apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-metrics-auth
  namespace: monitoring
type: Opaque
stringData:
  #ENC[AES256_GCM,data:T4Hkh4Ku/GhWmKGibTWNG5ds55FvyrqpiV/dhOFulB70FVaH2kIoT9HdaGkM5OJyqve2cuBPhhJXocVMUMgOoQidyMfHBRD6fxkO,iv:rypPoaqPbnE6zSuTln5VaTwWGmWW9SKxm3pM9W9hL/w=,tag:jWp6RCL93CZsmKhDENEYag==,type:comment]
  #ENC[AES256_GCM,data:hWINNmuYiaEDq7AIYSybIMdZz+TTrHK7C/1zlLA1wnJBWPd3n16lXODNy6gD6OnAgjo/wCCEEnboOUV9kqU6lJ8oaYg=,iv:qcnE/t6Uw9/Um2NZGGF2LtvAfIyaug5jkqLYOTkA5zU=,tag:loJDRS1MKSuA7BRv8q9Fng==,type:comment]
  username: ENC[AES256_GCM,data:buYbMDgi5A==,iv:vlEvRmAyThSlCFNKiLhABzpuTrmkd8xIGV7to47tkoo=,tag:LFLC+appbdosapW0Ikj2XA==,type:str]
  password: ENC[AES256_GCM,data:eUp6NvxFGW0Al5LWowwuUKv2kOE7FO30b3nJhJbjMZk=,iv:2DHxBTrf/rWEfmG2GejNw34/cyNeLIOiZHGnrv4j57o=,tag:pxvW3WFRQCfAf+BSNqe1YA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhb3RxZTBUN3F1MHo3Szl6
        ZmV1dHBvczZ1NklGZTRZbGFUam1jNzlQL2dVCmF3anFWOGk1VDdIcFVVbDNGcWFt
        UzVIekhLaVhlblpDMVc4UFdRbHMzUWMKLS0tIGZsWklNTXR5cXIzc0ppYTlRK0ds
        bGt3VmZ3Y1c5aDZrZE5QL0c5MmpITW8K4ESKGM+leSgwzTS1DE2wtHsGfl4tq2HR
        3j+y3Eu8JkxuoAxSpn8x/PZFzYw8rgjUlwbtw9AN8/m55uJWv40NEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T08:09:13Z"
  mac: ENC[AES256_GCM,data:jeGEoeR8CTeEPaz0X7POB+pdWprVuGC3akqi23faauW3noCWScKdDu4W7FtL4DyooV/SzgVBEvHsIpitXlHHC4NyPXMvPu9XfqbmUGtDYMnx+UBkZy1v1S2OAHqe1PAlZ3BimLDOtuWoYrONdM9xX3JuX9RKk6pM+/8dFHmjuD4=,iv:8Ynhdi+Dz2EVMGAKi+l/jaa0NfcQix4OUrR8DoHJpEQ=,tag:/5tf07Qu7qMPJHd7YFnMew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
