apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-metrics-auth
  namespace: monitoring
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:KsmK7y7LEQ==,iv:eGFC4AS62cm0qUjGGHx+0ciT8ZEzoBzeeuTtE7bu07M=,tag:7HUHJ7orO1njHOWq0D/Iig==,type:str]
  password: ENC[AES256_GCM,data:FibbGq66YgzS9I7J1h7TlNScG+puOMuDt1IOo7L/Qv8yyIUdPXNcSZU1y6s=,iv:LSG15ssjUahgKcRiXYAyWVYbgxogWNhFh0sqk9EGL3c=,tag:2LkFFRcUYxnrtknf885GMg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVGNyKzFvci9mN3dYbmdH
        V0cwcTBNVUJBb3VEd3VqL3QvYS9XU2hxSlR3CnhpZkl5UzhvTXdoZzdabU5rN0Er
        bUl2bnBUcVF6T1piZDNIdmpVSjQxQ00KLS0tIFk1dE1iK3h0WlV3MWh6cTJpS0lE
        N3RERjBmaTF5MkMzQ0ZNNHhDTkdwL0UK6TOd+cZDG7itJ4/6WRd85O6ku7pnZYJu
        p7Vx2Pwgpkljp9gAeHfOzl1jy1jGhe8M+yjljGhVJP6sbixQzxU9OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T08:47:10Z"
  mac: ENC[AES256_GCM,data:YrknFQsWnaGYWuufgD+D141RAhWiwFlN8q90gbGx50Hg3VkGSvWAlhFqDobyxxXiR3b34znwt8nNqkg3p1EGoALJx7dgyUdStTUB0Z7xs7AdjhyOOZ9QKxB5DtEo5YHaOGxmn9tEPxi6Om8PCMXjF3nU3fHy6B/aWZDcG5y107A=,iv:Axfc+aSoX+rC6sqKn9yqPv29iPNQPsA9ttxfYWBpuiM=,tag:ETn44ZZK5U3aeqa0uOHsdQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
