---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn-volume.yaml
  - pv.yaml
  - data-pvc.yaml
  - secret.sops.yaml
  - helmrelease.yaml
  - ingress.yaml
  - authentik-outpost-ingress.yaml
