apiVersion: v1
kind: Secret
metadata:
  name: nocodb
  namespace: databases
type: Opaque
stringData:
  NC_DB: ENC[AES256_GCM,data:QFFfzar9nuog4Zubp6Py073LAzaGPjY9o1uY/pvpxxA+lA1JYjYyjEcDqKALjWIvfTw6qmOBi9E+8w6zRonJVpJu+xNwn7e82oYm0xmCTy0Tb2qo/gKsjgZVoyXWqRPhhuYeL9ak+a7alZ3Sh71/62U=,iv:WGhe7nbVTGpqWJv7b12oi+udtnFov4LrI62GQqOsLuE=,tag:wVnr31yJWYk2kbvLn9kp1A==,type:str]
  NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:Zyrt0YuydeiByL4paudKy5LyXuedHSodBnG/C/P950tiPY6WxvSzPXNP8M8=,iv:mpdLqbFi4/AY80p7/evp0gEKiHp3OPbPZIrscWNQBCI=,tag:tyQkDa6LG43LtVgj2SHX1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R2llQ1VwK1h3eTRMMSts
        N09sd2g2a1ZNK290Z2U3WFhiK2Vkc3pxaTI4CjRMbFlkOUFMYklNMVowazZRUWxC
        dFJ1ZXJ1aVNERU1qYkZSODdLZ2MyS1EKLS0tIFVlRjFjZjd3M1loRnhzdkhNMGNt
        RkEvc1Y0S0drakhiK3BpRDU4eXAra2cK+AOQFOSTOJBtLrMouxOgtXGyCDQL8ufS
        B0CohOKwqtczILURe6aPgSEE2yQEBHpY1N0d5/oZrAucj8u/JxcKdw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-10T16:46:33Z"
  mac: ENC[AES256_GCM,data:PYOagP8jcxTnWX86Pq1p1X3gZ/+Q9dyBXWLNY7hX+oObxfu2XsLrbxVYw9hvbJ6vySJnWzdDTOUBnFQRUDxXQk1K3kTuh6tvzjooCGCV3L7rIjcLdYgq4hQc8yguUQv+6L0dklDe81utOPW0Nd0sCcBaYC/c4mzkxH2v7KLLjL4=,iv:vjJBUNmpjeM1uPmYXrOqxcjGPZiPtPrHDM4tO0sy5/w=,tag:NfsCOblkaSX/LERokSGwzA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
