# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-development
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:grjFvmlkmQqPZgfJQlYRV9Iwu0S+sTcahOuBDsT63eXXuPyFfWIgdjFVKlo08C0LRDGpNBBQnrw5ftl82wruPUEBYLgbbhpQTzLe030m9tp8t9/IxgrXiwVVS5zdojg1nM8m5FlOVIx+k/jmh6Jj0/SpPdQdvS3cKFj7bzQkeGyUfmKvKJnIuapqf7PE0kHlFiyYhzzWlx04A1reUjUgcGognP/DiLLtaOtXfJ4YK36HOX7aCymTcnnL9vBPts9bZcp5/sJ9P9gjy0jT89REaz9RdjJFsAwg1MIAIkdQDX+hcDOqbwg=,iv:R+RSsQk9r2e9sXE6pRe0jZ3dnbhzQw9wqvSkvAwqby0=,tag:o3tYMA5JaMrdec8jqqOm4A==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSERqK1U1VVpVODdkV3dO
        TTJOcGVIZEM4TXl5UWE2RFlFZEM0YzVMeENBCnNiWXJQV2YzdGpZUmprb00zdk9h
        MnIrNGtadzVQd1ZTVFBwT1hBdUtRS0kKLS0tIDhZSjl4WUV2QW1TQXFINXlCWkNN
        V244eWY5VFJLRzRKQXlDbWMzbk1qWDgKWDbYNOLnY4pAa5GoGSlvvgw+45Dfu2Rr
        bEZit72hkorvgMjPSj2hL5C3RmhmXvx8wx1C5TDrD1EwzZX7MQPsKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T11:55:02Z"
  mac: ENC[AES256_GCM,data:7IyukhyrK622ZE/ZgfFMw9YZ4S1jRaE3uro/XuHs1FCIhz/koMTqJmT5NYyFAoExZTQ7HLUJ9o+7Voiw7UnI8hwozYlTOo7hva2dHwiYZsJRwK0jW7Ebvtg/FUZ0X5JeS96T3fvFAp3pj1Yg2uanZ4oE/jc+7SawCTGgDEK376M=,iv:BEULg0ZVJxoEgIV+j0zbZ633DlheF27E8TYipzghpw0=,tag:2R7+p9Ar79xZHIBvpY9AZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
