# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: absenty-secrets
  namespace: my-software-development
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:HgHj0ewXZuQhI5gnBL9Uve2ESOHy4qT0qxh3BmgL4AB98Oi58Sj/KZBADGaSHcukFVntHr9fqQ==,iv:/NFXaJrn2J07Q2cI6HB9V61EGeUaM1CBkyqfdqKwk5Y=,tag:IK4olka38UJL/WigeIkeVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2amI0NHIybjFrdXlqQVpM
        TmZwbkdtTG5XdWJ5YjhxWlhZSEZOVUlzbEZrCkk2Y1c5RU9xdXdLbTdhQlBjaTBX
        ZVlranU5LzFFb29QQmloQnlhV29HRlkKLS0tIDlZcURyZEViMzM5Q2pnRXVPdHg0
        Uk1mNUI5SlhRRExKVnlmZ01EOTg2aDQKiAF9NBg2bzhPkt3pJcmATbgcWFwOIMZo
        n8X5dlBSMiM0cqgUcXHdBZmGR/rpiNC6dhDYCy/RhY56fl1ieaLxog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:54:15Z"
  mac: ENC[AES256_GCM,data:VbYoeVc5khi+LaIOhMymPSfc/eQzed/RzhYr9+XvZFSldzUmtf15wyTNiVj9sNgPnPnm06NhwbsYfw9zAg4UaWFLHUDfKs4aevBZu0KDbJQWYz6Mbb2busUGdkwUzjcKPa7ZoVW+GPKRMg4RN4Y7cmL8kSUX/QGK80W7FaJJ3pQ=,iv:KKqFX4ktN9xiRkNUGBVin7n98yycGJOdb/Y1t5zaMAo=,tag:kXKIzlSUCRF6OoMlon/O5A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
