# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-development
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:P/M6eUET8XFT3PLC9pcjjN4gp+Q6qHJijzjdgWbTDxASp7occLRSNu3hULz59hqsuENKBznHI/YSZupCxZNR12T+KJj3uvog4RfPBcFAj2eYGtVu16Ok91Ub9XQr8v7OFXGKNIpyhaCbUwksr0q7CMoNBd2keekXVx8u3U3AKbP4FG/TqUweFaCCUS5iMp3k531Km1lT+HNaO5UUc6dcUIb9mc6Rlp9WPT6qZu78U4oaF5wud4j7c1apLFggEl1Ph/8kUgpqdFCAxyeDZDCcoOF14cDlMtAZCPNqhCzouXZ3RgE9y0o=,iv:kZGQXIwldds30VeGSD6FlVyQGu7j3EdEB1lKoJokios=,tag:QOkNl8KF70Q6ppGDDuYyXw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWjlmaktzV2l0T0N6cXZG
        SFdxTVgzU2tqYU1zRmNYUDdXMEVFNExPNDNrCkd2K3ZoMnM3M1JGU3A1UXZlRnJn
        KzcwUGFVakZQTzZrTmphbngwQlYrS0EKLS0tIHRISTRjN2NxelpNK0tyWG1hdjN0
        K1EwUUxDKzBPczkydlNwRFh5Q1oyOWsK1xDvDlUUoT3hGa/pcxA69vxWVYHukln3
        P0bIdvs1c1P48/e2I7ELFs62c0P7adSWJpYKmRX9E1UNruCB/AVGJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:56:28Z"
  mac: ENC[AES256_GCM,data:WT5QISnXdHfxnxIuv1yJyFzWRaOlXlYzLS/qhQ+Tp8ITg7xfUYyLnXFmnfuNMBA7yoL7gwXFC0z+UbWuf1rd70tICAhuXrcgZHoQ2KqszB6aNS04cOQvBfCI0MjA8yZcdUH5JnUH9hknlyFv9GMwCh98fMNzU4RK1uS+PSrfQE8=,iv:FeDCT8UedTaZx1j1o8LxtGlH1sQyyDSqZxpNnlGePuM=,tag:4Dmcodi4NphSt4bAol7jZw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
