# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-development
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:2mrei6xSGD7jHbraVe02WzL2Y7SQr5mvMzKw39ycDuXK8NN1w38MStkL7nScYNSAA1p1LIaoPpL2X9wkzu2OXDTD5QZgcACx9iHXHoY0fKHdRIbipHW+y8TRQEqZf14EIBiwO4RuaD0Ho729nEOP2GuhgxwSNJv0qOEAzm5jA9x5gfpgmDYjelr1c8P657O9mLd7LaEkScSOJ4sIs8JbzqJCrCLJGrJCr+nQkgTsezxG3vLqXSSzBsqHRDWsZyyBRlwFYRoNzk67PYeFaqdZycfVvoaaJXy4Nyel9suG+677Q5oxNzg=,iv:aoBD4eDlTYOj/1BtPZI/6xaaum2lC2VHacZ24qiy4IY=,tag:yvOoo7hzIvjNLZpq2DVXUw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbnBYVks1ZHdMOWJvZXVy
        Wk5odmRWUmRteXllcVNIRFhDeFlpcVRndmxVCm9kNTd3TXA5TUY2K0k1MDg5RGxi
        V0pDektydGM0a3B1S1BBUFVrTVVZVjAKLS0tIFNpVHBEVEE0M2hMRDhiRmNvV3A2
        SmkzSXdLeHZLdTU0OXJZcDFUdlFSMWsKNX8u4VlNYNsYECCWeP+UlmZjtt81BcyU
        9wV2bG2ZgwJ+7Dkyw/wQ6Eoxms6MLxXPmxQ5VexzPdG8b4K/DsBvSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T11:55:02Z"
  mac: ENC[AES256_GCM,data:1w/jKwp7r8dCVHeAQT4E4XeexNvG+3ZIdJdrWXfoLSmfotrcQVNvLtqKohUZz+Ppkvb7DPHtztvQ3piMSaDhtLOGKsZfz+nND7O7mLAFS/kUubZTkWadpw9ecSUjMt8+U9DXpzzIbFiolGV9jHdSFmqBg+F3NvqAEZ0ZuGDvCSA=,iv:vplTDXjJmVhtp9rRY1xfeWAmhXNNP4UXvOl8CoQPaP0=,tag:l3XRdwGq0JZzd7ntmmtIoA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
