# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-development
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:rSvzZUi9EVF94k590z2T8pRA7cs7AkDdhniQZGzpjemcZ5i9dUasSLoZqvCgmyJTiZkWdEI/xDWu6NWKgzAmPPmAtosLqnRItTcRUHDC38oIZ7PLcbxx7Ed5ihIh8Sj19Tm7fwh+DdAOlgro9E1djDzbxpmSFuljLfLvM6t9cmSm+R/Zgp1bmzOt8lnUdX+Yuu890CPJUe7JLCVIJ3raU4TnY5kEqnLNObknP/Ft09DnbnbemWXFGgHJ/hyw1lH0dH4SzsYG8P5up7C8f3QfEihXL3R+gY+9PBYDt6UGiObfgtaaMv0=,iv:DLQ/Fxp7lRM3SGsLIos3nB1BgCUNgDL5NVwUa4C6ADw=,tag:AgeY8U23YjOVy1S0By0K3g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYVlPYitVUVFWQktxaHlM
        ODVnWDRIU2d1N0pGVWw1bXhvRGdNa2lRUVhFCnB1SnZHSmcwKzdjb2NOVmIrVHdE
        bzNFcWdFdGtNOEl1b29pWm94L2pFeFUKLS0tIGZ4aGh5SFZhMWllaUNyYjA4SW5x
        c2ZvRVI2Y3IrMTgxcXd0NzNHbm14d2cKCXxS4yhaEyCvPVOGjmvVUKouhVbbMOMH
        5kEYDxJZGp9idIGiHBZ8d8wOiVwo8ASdG803NWSolCElbWPfocamkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:54:24Z"
  mac: ENC[AES256_GCM,data:GadU03yOWO/HMPfGOi7OdnXtT1f9+knbic00wN+8syZOjEdhDPGJpeU7DKFc4kWAjegYJzwn+wfHIJxM2k1i73BghUUWXt8ujzcQPOqhVXArVAlVNnQzkwwq93Fe8yx7ggi6kjpcktRw0RiwFsIGR+r2UxsUsExa3U6ESfSil/c=,iv:p/ckG6XVg+UCj2AtRI7parZqzUmcbmInkWlqYb2/m8o=,tag:rtEF6eQ21ohrHJxrXo/X3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
