---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: http://external-ingress-nginx-controller.network.svc.cluster.local:80
  - hostname: "*.${SECRET_DOMAIN}"
    service: http://external-ingress-nginx-controller.network.svc.cluster.local:80
  - service: http_status:404
