---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-assistant-alexa-api
  namespace: home-automation
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
spec:
  ingressClassName: external
  tls:
    - hosts:
        - "music-api.${SECRET_DOMAIN}"
  rules:
    - host: "music-api.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: music-assistant-server
                port:
                  number: 3000
