apiVersion: v1
kind: Secret
metadata:
  name: music-assistant-alexa-secrets
  namespace: home-automation
type: Opaque
stringData:
  alexa_username: ENC[AES256_GCM,data:z+T8nD0=,iv:GMfHVulCs2UiEwuMdf5ZKVESFVz+N+iUSXKbAGItsrg=,tag:+3fsXb3lizxnhRMPEWP4AA==,type:str]
  alexa_password: ENC[AES256_GCM,data:BjQ1pA==,iv:v2r+9kzJHcHqk0cYNSPYx6X18JJFtXq6XotsG3EIyTI=,tag:G9FYwb4qV6iSi9xpk5/14w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcVlzMHJMcSs5Wmg1WXRo
        QzhzdW1MRE9PUVB2VGR3bDVBQ3kyRHE2U1c4CjkzVEp3WWFCaFBKSGxHcU4wWWdX
        Ui8yQVJRS1I4R1ZkTnZpYVhVREFvT3MKLS0tIGlWSUY0UEs4UXlSeUU5TVl6YWNT
        Q29id0JVekZ1L3dxRXBMS0RtQlU2WkEKEIrDX6tovAYayKaEW+y6sAMz3l6Oj14l
        ltPVQXEOeMmvLCbaWXcpEylOheO8io7ZyL170xr2XOscZ+qwkbhLQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T17:42:27Z"
  mac: ENC[AES256_GCM,data:iWTn3IFUGh93KS58vr6jcOo9WbxvxhAhoTDSnlqvMgA7SwBxIqNPs0XXcUhQtQbQPeMEkz2tts9ZY/NW70PH1TNumnMAymB4I4L2G5Q9yFrnqSbS5pe9TSxUidKVJIu0b7JjZhNkd3UTiI4G78M+lZLS+yT78oE/DFPpQO8qGTY=,iv:tfaf1nbXIg62/9jXzct7/oHVmcFsimn9UCcPuodUkCA=,tag:2dfHpIpZ2XDKCUh0YDSZiw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
