---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prometheus-filesystem-trim.yaml
  - ./prometheus-snapshot-cleanup.yaml
  - ./influxdb-filesystem-trim.yaml
  - ./influxdb-snapshot-cleanup.yaml
  - ./home-assistant-filesystem-trim.yaml
  - ./home-assistant-snapshot-cleanup.yaml
  - ./openclaw-filesystem-trim.yaml
  - ./openclaw-snapshot-cleanup.yaml
