apiVersion: v1
kind: Secret
metadata:
  name: csi-driver-smb
  namespace: kube-system
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:xZ7qmFJrfh27Urgw/L/ycg39AqnRnkzt,iv:VbNgRn960vL8m1CWR+HU9Y112zaG9zYaf/OhIHyGPi4=,tag:/bV9H/PNbcQaz+cb+LDesg==,type:str]
  password: ENC[AES256_GCM,data:tLp+5/rY1WXebsTO56LuIw6egCOC+7sP23u7WJzfB1e40w==,iv:gAqM4GcPiNvwCnOV0uYr+m4AYW99mw5RVcir/NiICAU=,tag:yG/LYEK8UnmpsfPrRJJxiA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMG1WUVVpa3pXNmdIWkc3
        S1ZaM2ZrU1FEOVREMjcvWGpISXlFZS9SaVdjCndaQVM2dnRUaVFDZWtiWW1PV3Jy
        c0Q1MHhPSXN4S2k5VG0rVFhFaTJES2sKLS0tIFVrYXQvZjVpRGIza1hzc0hBUmlh
        RkVsNTNnU3hoanBNOFhzbzVQcmMxMzgKOvC+RT20SZS2n/gSuU96fwldfyZ3VScY
        FQ+1wzGaKmV3Rz5a9znZISJRtW5UPvQICADn27crpU6eEV/gI/SlOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-05T02:12:50Z"
  mac: ENC[AES256_GCM,data:cNr/MOmO90P5+XQ+xLNVs7l/tOAj2JFRZHWjScuXSMoAAceX8WE47ew32KG+XnFYCCSt32Pj9WO/DAUX76GeU8Rp5SA2lef1obMt72qeWdmzoNgbwTF+JlaaUX3rxVBekFtzq4p7QeRn+HkEgySPy5p5CQICpBJSquZ6DDU1N/c=,iv:OeSkh7kg8trkE6yGyNtbUUBWlQDCLlT1vU7wukX6UFk=,tag:OBVVGSGKXTOpUAIFN/Sgiw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
