[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBERNETES_DIR = '{{config_root}}/kubernetes'
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/kubernetes/bootstrap/talos/clusterconfig/talosconfig"

[tasks.deps]
description = "Install dependencies"
run = "uv pip install -r requirements.txt"

[tools]
# Template tools
python = "3.13"
uv = "latest"
# Operations tools
"aqua:budimanjojo/talhelper" = "3.1.3"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.12.0"
"aqua:go-task/task" = "3.46.4"
"aqua:helm/helm" = "3.20.0"
"aqua:helmfile/helmfile" = "0.171.0"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.34.0"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:siderolabs/talos" = "1.12.4"
"aqua:yannh/kubeconform" = "0.6.7"
