apiVersion: v1
kind: Secret
metadata:
  name: paperless-ai-secret
  namespace: office
stringData:
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:EN5AyxvN6ITuV6mQeXlVGzjsajpYJDMirX01jpOuVPVAbGx6iZ27Zg==,iv:cSetj+lGizuVPQuDyYe54A/eU7wfXoOFi8gFIMQ5QpI=,tag:RSmEdrNJn3v24U1N2ipCGg==,type:str]
  API_KEY: ENC[AES256_GCM,data:6dkPC009yC0mkg==,iv:0aUiIjgxvHejkj7MW/zkPaavplgBjR2KKKYwPsfWlSo=,tag:cH50JqmxXRIxvTR6rEd5Tw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:vsD+pNs1sxpU/w==,iv:etTVXaNazL5IKP6YzqtAAUzoRIgxcd039hi3ruoMtwA=,tag:JwH6i2+rAmVbsB9XjLAEBg==,type:str]
  PAPERLESS_USERNAME: ENC[AES256_GCM,data:1tXOcd+pgancug==,iv:tBnxGRifdeIqALXveXk8fJqEAAiQbnaZEATULMxndXQ=,tag:BM7Gks4m/vQxrpDY5NRDeA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWG1mSjhLV29adkpHNHFB
        dmI1aTNvaVdGS1RWYmx3MTVCaktqZ2tZbWljCkVXa0ZKMW04cldWdjljNElyNTBO
        QWRSZzVJL1hYZHZZb0xuMU1JNmNPRmcKLS0tIFlZelFRMWcrYXhra2tWbEFlVFJC
        RXN4REZBYlJoL1ZOMDFFM1dUN1dUUlkKRMXKR42+kWxR5w6L3+HsI239lQr0jHiz
        og35xX6bPIlMfgyZ/QxMHBFRMfVDmdcvs/yb22g/fma1CKgJiXEWZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T22:50:14Z"
  mac: ENC[AES256_GCM,data:KKVqNPr6xTUDu/h2gW4FXP+eqfK3hqUIRo7/PAnXbmujCg8q0ocul9yTGZh/wNLhW5am9O6fvmrk4TS++XFYbtpD4HplXxOUjcSA93htJGpxzNywGOgAP2NFXoBXhOf92jQh5UArEOmArIv4UOKVLTXQKaSTDZz0Rgtp8SnBayE=,iv:QYm34/kb9dqyqHR2BT5Oqlj8PNfZC9TQlsjXGIO8HM8=,tag:N0EhRL15vr62Bmdvkul3uw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
