apiVersion: v1
kind: Secret
metadata:
  name: paperless-ai-secret
  namespace: office
stringData:
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:1g4bjZxT7LkCy0RA/l1tfHrqVbNQChIsXEnzmrvWHtaJuVBKpX7VkQ==,iv:/iZ1bBzUfk+0YMo2s/qe0rlSSCVMxWnad9gVOMnU/3Y=,tag:s6Upo4f92ZmGDZMOhjf/rQ==,type:str]
  API_KEY: ENC[AES256_GCM,data:grl4rngu7vK9yQ==,iv:btrWEmyfrPU+z8G0zZ9nDpK4YZj0WtmBmijT5BQSDVM=,tag:E+0FACDkk9xiKW5kXJStsg==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:mom2t8ANa/gcLg==,iv:CkuP+XDhWNFq/9XVGusnEcx2EIrS2ko2hoUvSOJEMYQ=,tag:SnxIWfoguclU1sc2WXnTww==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOExJZ2NBSklwRW5TcUc2
        Um9DNTJSS2NnVnNWbU5BU0VNbW5vdWRlTVJNCkhONTNvNk11WmxZSk1FazQySmp0
        Vm9xc1FVeDNhL1VsRS9hNEllZ1FxclEKLS0tIHJ0U2Nlb3dUYW9NR2xiM3Q1VUZR
        S3NoTk9WVHhZazRBSlVPYngrZ3VNZjQKMWxdcZEZ5vgxMCpPa0xXjwuY2J/5UECF
        +BzasuLSkl2AqE8QqKkHkyPlw7kOep0maer9UrTHYLcHElr+T2P0sQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T20:59:39Z"
  mac: ENC[AES256_GCM,data:J+92Z88L5g45Ffwt0rkY9LANd0FszU6oP1LmMTV3BrmjSxMXln76tIoJDEhXjUB1rJXFfuXoKGIeln2C2QMcDqscicRRxmrlayYvqqni+1sqvhPEVuMl/4QMXwxqdFKrGxX3qlh5g3tM+COZKeD+NApOlom5PTnO1NJi/AGIBTA=,iv:agEFvkOajD8sKdAbvWI75WxCCic+Ce5Jk2onxWBKqRs=,tag:OYLcQHitQl3ZTXCsOXAU2g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4