apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-oidc-config
  namespace: monitoring
data:
  auth.ini: |
    [auth.generic_oauth]
    enabled = true
    name = Authentik
    allow_sign_up = true
    client_id = dU49QBcZV9zCklzhdZOxEALoA0US0HimARDE1yfo
    client_secret = TebAWN8h2M3xGHkIUTH60dCJYbR4AJVIi0CVrGWVLqhBAYlF96HIYCi2RvcB5H9c47UgtGSWynGS6nT9TofGQYGhRVDgEVzsMlhIsXRSWgxjr6OPCJJAbm0N0cgrnhcy
    scopes = openid email profile
    auth_url = https://auth.example.com/application/o/grafana-oidc/authorize/
    token_url = https://auth.example.com/application/o/grafana-oidc/token/
    api_url = https://auth.example.com/application/o/grafana-oidc/userinfo/
    allowed_domains = example.com
    role_attribute_path = contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || 'Viewer'
    auto_login = false

