apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-password: ENC[AES256_GCM,data:UHmdEGjQcA==,iv:z6h5ia0stZyiZ4FfKxrua97W31k5FsVQbCcrNBz38Zw=,tag:MdjIYaHKaS863dSPP9BW+Q==,type:str]
  admin-user: ENC[AES256_GCM,data:fH37Ggc=,iv:PLW8Awro/nyS7yJQJh5T5JPZIgZKWeE0AzdqY8413ag=,tag:DjQOBQEvHHzBdf7OHp6O7A==,type:str]
  oidcClientId: ENC[AES256_GCM,data:d6jkrp4x58RNXhThitmSy9ed7airsUceZ9CESLwL/5kByGt2CJRWiw==,iv:lT3B8P48bK1X5M4ZpcBdNGPzh8jiQ4vMILZFliDkU0M=,tag:jJS14foAch/oKOiTtq0Mrw==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:ctY8rIAqKo7pUOBf4hvRE/QPdkWCK5lM4wpZ/wNVFtdnaNHbgYOqrl37lnTv+snWLhLcEhc/aQUKz3qqUhIXrU0Jr78prFmzlp4Cosk1JWoB5HxNL/SNI1FAEofS3vzMlqmG3buPI4ZBWypRGpnMcm0Yjq4TkW1VL0PfSeAzlf4=,iv:Lr7U+pH5CJVFhEK/In5sGCfASGOuucVEyxGehj7VZtg=,tag:cNgu/Pw49TSFMtwfktqzSg==,type:str]
  #ENC[AES256_GCM,data:EHDDCdpBmg9qjo4pZyk/nB+xnOsG80lBABmvzwkXp7+xQKp44RvDdpB4kpkcmhvFcN9Q3XKzsA==,iv:+/VIoz9jjhbe4O6ffSX+De3OezC2WFm/yDSZ4DTxSzk=,tag:ugE3N2dG8LoSWwrunlRXGQ==,type:comment]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:W2BCZauIR+GMWE7fIBEnnN2MEwx60ksd8g2HGCfnQ2Fi7m/O646ZEw==,iv:V7I4U6njGKRMenNMnRtAf6gIo242DUS3E01pi51AczU=,tag:z/68SwjTsT0KZrnZqbAc+w==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Qi8ELJDNNtPGJP5b3o4M8ioq0rjaZ0MWrZExERPHDgcz97BU6LwXwJCOAiqyX3Cn3IPyMxRx+wOGXSxwkB+wabxCFahDccD0wHE3mXdpwwPorZ+LdT4Kg/2QuPJoBSAGQmrqOtxYkoLy7y+GXEVLkDIZPKR945yBiHmhSDFwarY=,iv:ElqTGJT2mlpSBkL08nk75VEyYcCcupo/u/2XvhjoT/w=,tag:aJnOjazZMaOv2bah5PosSA==,type:str]
  #ENC[AES256_GCM,data:vINw6S4GYDpb+PhQP2ALEE9tvy+5y5nyQuk2F1BX2jCro5G/eJOJ4NQ=,iv:KA+INcBeIKXnABTv7Bd5NG8nRCPsx5suAkRDwQRu55c=,tag:xVEN78GxYUYA9CuWzORRWg==,type:comment]
  TESLAMATE_DB_PASSWORD: ENC[AES256_GCM,data:ngLe6RuTBi70MKXZ3Ci4EOLEKuvXNttHFLJ10Qno/Lc=,iv:7dfpjUiHAAHqRmFNnWqccKERU+K8S6L+fsLXcTpCPIs=,tag:Qcd1ALihP71e3R8FBWwVtg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTWFvSDhucFVTb3BGb0V2
        Z1hERlRqT1FwOTU3NllOenlZb1RidWpWTFFvCkY2MVVmS0hRT3pNQ3Y5Qzc5U0Rz
        eERxOWp6Tkc1YzNwY0IwWjhGb25ZTWMKLS0tIFdtQ20wZnFhWXh2eTYzYUxCRTdJ
        U0VjV0hWOENPTHhRRUh3a1dNMHY4NlkKCQgaOh2lGa5U2lrHkOYkwXV9Cyq2rjJr
        sEKS9Ct6iDM/nE0WpxkUC+cRgUtW2bvK7leN3liYtYhqErQYw6wD/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T20:55:50Z"
  mac: ENC[AES256_GCM,data:2qhB7M5Olpbnb6ETG35Y8dq+kDwUo+x2giUl0JT6l1ScCeAarf7GdC44VVlXBRHPy2xEiMxOSKokvTjEkjBHP07vslp2zc/BdKgChlbbU+fIDB34iZFyDkCdesGsWiGe/4Ormgt8HAnTa4ArLDaMq5TZmndXvxnfRcPLNPH88q8=,iv:l3/R6biArVpg3IjTFe2Rbvs8UOFiI26Up5hro/mEIr0=,tag:QIrxXrXbOtLpNM4Ixz+drw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
