apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-password: ENC[AES256_GCM,data:7gSo/tlx2w==,iv:SQbyqMQFBL6YNsusuRWEegH28uP4GTTRNlBPNEsMfbY=,tag:4YqduEQj+ggNZJguXw8/0Q==,type:str]
  admin-user: ENC[AES256_GCM,data:oRNFe4A=,iv:wbqbuTGSuo2TuzlL1Vgf8ufDo+1uRpFdvy8OY20mMgw=,tag:Sb45M2i73QUIWJtQHIoeMA==,type:str]
  oidcClientId: ENC[AES256_GCM,data:/fIcrWOBmzJR21X+vjaR5BFR5NG0aYPOtiPLqi0ycuFsfZ7QR4qm4Q==,iv:gbFYeEfDXgiMZnM39PDLOeyljldRg971UPVKYNV9VZ4=,tag:cGmpAl5Cpf7FRjo1ZeHLzA==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:Exyw874l7s3dDjjSXzo6glPJT6UiND8tXjAmcjk2UTha1yHe/mrajOtAQAuJ4XGn8Ynjqkn1bvnWjf8a7dFqLLy3vSqMniUkwcPD/W2H2vMNS5+iZpZy+uzVJIv3FPscssJqIjhHLRN01mmizXqarlqN+O1V6bzrnNKZoHpEJ7Y=,iv:G9RtBDUagriGpGwO2MTf1yUmw8mTL1+9cuOE1QxpIYI=,tag:AUafLBpBMxA97/NzFuZ5XA==,type:str]
  #ENC[AES256_GCM,data:KwAAuqbRDIdOiMO10xdepcumd4tJ3DGoIK9+5SlBUwWgXY31hnnflEL+P3JHeHTtS+V2G+GsLw==,iv:6YDDVBuWDk/2wSR3kQd5eftUDRbZP8fRyjrzl00t1g4=,tag:SR4Tv6g7JiOcF53LGF6Qjg==,type:comment]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:WnMbFHIFGkw0asr2BWUvnM0mPa1Gd+mytMomNe0d8ob9z3aq5ibzNQ==,iv:woReiNdAhi5TL7b1l9to7UM9hNaHD82WVv1ZYnCdvvo=,tag:9UVkJCEImDygwcy14nKJZg==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:fLLowp295+EjsxfBg7FUU/58qcLoUErt6ZTyt2loh7fgqRCvVQBj1ABIc0Lh2e7/cvfxlyS8ub/DVEEea/mlcZB2YtbEkrde9aAWnZLGtj5jn5bN6ujK1sujeUBo9bd4m14gVVY1X9iuGqA1enRA/LY46PCdhetS2V4/9i9VuBM=,iv:7oV9pvUoVLSJSoNaQ/RS0TyzIgSjFTguvJouHSlLwow=,tag:zQtoh1SgeZK8A4Z4IHW3Ig==,type:str]
  #ENC[AES256_GCM,data:NoXWXWKcUxYUvpFcb1ZvMDljqDBrhHU3b3W2h1yGxtkN04lxiLItFx0=,iv:LJpAWAbnsskPfiY16dsEVeBSN1fttoEhDn4qrPHYGfI=,tag:+FhTuq96MeiPOXev0nnPgA==,type:comment]
  TESLAMATE_DB_PASSWORD: ENC[AES256_GCM,data:UfN9dYBHzJwxQCpbDlFjirLtV8stSCXyWC6TDgucVl8=,iv:QUXX7gCfrvhZ/YZCiRUTQnXaSXN4JFaA4ULSw8aDdyU=,tag:+AFKYMEl4wayA8oTtZB0RA==,type:str]
  #ENC[AES256_GCM,data:M8DTGKtR9xvVllcp9m1QZK9BMcw9i3LFMIdq3m45/plTV9i0OkYYylDVdIg=,iv:QfEzWFuQkG2BIz1sxM3xvd3ybcruAb9l0borj78FX/w=,tag:d2CjjoQatcT+E3jYQg0xKg==,type:comment]
  INFLUXDB_TOKEN: ENC[AES256_GCM,data:h3xXDN4Iw5pt9wdNJNKIlXMDhApPE9CHlzCH2mBC2VTLpBYK8CRwnxzc+8Uxj2Ppgqf9embmU4PyrB/WMbkoxxUD9Srv794EPyeREY8H6e+Mhj5XmluDAw==,iv:FqyN3feUkisSItH/6hB2bRtLHKqJkGt9AETezbej/AQ=,tag:jMAwjTivL8v61irKvl5i1Q==,type:str]
  INFLUXDB_ORG: ENC[AES256_GCM,data:EnWptHJwBHVfhQ==,iv:hOAGoZENs6JHynFAGaP/FX4Wh5XYD3WcbOpYWgtzNHQ=,tag:GABZw32B+dHHh7wTsNmsIw==,type:str]
  INFLUXDB_BUCKET: ENC[AES256_GCM,data:DlXHvCP+wg==,iv:wr9cxQ3YW1LEq9kJnYOiYX1D8wDZ8wRo2E+hMvuWm2k=,tag:OydXHTKUQBrJiGWXj8oWAw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOS9LRHJlbjd4WWx4NVpR
        bVh6Ny9vUG1kQk9XeUNsVU00cG1ZVktMZ3pvCloycmlyM0J0TFgxSHRxZlhBY1Yw
        Y29jbk1SNklMZk5FNEMwaTZEc1RYbjQKLS0tIDdvcTNibitoRWVmd1V4MUlEbTk5
        dkdoWmI4U0hKOUVOcFhMUHp3ZVFPdW8KOFpT1cqqDRcV1/RlX4DRxgpyL4I84Fle
        QVl7N9LkaGcSNvRR5KJiCK5mJSABG5y1jp2eIsI4rgvwFKw6Xe71Yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T23:39:10Z"
  mac: ENC[AES256_GCM,data:8dXV3cVzf23X4r3+jLXXNg9McOzo3vy/R8ul0QtKMqIEp9rV0+MHwPnbTt41k9PbjPyUtHrGAG4N1zrqzGM4XPYKRvgvHItHOuxxf29PpEIdPCKEt4+L99iPk4QlDk/XCm1G0a9P190LKN5SG0fx0tTnIZOj9Vd4QX2OERw2ucs=,iv:/Kyczr4kcEbh3p6Lsf0aBBbYaUi/LV7elUdKhNtK2K4=,tag:dvaKPzMwZHx24bAw/A5ZkA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
