apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-password: ENC[AES256_GCM,data:2YzioWB2fg==,iv:owFR6x+uotb5k+53XeRG3g1o3l21DfxVIsib3Hl57J8=,tag:h7nCSXNQjTjSCOUHR6wNzw==,type:str]
  admin-user: ENC[AES256_GCM,data:Pj9qslk=,iv:5OzQxTjfELLPDAFkaSH5Ol8UXEBuFCXhgaKbmpneKXo=,tag:r5PHiohedYWCd3lD3gxWbA==,type:str]
  oidcClientId: ENC[AES256_GCM,data:jq6fe44LWYHqZjs2RNUoNS7V7e7EqICUnusntFeSTjlKLLvJjEmd2Q==,iv:0A08IIG5oiejvH3O36EWlOS9D0GFBHFbxBB8JLXcQUI=,tag:98zPYuA5xh00MiLHtpOxag==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:4aLFxnl7d3DMBnf20texdRNI09IKdz1CaWXGAi7iWR3tfVde8gQaMxfnIGajdpfeb6puHq2ah7+aavwyk2bzy0A1diwE5O/juYffTzEF2foXdXFzdXhKv/qtZQl8rzKJcbfo6x5g0Y/Ax51BWJLuyYQuZm39zI0+ZPpBqUJWxGI=,iv:UFwf4n0p0g3A07Vd/olFVOp6L5dv5bx3s19WKqwwl0o=,tag:oOnQGsySm+fA0h2kG5U4CA==,type:str]
  #ENC[AES256_GCM,data:5LqQ/lWC/LiPicSxU3sGoctrgHu5eWLkSBwYdd8XROWz6UjHb1iqk+RdxxvBoqQkYV3DNE09sQ==,iv:HQXZ3vlnU48PBSfSruOElwGG8DHNa7fI8/+uDOKIIjw=,tag:J+X2LTBn6ueCem5hHBYcsw==,type:comment]
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:h6Sf0a4Z/2TelywwYN7Y/lg2R+/G+x5CaKrkEaKuk8ZehvVGBxkRPw==,iv:2E416+AD1oz0h77XBEJiZD7sw3tOnW05aH2Z+6P1Ikw=,tag:4YlK4UIqOJdw/ad6sfd5XQ==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:acoUaCqaCZ0N0JvyDU91q7VT2qNld+KHT8gsFnrt4anfSswV84juhIVP8MZYW85I1UkQz2bJYSkl6PQRO6QKVutY0khJAOwMFJ3WZibzoD3Ifs9hAKX2kpax1WWDmzQAA/KhpZBvsaqhLVYFyj28oX48yhtXaMu9V7lLn3VgDXU=,iv:S7cygJi0FO5DhZcAL+GnazR9pONhSih1A675KZVW51w=,tag:oGGGMY0zsc5zaOa4jD+L2w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYUNSbGhQTU5aV3pCSnNi
        bzU2aFZveTRBbmtnRXVuYUxlSTVHWmtlN213CjRVL0dYeE9HT3VmTkZPVC9rSlBy
        YTVDemN4d09MdzhOY0oxS3ppbE9FU2cKLS0tIE1nUGQ2UUNSWm9vQWxXcHdveGJi
        bitUcWRCNDdKLzhqa0NSZjBhT2pOcm8K6hVMYUNhCjqypdgiergzeo45ZWACHq2f
        8X2HQYEnygDOLMc0UwxOgTqld8yxjUciCrgeyRqudrS8DtTBs1wgpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T19:10:25Z"
  mac: ENC[AES256_GCM,data:SwZ5zt2qPAzlsiS+WpsltWPaPXFO9WMYUlAmdNUKFWkacc1Go3SqPrF8NnRtpoHKle4ydyvK/ScCMgMK1e9HEwlfRIYieHIxATxbcc1HAsGtE020ZMH41ALXUPOWWQiHBfjhFYllwMBeuv5CDuHoYiN7ydAgM2ft2GA0a+cI028=,iv:pTNoZPzCtV61pG0EfOpTfdJASSBv811p2YEeG3HauqA=,tag:dOsxz6ZL8vsOMm5RjpGZEA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
