apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-password: ENC[AES256_GCM,data:d7RfyRaZ4A==,iv:WPfcqYvp1v9bjuZghqL90/+KZ0k6kHp5aeErMTV8ZY8=,tag:A5QEum5Jm/4ydu1gcYJ3Ew==,type:str]
  admin-user: ENC[AES256_GCM,data:z9Jqo0g=,iv:A9kru7iIYtJve1mXfwN5FRkODWek40TAIPtZ18Yx2m0=,tag:qWaf0i29/nao7rNBatG5iA==,type:str]
  oidcClientId: ENC[AES256_GCM,data:i3qTk2BEJ8T12ZrPjgTRAnn8rZm+0z8/s1gorxjqkLgsGV+LUtqqoA==,iv:Cge5gDByd/w4kDEELzWiWTqsmAP3ZuVhY2Ijei/QRig=,tag:o6Gk4yiNKEybYeIKIMGnZg==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:8q6266qzOqNB+YIlFO0vnknFYys1mYS4BfhJu+53GiQh9n+wjxXX2dMpB1kVtYdLhkK68WhZmrdieje9Y9mue4FCj/0B8XY8ccaWBux089kNz23bCNSnbn1mkcgv+MgUNfPV0TOgvd3qZGSXP8zlSrxLWdvtKH6/eOlzBPGtpoc=,iv:IXeIIZqsHsOtb3EJmuOnDwMK00QNXU5t8yuoqYE93DE=,tag:EXItlfNpL8Wy3Sf1cqHcIA==,type:str]
  # Grafana OIDC environment variables (for envFromSecret)
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:i3qTk2BEJ8T12ZrPjgTRAnn8rZm+0z8/s1gorxjqkLgsGV+LUtqqoA==,iv:Cge5gDByd/w4kDEELzWiWTqsmAP3ZuVhY2Ijei/QRig=,tag:o6Gk4yiNKEybYeIKIMGnZg==,type:str]
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8q6266qzOqNB+YIlFO0vnknFYys1mYS4BfhJu+53GiQh9n+wjxXX2dMpB1kVtYdLhkK68WhZmrdieje9Y9mue4FCj/0B8XY8ccaWBux089kNz23bCNSnbn1mkcgv+MgUNfPV0TOgvd3qZGSXP8zlSrxLWdvtKH6/eOlzBPGtpoc=,iv:IXeIIZqsHsOtb3EJmuOnDwMK00QNXU5t8yuoqYE93DE=,tag:EXItlfNpL8Wy3Sf1cqHcIA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOGtyUUgwLzFORHlNS2pn
        MWZvTmN3V1NTd09QOUxjNDhYbTdtSEtnT0ZVClcyMUJYYmV1Y2ljYkRxSWFUQURD
        NDUwMXF1eHBnOHY4bGtydjVSajZkS1EKLS0tIHVURzVBSFQ4UzNkdm5DeVpXTFVE
        NnN4MDZMcFg2OTFxcjBVK1dGd1hWTk0Kh2iLtFBpvCLaBj7KT9yk8sHz61EcaPAA
        wR2Hn2wPivz9whBYSRKAqEuD7eDjhTAAw3Qte0BgAZkHKqfaXHPsNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T13:37:28Z"
  mac: ENC[AES256_GCM,data:JkPToqmypx2/9hBsOUenaVHpYTPhBu5FfO4nC6wRaDdOvWvUWXRoC5Zva4B9u/dpp/uZJrE3qJCLvaRU1KQ7mmz32dAyWJZ1F5U5ncLfY/mTwXRW1h8uqJDyJzmenwUYosz1Cpv5Q7bNXqvAdk72ei6iVhhoD9FkDtsVQTpgEhM=,iv:gYq0OnQgYQMmxKLxlG2i5p4xgZ079bPgypLl4E2/4J0=,tag:a9W4Joser0icmNpmBBYk8Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
