---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - service.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - dashboards/dashboard-network-sites.yaml
  - dashboards/dashboard-uap-insights.yaml
  - dashboards/dashboard-usg-insights.yaml
  - dashboards/dashboard-usw-insights.yaml
  - dashboards/dashboard-client-insights.yaml
commonLabels:
  app.kubernetes.io/name: unpoller
  app.kubernetes.io/instance: unpoller
