---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.sops.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafana-dashboard.yaml
commonLabels:
  app.kubernetes.io/name: unpoller
  app.kubernetes.io/instance: unpoller
