apiVersion: v1
kind: Secret
metadata:
  name: unpoller-credentials
  namespace: monitoring
stringData:
  upConfig: ENC[AES256_GCM,data:4fzpz67+oyNC7hnByTwzuRDI8OL1Hghkh4Yeknl+m7mhww27qbVVaavTfToedKRhB7Ob96jhxjtlOWAIS1zvS0l90raaHge8jE3M4XyC1WTwkpyn50b5W+/VZ/v+Jj3VMtHJBwJdxerbBsF/0RhcblMXLZJs3tHVsL2240yrGJAkrT9vdBQtHxshbFxg6w2cW+n/o181tw3TFTa8ifF6cZOjqE6mvnLgl7mRKnobYimpFaQ54nXeyPOZeKjt2ZHG2/8Xe5u+VgOHGxqGbKdpehRX26YlwaVJ3RIGCbgL4DouklkWIow9gesvRx0KnyS6d/QcfP0pCXSguXw2/tpgtOnHLc+AwukipoupxkAvL7cH8fPcx8J3NCNM6KWC1FH2Bf6IhiOjFUW67ASGS2GfUgxU+8goJJ0UCZhKCNCpnGXWbn88qB9D7C08S0dJ9L5U3bVhNB3KaLIskrtBXOzuCqV6lDgXJh64t2/ljZe2W6fFKDTg0coUm1ZqEEb1upK0SuSiwePELDLWei9ZYq1NVRX6fFQHcrn3kOZzPIf2bEQ5Ri0054kQUq14AyktXn/jBNyBYIJTlOqudKisI3R7I9CBobAdCgxJp7gXbcOqCw81ZSUN1N/qHezCzhiCI+iXrLgjhIYaVT9b20Sp9ncYLM9ZvW8Yuyllp+zBm99lpgA6msVUFhlfv5uQ0XhQ5ET8kcRNBLOSrMJnfyqwZmuWrqUyHiK0Xy1sfM4kcvWvuGa0IrIE2aYokKmTALbrihdKcVt+B3THSAFVcangexkBVVlSWkR9b/6cljPM3aeS1rYU/EOlOsDLA4xEs5mJcz8phl5Ry14JpFPH6zuRnca1Zzw=,iv:mTak9RD+Ze6BRwMc0rBDo8wxpltuk+g/VdkNGTnzTxE=,tag:HkQ5Ts7AiUxXe8TvYJ1PSA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSU13QTBsNDdsTEtDVFBV
        TnBMOVdJWTgxM3hwVTNCOG9EVWltUmdURkU4CjljOGIxUWUvSUhHbFpQeGErSE9H
        QXowQ05hRHpTelpMdzRVSlpOeUpyOVUKLS0tIG9HOVFvb1RtNk1JMmdqc1d5VXVz
        cFZhcGJ2bXlkK1NmU212YVUxN3hlQUUKafCWEesMaHzGIohJFJDuzaBmv2ZwmwBw
        B9vfokwI5ffpPpztvHswaNL7vzF+V/r/c7qkxfLy6NiH5iXmon7n4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T14:15:27Z"
  mac: ENC[AES256_GCM,data:Q18HbOGbe/qO0Cyjftqj6exCyUbJN9SeUufe4E1ZAMtmFDNIo3H9MZSgbON0B1K9R2+Vf9lYUJ/gxlu/4AF6BORjciLhE6BGtzNRzkynmFHrbaUrrq/hMj4DjsgDXUCEl89yDDNQOg/MVUKvp5FnVF5Kk3RAFihrmZl0tIam5/g=,iv:6rC8Kp1GkrR5zu/UDl421wibrO+N8nBcGf6tXyHiwq4=,tag:zPN6iySm8I1WclYOtI7JVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
