apiVersion: v1
kind: Secret
metadata:
  name: unpoller-unifi-credentials
  namespace: monitoring
type: Opaque
stringData:
  controller-url: ENC[AES256_GCM,data:50z460jg02dAg+OSFvMOtdAwekk=,iv:FN6Y3SwG9nPiUC8GiAIYFgpLGmGJk+ogiTHMIHdPZQA=,tag:twWe0w6aUsosSqu531q+0w==,type:str]
  username: ENC[AES256_GCM,data:Z/4xKHv4mQ==,iv:IVKEMl8JVZdl7BA39puHUvTHblI35ej8sJce2rBOLf4=,tag:x5rkcmo21CtQO5d3JCiFbA==,type:str]
  password: ENC[AES256_GCM,data:wa94HejxopBHjtq0pSw=,iv:euR0a8ZtZv68S5BQNyswjSNw6Ah5Pb0M9zHyGVe7X7U=,tag:aa5QszEIpig0oRnq5VggBA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOW9iSW1MTkhlY2QxYVNB
        bE9RaHFVWi9pcGIvR1ZZSGUxQk5EWWlJWENrCnVGemw2ajNQZDdRTUd2cEFvakhP
        TWh5S1c5V0RYYmxlZzBFdnpodzRpZG8KLS0tIEdINk1KTUVLUlErWCtlUDY1WHNr
        OUtxeFhWL2o0WGJ5ZEc5UnpBUVJuT1kKraWlBToAi9abPber1W0xN1KtGEPXnomW
        6bor+b+BH4S0hPCfr7IXPIUmOwHcKWpxnw+bSil2chUPCkPdsElohg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T20:18:52Z"
  mac: ENC[AES256_GCM,data:DoqTTKN7pniWhBypdGRCzx7usklRO83ZMuLmowwqAIUdKO0Oo+wBTmwDKO8nI5eZ8ufgdSascsbiex797LtGSTMUZAyyZ7fLmzayV6NuS0SVNaZoSiQXsaNjMx+Vt9wn7mcpOIVwpYNv2YrE+vVWt2m6zb7JndHiSHgr93XotwE=,iv:rkjLCs+wUlrT8QJWHUzZJDL9dUxMn7EYcslpLEqnn7Q=,tag:CRmLcbO8LJDuh0F90j8WYw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
