apiVersion: v1
kind: Secret
metadata:
  name: unpoller-unifi-credentials
  namespace: monitoring
type: Opaque
stringData:
  controller-url: ENC[AES256_GCM,data:4XxvSyPUP0RkPITiv1u0fezYEWLiyZVMGw==,iv:rZn46kyUbF164l70oBb61xXIX7kT478ZB8WWAiW052I=,tag:LUrsgB7SnWsQtWHhKhOsGA==,type:str]
  username: ENC[AES256_GCM,data:u/rnndlKbA==,iv:WtkYLa9lMkvAKi3ykHq1u0TVaDvPrtGIX1ol16v7UAc=,tag:mRIQpD8FIpVxyPiynqwjiw==,type:str]
  password: ENC[AES256_GCM,data:ziH/cUVS/FjjwVRN5VA=,iv:R/q7ETHfAV5BK6VLZN2gGx/1Wq1eAZ2a92Ok8vf5MA0=,tag:1DIirL++66LQY1Ku7MGphw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGT2w1dkNCOEhlcHZyblNG
        QUUzQ2EwclZiMUhpaWJNTXR6b2hudGZOeEg0ClVRQWhrN243SStJTzVQWW9Ea2dH
        WHdrekQrd0FHUDdmZkhJQWREeUNGU1EKLS0tIFpLRWFpbEw4TzBEaHZ6MFRTZjB5
        SXdQS1ByOHlOUkV6V2I1dDdqQzd6NFkKPAPiJJeFPD4RQLFDSgXHIoHFbSnZ6lkd
        182bMRJVqhgTL4R+Zykmje2sFVx3CLQmIX6tKLzvGAA1spTUOygVxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T20:09:28Z"
  mac: ENC[AES256_GCM,data:o3DZ44n1UxVY23LDf0PnzZ4Vtkh3FcjUNkmNFRKnVQ71/Rg12UQawAlg6UEmcIBFOCF/8B0m/Y+1StzKDl31Kv/Z9pmCxPNPV+rmiEkTrGxq+CVNEA0ezMU2uCkq0SABhvHOYeFXWSnvn8BMBuZUkIXBMzjU+ShyJoJEPSwEYfY=,iv:wQZpzFEH6TZ48LlKdkGfHbnCsmPppR2977iavTGqEi0=,tag:IE4k9F3lPSBhdJFKgD+6yw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
