apiVersion: v1
kind: Secret
metadata:
  name: unpoller-credentials
  namespace: monitoring
stringData:
  upConfig: ENC[AES256_GCM,data:S5GSpW+JdHeMEZXgBy4vu0C6yWbwZmbOJc7Keky2+6l5XenWtS1nMywzMkQECOMXrrHz45gUlDoa1fhqarhkW0pvqj0H4zHRwDhGdwuS7i1ZyryJDR48WOtV7mxx0bKxz5ZHPfth0uKRd2ygNhvPPnZjgR7W8RTgeu3CX+5/8RvOoq/s1tdMptN2saeumw0YytHmaUyqfazP07v+ll3QuBxseEHDqifJN/DI1A3EUuSfkqBGxSS56nMeXwx9XoaTzxCp7H6YIR/IUlJdHEOdcIlp4Ezhh5qWXlpMYx+jtsCuq2NFGkTebyLb4AIwHyUXuvKHwZizsKkKlpwzaAfWqwfhuyNBfLJMGvFpV4N7lnjd7bdsqioGkAhp0mDXP3XtfUBs4JCuNqtwR0iF6VUk/n6VqM01XT4fq0Km/jwA79yfM3PqSBDbGXx9b1zOY2U8DMNJPADfxo5kF8KigqkoTl9TC0sN5eWTI0tsS2lR/b3mbGzLPOsQJU1I+ZpKdnduCb5ZBLrLI8DD5OKrDUwFaSFWn5f7RA5SE1FcmIFqbdGaQKesG89qk8dKxa/HLRAg7hXsGQsR5W1VJJWEjiuYgo0CP4HnqEviu2y24gkPLohWorxDqzts4/sAU1rebFfjumcfCGUqTSpgZlXqJwM4j8llz1KRXv0Mxe2vdI1VrnputfpY05GIJY7B8k2t8GfpzFu0cp9gxqPVAmijDMFOyrFIP5aIbwEhfk8BzyNqEs33Uk5/NqTHONePsLdjPKZmfryj6Tx6JXk0YDRz5HS1uca93xHrACRV1Y9jRyMhCRSLtBIbsrjX7IG0Wd/UxvH4NNyzyc4PPfrm8qugFA+eVzg=,iv:61Awqtn0b3AqOSxfHB4v6ul6MuyoJr7SDXxGKofAGc8=,tag:L4ER9wfVmYEvLc5pDK+idw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOFk1WitZcDlPMmlzTGFr
        a2J5OHc1eVAyR1M2bEhOK1gycUpreitmbUZJClplRmR5NGRQQVltc2tUNmtVdjF1
        akZWWG5TMXdXd3pDODRHcm16SmRWWUkKLS0tIGVJYys4RUVoVzJ3a3NjWGE0ZGsr
        emJRS2Q5akpWb0plbVZleXk2WmtSVWMKcU0XvaAS6wQ1tzhwUEO2RNhXo7jHgX45
        QAfsX/b/DzGmrOgT2tjL0iyybU7e+tZt+raxuVx+Pd5gHQN48xDkVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T22:19:44Z"
  mac: ENC[AES256_GCM,data:T8tMWNPqTnfw9ybYa1oZWPZCxEfuP7Xw62EJWHgo0bt/0aZO7UeF2KG4nIKAG6E+euXgNCI8WY5bWjSXYQiPuEFCPC9dutbsRmSFhv+8X5aonAeQxpCPeS4a7sj08wMGbDqs3wp3eyaRgMBCUxzDsv/46B317WM6VGN3s5V941E=,iv:hUZgliQuZsDmgoERYlcrlNbkyDFgakI9EZKcN4Qlc4g=,tag:H7GHsHvlcfl4Az7LIaWdPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
