---
apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/instance: unpoller
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9130
      targetPort: 9130
      protocol: TCP
  selector:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/instance: unpoller
