apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:gWZOVsVw2uPjqniHCteLvpY=,iv:5yUNwHnxRIkw31uFUOgW6CFofm4pJHbvqH85SwLrGjg=,tag:OrqTu0sFfMt2S83dtQbkwA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:Aa8WtuxpSEbvl47K+NXQdVDK3u/RPo64rQ==,iv:OqF3qAmdj2/T/VmK+6EiEFHd8i84bvmdnKwGOgrjKco=,tag:GvLc5wuqowxTpTdiuQ8BoA==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:hiemAg==,iv:kT9Yf2kVv89XhRHe1ZHissIzky5VJxS2AE4dac77OtI=,tag:L0EitqXvMq9P20WSvY/1XQ==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:+SdvrJg=,iv:WfSJBVVISn1MPzENmjfo6jZtPlR8pcqYEWwAoJsEtak=,tag:NrjrW5XApZshed+XZWK8bQ==,type:str]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:siJuFYUuFxlr,iv:Rz+5WWSWgTpoMRSHTJlm1QZfKrNq0UDyXACHMTQqIRY=,tag:Bbbp5+mbj1rIeoROjN/Olg==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:Pmj61rm9MEwNGPnkQNRZnZw97pxdJBS7tGO7i1TswlrBW3TnBvBJRQ==,iv:Avo0iu61mxgVXEX5+mmilTZGJTodYnQgF8NDSD15K60=,tag:BLc5lfVJZltv418TgXKlMA==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fdFoxQkZYHRJ/yoHIRXfFDG0jw==,iv:1xs5cJd7K5JVq/NTxueqSKKh4awAfN/usvYzm3oA5TA=,tag:SaZqSOikW0c6vKnKDd+2Fg==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:FiZPOc/KW1p4W1D2icnBcMf7f/1Ufgk=,iv:9t2U26MU/Fr+qDavqakzcJ261qmIrdEeUE1J0+WzdLA=,tag:5mG9IrclBj6THdsvQr2w2A==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:Grh8bKnj4b0+nMyGr9t1ynDjFtHRueA+bLpXknsJSSKGEpPraYgFFqvgYhxdgQ==,iv:DMFp4j7YoMHqizZhTq0sCG0rTNPRiDDWFP9FsD46lkM=,tag:GlwjBwZaWN44lkwr7shxFQ==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:SidaZVPvUeS5xm1eWv5A0YHhwFLgStDR6VmG3yJT8Qjdj3o7d4a3FuXm,iv:AyaDVdvwmL5WX0klnld771lSqjkCwVuDRI2dK7Sm2/Y=,tag:Bjjl1SEBr2IDYpTbkHENKQ==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:v2r+MqrU+XCZC7oA6Bmi76L3YAXzWBNjlTI+JMrKjTMNaThWrA6FKk4hpdqx,iv:sWnGVsJFfqSqHUoPu6+ycSGn7UqKN/3sLCrdDG2DpwE=,tag:i0LeTWUadcqVr0HReB+AVA==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:nJ6gy5eBtsprm+1NCyTRr25hp4Q=,iv:ddVcV2jdyk9LHEW4c/RTY3/Nx0II0w7c/eakhDb2Vw8=,tag:R6430TOfxvTdUpXBqtwZjw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeDdzTjZONmp4VFVSNEN2
        dHExZUgvRDNyckhlWUxtQytjRjFteTlpcnlZClFxV3FaTkVlNmRBT0toYnVUQjBi
        V0I4SnA1bWUxTEpoTm4vNmw2M0ZGTGcKLS0tIHJnYnV0Z0krMDZyZ2R0UU1mcmdw
        eVpwUEJObG8zZXNmR29oUUJzUmFteEUKVpHD4NuNxoEr1Y8BLrb4J9YUzvyXcmm/
        Ta26qX+5Vxy4ruc6GClzpqouK0NbQ6CiMV+TiUw9tc6Sdq0qeI8DZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T10:35:35Z"
  mac: ENC[AES256_GCM,data:d5TnpymziDrOCeORfzh4duEvzGk3ce5UmSn2pp31bVRaSVO3F/rc4Uc4vMNrU98kpjCo0/prM3dfwu2jMj2SklMzksOmzBwGskm9OWOWo4q7uIQycOZyPekswKwqNM3mZvrweyHpW5ayH4k/2adb/eVSqzkFikGogf8FkP3GfxA=,iv:hdkJ/M2F3uCnBgVUkir7ulqDJ6Qif1efk63ZcwLqaLw=,tag:jSpU7+Y+E8ZZA9oRdwNUOw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
