apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:JxHX0qVrBw4wf5KLdw3n/u0=,iv:HnvQvYo9Hq8yMNrOBLtCrwh7q+4xlYvLBzQKa40uH6A=,tag:UIhHYbFAQjcUBt5QRnxAQg==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:cCf6es0BZzjOP/pzhGYKSf7Rpj2rD3zd/g==,iv:0V6+DY9tn6XKQw4/6IxLGq+BL5Ne578fn31iClVW6jI=,tag:aEQSKVF8U0bWANly3fiNlw==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:q0ekKw==,iv:b+AA8TKMvvcPa6hxwByHYoHAj+D/Vx4+WsupmMi+kfM=,tag:M6OtTo61GHNw2BNtlp/Y4Q==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:bUZ9UAU=,iv:vKgVkVmKkcupI7zQYc8LtwafqIRNun1JLLs5IA0HchY=,tag:OsY24skpoBXlIVDhEbZH8A==,type:str]
  #ENC[AES256_GCM,data:dJ3yi01d2J2n4TNejE4bpRFllspEGgAhB76mUYfhddZLveQFaoHb,iv:7w29l3K95a8HHym9nqD3amve6irAf40JHRCqi644QZU=,tag:vx/fgQhTzsriY2IHP6G08A==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:VG9mMhT1G/nX5A==,iv:QCj2ocaq9cEcApTAWd97tH552ae5is/9uYRv/IAYLuI=,tag:Dxv6yuK+cRR3ZDbumMU5jw==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:s8JMqaDQ0Go63WRIJQ7lNMWDDjIzVJaANa0fcXoRc52NavQGY+5fJbK/,iv:0XYcLHchGbrvnYPq4opmys7nPMTTUCzi69Yoo0tXZ+I=,tag:rLh63lP5RY1zUM65yM3a6A==,type:str]
  #ENC[AES256_GCM,data:BERtl4qsRNazjQxTWm7daOgKEX/qHNvvwBt2+S32ndQ5HbqvVpgRAqTk6X4eA7TE6bPculgVnUtj7xyg4sqNl6k=,iv:TtMUKnin278bPBnAJAvK/KXF9fieb+SyjMoMbtJsFNM=,tag:kU7hMdqaU1GtSOxbefcRzg==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:7yQOLgx88KbIDjZY+yd/In00mrVtQJWVZj0oAErv7aIA5szYnqxK5wlH,iv:zMfUsTd1AO5r75kwdRDvGxqIG8vb5SgUT/xD3tEZrbA=,tag:lhBO3ABcyPRvqER3qobvKw==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8MqHscGdQJ1LIam/CnFc+As3mBhmk/lPr1elveYjPMxxr5dCYLzq/JRMJYezXiD+qwptYkFrGg+CukqYwI2rZkDhP81s+EVK+fWTHrsbK24QutMw324GiBMIUo1cF0ru+uMwffjtM6ZuII9fIuzmrf/ELlWCqH2Q3cSgnDFXjHJKRg==,iv:wM7MIfb3r6Fze0xtHRN2FS6uVqy1k5n58qKWp+S4vlI=,tag:DnmSNKj+o3kArx7RSl00Wg==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:TTo4VCfC6CjkbS54rPJG/RyDTnh650UBVYzVvo7GBMVVD0FWn1CPfw4vorrzP5/2,iv:Y1oBosjxOobwFfLDDUTE0hu5OMkODKWjbhF5AybruwM=,tag:r2aYqaW3a98ygw2UfjpORg==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:d6COHHDNDgXcxY5qZG4chWCsJZLT2+3NmSY0enZhqpauViaLXpYL0LYjOA8=,iv:RjTgBvKe6Uo3N7wbKQOvKOzN/+5mOfqbjftIrz1shns=,tag:Zmw9Ws9q66xKVlB6RxuzIg==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:jXyIw9uYdn+YlxDCOlDjPXfPVdQcrmCp698XKLx32HmsldTGXDT3NjyGXTSE36Q=,iv:oz07xqoIFec9f9kG2kK4WUoOk5DP8e6NW5nGoWxtr3s=,tag:8+Tmr6Hhxo/8InRFTrNEvA==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:hMwlP0WYnCnf3Upu2Rfwg56UuHJsxw==,iv:OrQm03/hRMoUYvtNrHMPMfJLdH0att0AAKmKNdgesQc=,tag:oTZdCMo2OL7oxt0CnoTeRw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WWVnbUxUTittU2lCVjVY
        cEtkTkJJUUFKWWM0OHdWdHU1K2d5VFh3MUNZCkl1b0pGaVhoVW0rd1IvTVFkM0cy
        anpvTittaEErdmV5WitYR21nZDIvUnMKLS0tIHcwRjdjbG82S0xWa3dwQU9OM0xU
        aFZpVU5JWXVVdmJhcm1Fa0srbENzM00Kjl6Zls+uyCujEJLV2W9QWBiwKIgNnYtb
        NT2PITt1MDeFdfZAxaSkv8gRWpTkHG4guyMNKCXCgOVsztRpise0Gw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T12:10:11Z"
  mac: ENC[AES256_GCM,data:FSUswzaDtOLaqtqN4iQbwvDf11CUflC//0Q9Ftwi8WfqPwPgNKMfi4mTqZZX5uEqAecdSsVss49fQe0EGsajP5qMX4DIHkNsv7+0SPBPE9I1cVHq3UO7u/adNx8eaqJ+WOJ5SsxMiubYmvUiom3+AHHAHpM2T3CS2qXOUAoKQvo=,iv:+sx9ncyVXLQsRLL18iklRCpBxEh0vV7RbFx4CVU1j3I=,tag:kj1it1wCQjAJOcsXHU8TBQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
