apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:C43p3sH8Tux3KHUAl7CUPyY=,iv:N8qOLJsCTd0S0GugJWHzNVbf1ZLF0rZvfYbILoGOdgQ=,tag:4opQm1EUeOZQpgIwl2/U0w==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:Flw6TYVVCU0J9zZCImmP4eN+KvItJsgB2Q==,iv:2bzXkqe4MKsjzlcFOOt4fGjhMdTcdPpdcmxcMFuYcHk=,tag:5Mn+NGLhEwuQLZumFxhsuw==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:6KISvw==,iv:aFXIe4xDpqW1IdYfJxM05bYkCnza3f9QPBFC94NlshQ=,tag:ZF68Tx5TlbIY6ga5ouNgqA==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:8NB3igo=,iv:AFlwK9bEN8ND7MWFqx+KNfqhYOUvNLTknLpPU13FkaI=,tag:a5ybodJg0lqqM/rfvLcB/Q==,type:str]
  #ENC[AES256_GCM,data:NypP1U3stWkwMaQXCkGbze03QlOyEPeB4fXybaEfr/26/pC46rHl,iv:lIudq/RkE3cRpiw6kiVDsR5fvLCO9f3gAZwLwxBzpHo=,tag:i35ygP9eS/Uy9mIovc+dmg==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:w5bPyDSw2kMe,iv:HuHpVmMtXjXK1+MWK32bH+EPZCUT9aWiLy5RUMK/rFw=,tag:R1djCBdjJ62PmAA3iCo8DQ==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:wfinMRZ9KxY1iD9mdNEDtzF+lc35ueh2d3bL+sTomEpz5J/shm5hJA==,iv:C0jvDgSFKtzYBH1seeEb5cqL1W+wz429uiH40YqA9uE=,tag:6+LsDjK1VPd5cDo6ZsbTgw==,type:str]
  #ENC[AES256_GCM,data:vCeID+Rv4RKSZV8Cv09cXKZlh8VDldr3A7+uDWD6yyVoRDm7g0Tz/aeRDy6yl35LPrQitMUJKTa4yC+GUtkFmo8=,iv:2nLF8ybP2zIEZXx4OO94R2ItMmMioDX2uR6zFF0+UN4=,tag:0S7RBl2A6Fw4ukoI4apEzA==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:+uUidJtv/ikPp4Yji0ntnRnNo2z8dUIUbJtzWp7XCNWdQheevXSFew==,iv:mhtDlzcjcW/WT4FfLd0AYuMGh6l78/b+RMxbFNo4GNs=,tag:IZc4aR6+DXPgm3uddQuf8g==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:s5FNBJmydd1SClpS2tH/dpaNFX3MwAb297UcWJGb1nLE1/d8/wmvALDFh/SiT+omJ6ytWlaVs/i3ggAOnHNmq4pk7iF3mNPkNc9Ua51mDouZMayqephvw693127igvAuEdGL7t9k2xleLbTZpH2DNl9m3JZZmFZMJj7HvGWTx+s=,iv:U4Kek7seMyIhfmtWYkMpnFAud8+Mt/D67f64R0HJ9g4=,tag:UVSHl4jsT35ysgIxhOoVtA==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:BtKc3OBsFq9SHbV8bAK6OE8+xQ8OSpZFVQnHOJfSErds+M8GSRFVzl0ZidWFGQ==,iv:r1HNlPpRf9+c4HSNMQ32YIGJgDgrKAvAH1wGbGVl/hs=,tag:T1dpwoAbBF94IkRKuZFgrQ==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:zTwysGumZW6xs7vndb/OCY3wW8X4MVxftx2T4U5W2OGdiPTl+XjoU2Fq,iv:jGqOQu8r1g3TU42NSQvY+rCiGusIOE5tGSSR+DYjotc=,tag:HuNMvtqufLuN7FKLgfbrZw==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:MVJsSyJeaHUs2fU0BHVvVxrCmRrviWOi4e5B4tINcChYtrlnRuAmHe2tF1LO,iv:P+zXBQ04XKk71idCF6yCT0dAHbQqQfsLGbC8BVOFMMQ=,tag:1lmWVfcNGL3J91QrUn4zbg==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:a+MP1eYjGFVt04B08oXeX7Ojl6U=,iv:UzM7hZKqEnueH+8/qzNmmezNy/q4Vjus7Vq0Xc3Dk4E=,tag:Pekun0tkDzCWZ4+tms6MwQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOGZ6UUdKUEJ4b3g1dEx2
        TUpRY2Y4ajB3R2JjVmo5TXlnUlAvZ21ZQUgwCkFzaW9Fb3MwNHVIU05uV3dJLzZH
        RmZqR1lwWGtSUWVGbm9oak5NZXZ0bk0KLS0tIHlnUnFYV3NJNHAzOTZ2eDNQVFVE
        clg0UFpoY1g1cklkcmgwRGRjNUZ1b1UKW/NH7RGUQPP9aX7dhI9zXGg3RSpZtkWX
        KZc41bKjK9WzwzvQ6eEPam/PDH4XnTklypf9Bz8MnnNvpQsdwz+QGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T11:47:49Z"
  mac: ENC[AES256_GCM,data:0aXCGUMFjYQBiKzpc5t7xXtsfgOh3jhmlCsSrxRjBjG8j6g1oEpiPhu05ndcOVnSwfuD/pLQo/imOY7w/YOzTZrAOyQYqfLxI1ShfLg2vC6EQHXxdixU8kejPse+LntDwzv7y8TCzTiraiZMMqg38HHtVQ16+zRRJpq9S9p4qHI=,iv:AR9bLrwYAUvKKXaWIiHxaoVh8dlFVJo4GR8jel+pCk0=,tag:j1LN3DFsIGFr4zetyeRLVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
