apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:2jxS3L0xGAeOtX9unc7LQw0=,iv:EP5go9ePnmgr+fnRl+Rxd9zEZVqwyGe0sZRa+5O4L+Q=,tag:VMJ+mxNJL+XO7IOxKufrXA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:YC2k3vsllnKAN0nlHflK/w0lNfPDRH9IoA==,iv:suqGX5dFyfbB89FJNW5Uv6h+F41vJZnl12tOKfWb1r8=,tag:owforJJnDHI4MGDDyTbC8Q==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:+uCifQ==,iv:+LyIYGy66S7N/Yvfq3/luwKtarWuaFh3U+kSo5W9YCQ=,tag:yp7huhgeqjev4Tyt2Hw2Sg==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:CQQR9DQ=,iv:0pg87v5CjMtQEGxxyg8m97HJ1ISdrxqZuOM6r66Tdqs=,tag:eDFoMElPsg8QoAU/NpWiyw==,type:str]
  #ENC[AES256_GCM,data:AZx3hlWszEwlLgxlPSljta1KhNU82YT5cYpw5niY/zdwxIMzhUTa,iv:tq0UV3p0Yw3HbKlNbkwjtec+VcWWDbExDNaUy5aTUwk=,tag:TSjSNqr4cKxbtpelykDgvQ==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:vdA1QOmt5pl0,iv:EayoHxyEPP5aSgNx33bUBjcC6wzK94CX54cQgfkpZLI=,tag:2zSIICqosmhSO+b3/a/irg==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:qXrEZpGNfpBGTM0Bl4/VF7isZEt6YhcPTeXkkNWqm+WqRsaL4+vwEw==,iv:IYsr/+ZXqoUOpz5rdDTkCh+9D2/qmg2kYvZL4UTh8mI=,tag:k7SgW9zobMENN6dvLm4wAA==,type:str]
  #ENC[AES256_GCM,data:bbxvQM2u0uT94lS+8b4EAD4rgNRqKTCwls5Q7sR3NGWTXIOVbvqzzzqnxmcaFfmUVMwdV9vz/1lgV6CSJF6QKak=,iv:F4bmgEEoYAKw0PrvER2ONQv7fxYlS8gTeEmeWfaeFs0=,tag:x2jsrtaVk9subVOrEABrYA==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:yNlhy7RDfYQ81godnummsoN3BA==,iv:DhDPlCQTx1ptvathgf22p4rST0vpm43AN5k/r0CuLoY=,tag:xpdotWNrPrtYr40v+nv0XA==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:SNycQy0tR41H2nMpf31VpSn6CsGMdUY=,iv:UxvS/qfFyRTodsWkoTGTDRDlRVor0idRrmxw/y6ipK4=,tag:nJ1NIdNs073Xcf6teoNITw==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:nhsi9K3yffqLvjZJc3NZtjCR8q1Rq1ImWA2hXm9JRqkTBs5ewvoC3nX4yFCdwg==,iv:ut45uoeNFtFyP9eThfJ+XaY5TtjmIIg5qBV7BvDuq3o=,tag:CVIHDrHHRLdGIAC1Ul52GQ==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:w4T4i4RALXmsRF5uLfOgwbGeTkBEPRQVHsWUY33QD24edyggGhd+eoBg,iv:mFDPAaayNYAdQ5DICaHRR4aG+SQxim5d/uiLOmZdjb0=,tag:XUBv+Ni/YmZ+kxRGK9p3Pw==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:MrG6UOzwQFnmq4RfTII48aDPYRuGNEHxH6oSt7pShmm7kmGjVwOG8Mrea7eq,iv:6/HFDbhBkEPNN3u1EVr4LuMoHuJkHHNIhd73nCWTgl8=,tag:uN/eJRQO1PBSbJngpgbylQ==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:wKKyEfDMoW1kjBafGv1n0TxE0wk=,iv:TF8Cf9XrBVb+zQ5mZObQ1HobhFAkNnk+g+wtZxN6A2E=,tag:BndRZuCI9UloO8n9xlyo6g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEazdHdWduTjg0eTFRNCsy
        V3hocmkrZVJqZGhNb0I2UTJqbnpETGNQbnhnClVRVHBQVzhWa3hQUGlmbEtFdlM2
        aUV2aDI1bldLSk5ySi9LL1JBU05HTjgKLS0tIEpxalBLa2FRMTBnNmtSdVdUYTA5
        eGhmQ1JXa3ZRM1ZzeUc3Sitxdm9wQXcKZs54utmXs0VGQIzR0gCnAMVf1o5+CL+G
        J+bIraAzZFestaoSEa/UNHmBUCfk6VcYOGgFrBp2ammxU+6z3oogtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T10:24:48Z"
  mac: ENC[AES256_GCM,data:QnNoxWcaN0GhCrivRI0DaL2JVwIOj+t2SBOIvC7xxlMYvKhJRdyz5sLoKn2cff4BB/0DgXXeiRhi3Io75wnYgJBnWig/+IdHXOjTiGRpgKZzvjjpBz3rLh9jfXdPKRJyFx+FAIuJ/0BibkR9RyBS3r88EoAFLRQZ75hUuDVPop0=,iv:O56fUz+OVdb363NOxdO+I7ueSGer3jz6JgR8RBkrXfQ=,tag:Bmv9XGFcAWXwXy0FwY2Vjw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
