apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: admin@example.com
  PGADMIN_DEFAULT_PASSWORD: 0v0zon0PrpoHZt5yDdz5LXvJu
  PGADMIN_CONFIG_SERVER_MODE: "True"
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "True"
  PGADMIN_CONFIG_MASTER_PASSWORD: 0v0zon0PrpoHZt5yDdz5LXvJu
