apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:ibXQKyTPkUtHvd0jTVygt78=,iv:X/CMkPu7oPhkvIRwS6VqIQ+HjWfjyxPIqksgKYi8W5o=,tag:cNRzXhClyysOHuUyGEsOyw==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:IiI8l56jaB0hlyyks5q8hKhfbSLbZxoHpw==,iv:yUJT4luPV/g1JPhtMgwmd6lL+wySl5i5guGetOjjaDE=,tag:u0KZ2uMoxjGm+6XXPDt+WQ==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:wOPtkA==,iv:+aJA+arHKpKCYhHS02ZU+lVRaUJJGrteo1sbU0JZQ6U=,tag:gvB0hhexiRwea45UN1jz6w==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:RrP8e4k=,iv:dE3XNhPb2deUNMJPRnunzmf3BOG+Dxs4BowLw9kEVxQ=,tag:JKX4RXFaDPB9pNcse/Om0w==,type:str]
  #ENC[AES256_GCM,data:3Yjqqh8JzMlraunq965k6fL0VzGvpZ5QQH9+a/cdSPzE3cWJ6W07,iv:4ppQVtWoXDeu2suUHI5qRaKGkmv//sh1Zh/HL4JCRDw=,tag:pgal+CPXh+6EU6VTLedGIg==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:xIuYyIOroScWIA==,iv:+UsLDCU45DkR5Q560/uCjwHwP6O5yX+VkLjokmacAEw=,tag:3kjNtSw9sH2ixkLbH4bJQA==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:Vl6Zk2vhE4vojuGw7Frl7tA6H18nP6zNlyCho4g1YgIZ3/P8MvAKAtbT,iv:NI8KT7egs0itmIz4xhnzWQvjk1XfoiKGzrQGe1t8fJw=,tag:rVKsXwFZ+0cqDBS5EZqEJA==,type:str]
  #ENC[AES256_GCM,data:rHINyWvWtJh6/jOUjlVbih5PvNCd8LndB5zLdAF4v2ooxhamEwaeGcJteI77Q+hxEJIapmoKEsuvLbOQWf28g8A=,iv:lesF5jsY8toVdqTMXc6uePyDwB7LB/zWatFJMzdDv0U=,tag:zaYrwIiEgUHGqBNBj+4MBQ==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:l68xQVr6jQ01Yj0SOg4ztgbb4neBGd4V530bSsCOGj1Sby+Nt8kPzh77,iv:enn/ngVfEoB07zegLXQLG0JtfaF9JyIWX2+3HXdTCgA=,tag:8ptL5+xTEvGi7hlWdWLxuA==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ny/0+xgjj3op8+gahKqUZtAz/fzQRQey++Li0xnNldBsL+qUoDs+d3WaMppfGxiiadRpwXhDR0q0pOMLHpSHLNCzCjSWAAde93EP1jNYs4J6dyHgS06aErGTvmqDcGfx0Y2OEHTkSeXIdHKRkABCQltO08yGqOKDdSbpxXt/ULUyEQ==,iv:4Rjq45nbXtOe0HIXjbpLxdXL7MGQHT/BKwyqrXQfydw=,tag:ur+JKUs44iJjH9FeMhdyyg==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:B1fBVEWwrAko26ALrTpYtlAQ6EuNzdLFNowMBaIbJ3WJMYkFMiZBb/EGC+8SNPQl,iv:lLun1P9xRHEq91nsSv/C10kn2q6ns+bZI9MMoQqZDHE=,tag:CwEzq7VO7Dn4HfSgMhcpjQ==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:0RFNoP1dA2CmbqMTL/z6CZuG1eGlXMa3mqKjETzb/cW6pKXDUkK8XtAX58Q=,iv:CM+cOByXwHxiJSqF+4npWogaF5bJqoIKFC6zPC0Byso=,tag:p9unsDJ3N7pfTd/tLjvWHQ==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:3fNJDRyuTxrOW0btWqbEAHgu4byvgHLx34+HALmNI74l9qlQOL2Pjl1++DuZ/E8=,iv:JFjQke2w95kb24EI3NKaSpMkjIugswpmVoyIcfAz9ek=,tag:njTbV4URqWUd3Nz67UYLvg==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:OnN8Axs0Naoz64o8nA+G6nJbnAxRrw==,iv:VHjpwxXjF/LAnHD/GqS3XfoblQ1twtSQN92otuXtinw=,tag:dVS6LNevPsRUiBitHzAwlw==,type:str]
  PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:sU6XVdqTq4Y+EnSRdpnm/J46xcbX8fCe7cDkLZZQr21rlR5Pj3+abxA9sjZjuXW8rLqtxd6PmUDuvxnaZHhHsfnVDorserhe7YBL5nJdtnqv9DzqyGl/yRAR3Lq7Kv3QgWzJftXOTQQeOLYAYzPVDXy/ZEnvV84PklIK7gjq+dzzID6iiXTks0MNgBTCmt+yzx3fILjI2H855feoq1yqLnXl2JEM3rfDF1x05Vr3oyedEVV3eMsQGFUPJEgmhIGnVyE58D26LwHe/+NTvzxzUJxByx09V4V8lTwaYehOp+glDmKpEbs5OEeolcZS0ZjRVbM9Hi9pAoW+qEIkITbNVXpszhuoB2X0et4Y81CQgzG2pq4wTZxGcnDun11bflOijbY6irKBdVubqxI6z6SXXmB4MgX6BnWehDJ8Iw/W7O0SnSW7pZzamYWO8EqtTTwNFZRhE6CJ81xzNEzWGILjdbNhO6T+IKnW7TZVsOgG6zYPPgwBujYRcQx4KNB4tCUdJuPFuN+ZiIjc6bg1RnpK6yGg4I6kJxwDoNHL0wHUaB3UyNO35g3JauNBgos3Yt/0IYzQmCiNRVU59jYtZLckqXQFqC0/jfcwjipe287y7cDsNWF3ekraqyJR6hIcalvTqW689AoYgQEUFmXatuvevWi2/fq4KX6/AYeC1TWrdeEJmqkrMH5oa6QNiyzUZmGLU+SSGhpu0tzOypFDCaF5a/kXlqxIC2hOfvzdFe9Smy5z5XJ+PldBqrc6wH4XJkw2/g/tpubgq/Me+jHVzeLfNT7RVkb3pyHIXK6X9HfcbL5gb6ou4LQvNiuBSqhmqxXOb9otAUx8LPEWSlS2EYaOkXyjqAUgpndbv3GK5QAmzpY42BxIZNOqRwsb2qoT3IJvUfdG9MUf0Yxvq7djbAxKR9F7XSKqPGftKxRFNjZ0GdJ2w0Ccf3wz1fhcUpKGmL0i2IvVL7g4YsQYQNVEBhdpiPYRZ+kR1fP86dgCkqsN1djGtnBQDO9K2PepDVxlvuo0rxEX1oy2apztEz7bqU2cxH/pJWME1Z9GseMEWw68ZizWjMPpC2q6bWDb2QmvEUYo5hV6ZnLGFOuXKdFvzdw=,iv:Scud0tbQtCc9Gs2kejdAIPwK10Bp6Hi+O/YlRTvFp5Q=,tag:kw90Fd4xhEZFhvNIzxWVGQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQmtXdmpRaU9Fd1c0Rmht
        VDErTDJtdDRmeVdMYngwRmZsYzI0NkdtZENJCnRObDVFNzlaS2dZdzFCV25kWEoy
        WkQreWtvcjRwUEZmSjBkVWRWQnBHQ00KLS0tIHcybkp0RnhGUkc4ZXNjY25LdVdF
        b0ZuWFk2YmRybFdZZUgxRkZLZElLbDAKcfvp0DvdjDl5LXpHQedhvqqD5L9Evkts
        t8S40H8EzBZcbNR0sQM9X3FiX1rvldqo5nWUPW5wBlULLQi+r/8EYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T12:31:23Z"
  mac: ENC[AES256_GCM,data:fWqD6I6M2Vs2cnA0YlvoYkSvpyvIk/K5Xi5yzwlAImn1D7jhz+bXMppmSqaBk3SbbrboPodQkQRv+WfELQ/4ASin1wnP1/jghUqVPB1jDir/Jb+MusxhxSYAaBDvyRdXr+GuZsPidhIBEh8FZR1bn8Py0t95gcQPWYyxWutcMIc=,iv:pGWAg06zR5gB8IsC0/q4CtlPfYAcP/UmhW5Va2jd1wg=,tag:IuKjTl+gjy/R6PYhWZq0xQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
