apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:7eFhXrwhsTDq82P7nUMTHvU=,iv:8Tfyu39DsFHbiKYxH+ZpYwyepV1LAWdahPTPiHladf0=,tag:BW2La9BljqCwtKPySB5nIQ==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:Mugak3JFls8JKdgE6UnvAj2M3QAmUD+JFA==,iv:kU601cchLK8Wj6/JxSSvtdNGf/DYpXHemdk2Pmu828w=,tag:06NNoPPbrVVfFVypxTC4qA==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:18PFTw==,iv:L1ccMIYCFlJEF9vdrINMKAT/hhYa+xmSeRe8pm+CXaU=,tag:OtcYUidn9iSrcd17BzfsUg==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:1t5aqw==,iv:KawwK6ZfpPjnvDy6YzlphZyP1vlIcYrxXPBdo8D4NBo=,tag:2Qf80/cKaU/VjzUbeyAgTg==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD: ENC[AES256_GCM,data:XwOxXuhjx7zVkbvqhJrjQRvHFQGH5QSIFg==,iv:tcYPY/z0v7POrDFJt7LzCH/qDK2zbKomYRAPiYUqejc=,tag:RNKpF7jf+pF2U7TyIeqZEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RGluRE5rRVV5NnMrUUxo
        N1AyTjRwWU82V1kwS2syUHlGZEZSeW9WbzBVClNqN2JpR2V5bllnd2dsWUhxK1NL
        NmZPcytUNnd3MGd6cTAwTmUzREZWeGMKLS0tIFFWMS9Ub2lTOWZiOXRkSmhwKzFX
        cGYrYTZFbFlRMlBTSWVmdFFLTlVzaFEKbc8TIR0uPRpjx4gZb3EJnYVQAI2QGHf6
        0ucPXqyAfZrqKEYEgHRtftswnLD6bs4637FQnwF+2/RFZPgekMivDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T08:57:13Z"
  mac: ENC[AES256_GCM,data:VZ4aGn1X3UMBBk9a2FGG+8nuyXlLODPm1oSYycyLLB0Yxo90oy5yyx5w1QLJyiWUMuivM1w7+Ag32Dm39VoFooEV4VD5ENkPqRXad825n9Uy1BUqIqN0KMMk8YBC/FKWbliOmr/WPWTD50iOHttEWGjiZv3TBs3bnyXHOD1TUr8=,iv:ClA3K/G5Y/pM61sGUPGVb8J90cA3kQnhYd9CII8vptY=,tag:REOxNTtn8Ct0ohHbvQj2qQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
