apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:9ZzTEyWKwmTJTvmNLeimPio=,iv:JU1YI8ZrWbVnyzDMTOPFN9Av4TCrU0x+e411ctksz3A=,tag:j12jPxzMhdEGCRWd708o2Q==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:v4yQLGo+muO6MsOGF246sYeJZl2+gQwMzA==,iv:SK5DvvBLK7BH/TqSjjmtwsX6ftbELr41/ctGfa0w9LU=,tag:UnfA7xdH4jfdh1QIO9+f8g==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:sOvRtQ==,iv:3SxBNkmiyl4uF9MBNyY9el4vuJe1vM80kjDjdzB7W6Q=,tag:mLwIDafhkta5NnCTlaTKpQ==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:mkT1rQ==,iv:NVQQlNhhoq/sgNYRFs9t3ISB5CyBMBeLUDllOf84cy4=,tag:s2XUIPpGyuqyKPi66ZH5WA==,type:str]
  #ENC[AES256_GCM,data:5xU4IoZTr/WIhm5H8lyBo7Rm+bIWJh8R5uFsv3F3aG1DWO2yaZiR,iv:fz/LYhlPlslj68vRtUew1l2lFEK7XoALoGgQXWlL/j0=,tag:KNmcj362PMWNYTl/tJRijw==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:M/2CsiLPNpQIqg==,iv:of45hJwt4EwxykFf2hNvh97s9or3BYSNxAI/wmQ9M/4=,tag:D8pEmJn05FCug0jFbFck1g==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:CRlh0WRpcuwvdDaHljPXkPhS10rz5/TWIRbyNaADTFXB4BYR6JBonEY4,iv:lPbs4eYnYgPPJdaEGPipvp/1LuHhGCUbfwvDBM70mMU=,tag:IUWyAdjYGbAVB4PN9icheg==,type:str]
  #ENC[AES256_GCM,data:ZmhO4MmEZLvCHeb96OTFceva/+N0X1za2pr2ocvo68qSNGRoorFWXmNph687Kh7ehyrI6m43fZNJuRYNuRkVtig=,iv:8A3Xbn39zTOiR2se/JwxzpF68a3XwRi8SB52++OPBiw=,tag:swOxBSlfB7RJrakQOAwF4A==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:6jwYC6eojD1oXf8k1/7R2AGkaecZWPWx1tU4K/nuvtrT8n8N0nnWMZDy,iv:X9tN7Z/qisFrLBCKOWS845Q7zvNRwNa8429XUsjFX9E=,tag:SsEIFthUL+ArKyy5egvyBw==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:998K6DaZfze4s/PDIZAqMi+ljZh+0pKB3EMz8gVkrEmSVqfmmWU5DT1Faj42YpqLh4c3LUki5FYhAW6JLhfCsJbgfriZv4bCo3AeTyh1ut6iPyVXRJnqG/2FbHUQQ7mskNrRCA3AbGTbIeNxywAG7hwAyZRiOMoLHixxrmWVh3Sdnw==,iv:aM41f+/+ROgdWinnZ/i+6E2rhySyG/ZtTZhh7Meaq9o=,tag:vyXo2Tb3SRGJmHhJLYsoAw==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:kko6Aq1wTGeI7pFrWtxLv408jKLybsymm1OfCeFE5CtVqqWMFjBo1YmZFXiYYw/4,iv:ibvimZWPeZ+MHBIKPyBQ97ZijNCBeDLcRLiM37USo1E=,tag:5tskZKb7NppSwkP0zPgnQA==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:ISLZKpcdYtg+hbVstANhFe19cYvFJitqAJeyfQRZIkBm7pSSAmpodLcJDG8=,iv:sn57pS9cFKgAIwI5Qj7cTz/r6PE9pYAO00Ao9mXJvOc=,tag:4X7PLpbYAF4+bHFYwB3QjA==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:1+ajHxlhpK15sNbpP9RXaejL76orJtFgJJH91fhswD3exlIxSE4X9qDguvXZytg=,iv:VPfPMXaeU8kACMTC0zWX/NjmwCMeYpFQQ4rRSKH6Jxw=,tag:AYIHHl6rgvDPiipdn/SrgQ==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:Lv823Ejz4p9tOwmBAG1tcbeDXGaYUA==,iv:n0n5Cxazvxh2ipMzdBTOFAh1IdbJA7RPtLMahc3sK0A=,tag:6BSHeqV0l9N24Pn46XYaIw==,type:str]
  PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:z9lqwi6dafHMwu21BITIzmDsSDvknxC+cKO0v3RUE2uvtpkObuuqha64m8KiMlNu6R6s+GxZ92JnHf1qZewHcg8rF/li/cB4mFXIdyX2CU27kwlL32F98VSyonJ/VKlcTNs3+U+89kgDituRGkMm8qRiDqmw6td9SGTdHG2Xvqij5pO8uCggzy2EZN8Mlxo9Ut9O52iIzmQJjOBjD5eTeAnTWO7dHMONluyffcVCd2YOXPiyvgFTxP1ZpHG3wC0EzbZL7juY6zLAuwHJDL8EEtjRbfcuk4b1TtdSqbO6SW744wCIETP+U5yaFojC1JGsZtH8ILsQVgDM0HnqfPgFoj9aMXHoQH40GS/qSzS71eZzQI1IWCe1lVnieyd7olcHgdOKgmdDEhcptagBzjzH4MhIsTW1S10PGaoNaagNQmsDnO/x5L6FRlPKxWlAKWQmxHSq3RUQxWZu91sMp5Zfd05+cqigzRgqGNir+hJcKMalS2DXpZJTxMRp2Ur+pVjlC2UZeZnNiwOb3M/bvJnkBe27kLRNkA0PO3gst4Gpng6g4SpJ6ZH5KKw9qqgwaCOQZcYZmLIwB9gTTlDZcAnG2/vi3+35bstc5XuQgnqiFP62snMnR8/8FOxIzkCK+fURMSY02f0AqWHvKRBM03LOtfZBVDtV7C5KRsInoe4Fc1809UQ/E5lPsmu+jnaV/1RDqcVYw4t+5pv0jHoY2Mi82fnsgv7Ba2eodlRmaumC1/O2E2Lbedwqt35dGsdEPVuUArHbEIIKlMAv62ZqLwSjC/YZ9f933tKJ9QbB+E0av1WvalmtK2/8tvBFrBwKmDaPRVI0d8604omChYcAqF4g9X3MWutAXH9CFO3ybNMdoFtBDNIRxj3qy2jIeNiqFBCuwTG3DbaD5Gn2DD1kBiHiN9ipFESp7f6UZC/1NVm9Cd00AW/9B/obQ3lISOvHq8k0D4XAsnt1/XfrWYinrPgABQahawY9iRoo/cOFFSLAdKeCUMgMfXwB/RFrTbg2zFNCfnKSgLHNL/MyNKBki3c9RkHcgTQsS4gRZW1qF7CbJl301ot30kjIQhyfZhpedxRaEtrUT3BVnxDVRNy5EdI=,iv:+e72caDUOx3R8FQmykb1Ibontphq6k4pGarSmbJlF4E=,tag:a6TdLUr7yal4Np1SZZIGTw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja25EeGs5eE1Jbkk5S0VZ
        SXl3NmdXOWxBcTRkMUc5TUZvZUFWS2NJVlJBClNWVnlPaUFKTG1WTzd6b0VGVkVW
        dnduWUx6ejRDK3lVWGFCMjZ0QXFYTEEKLS0tIDB5dWFuK3BWdXNrNHpOd1A5bjFp
        dXdKRUxTK3VOSFlsRVU4RnNWL2wzY1EKyNZyesbrHX81qpM5I9j2PTfH5xkp5zeP
        voG0vb+IDD1BtbN3xlxox//aaYmomKKvaCbYF0fgogAnZg8ADxxHrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T09:39:06Z"
  mac: ENC[AES256_GCM,data:taxMVHYxrz8RT2IDVzpm6apUqgawpB7SXZa6aDRBGf5+eX2znisfo2QboK3MUU4uSkHR472XNZDY3Wysdko+MnDpZZf82NnUMwdtdrhRYWGL5BpMa627oaWx37FDeayt0XPjXJYQgIsVFBkAmrrSaM+0Htuqv9sPwzi0kxQf2J0=,iv:3CZlXHI+jaJ3aiF/cYuXx9CvXItRvxHhkAqHib2O6gk=,tag:noU7MEejlBpJkCeiEDiEkg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
