apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:3gwCeGZlOz4xyN0PfZaQ6xs=,iv:IU50wAzW0xA0Y4JDW9W+A+KJjUCVeh0m/7SwXZ+R7ac=,tag:X3DSYlnH+Awra6UTCWYq/Q==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:O3wv/eA2yRTf7vRvcmXhcgM+edYNqhshJw==,iv:nCZ6oVRRQ86A3GsIX1BTe+HyKnqTICFRUYY4mSR09TM=,tag:lsuftNT1uM40IzuWeoC7Ow==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:JOimEA==,iv:x4WlDu+XDOhlEUBkY2U3yHUEXN5e8S98eMrdViirIHI=,tag:VfFNazaXmVojB8YjJ330jA==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:FJy/edA=,iv:N8ns1bCz6Uo0CO0sHkWgvgIOirOjX2AcG9rbiH/fv4I=,tag:Zmf5eKJdTjZS+bcRNn2pjQ==,type:str]
  #ENC[AES256_GCM,data:sMXXIsxjy2YEoWoV3XlDMz0OLbQNfZuIq3B65yYZvTfV2fo+cuGC,iv:0okJ+GBe+DFIYNTw9vAjHqEqvm7Wu0PoZbrSjwClHXE=,tag:Rq1jutS6r4nN4UDc6OvOLg==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:bMlz79XbT2j+6w==,iv:oyIugYyw2YwSO8NlGvW3H562Bk/NAvsRY+uSu1RMJy8=,tag:0Ly6+UxSXGpWWkHZBK1qwg==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:Abxnw7acpFcjCFhOyu2Tu89+qdjMgSSq9RwP05OAV5IPtp3p8LdMvTyK,iv:a8YD+OApgpOnQrKWGk8O2CgHpS82OT8IvMPZPWxyVP8=,tag:4r1fAWh4NzhMt1c64RFQQA==,type:str]
  #ENC[AES256_GCM,data:iVzsz+3emIA16lrM6wIEmq4tyls8n7zSRP7Ue2FZhNYDAVjKfu1kmt0S7VOhVeWNlxY7adebwHqE/RSpvh3wb7A=,iv:dBMdpF7SL8NnGEJ75M/pnskTgLmb9ekPvtyYlNIWawA=,tag:8XYSJKcckJuX2MnezF/NGw==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:XKedDWijfVPhuwLoGKPu8pq/jB08+993kMaZZrKY9uojUvmNpg2UD4ZY,iv:cbMJ0xCFz50956ftyeQwO2v9vXFQQ2EL5AcGWHox3QQ=,tag:KyCAoiKPuJ8/Ad3AO5dxbg==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:PCS0GHZP8UY8lmnshFfhwKOC7DRNjjVYzMxY7H19EWhrNHIMBhtE+yD00vSrVKDKcRrMGHaftqVfjMOJN+f8gZYDKcqccuTBQ7P42vXSij9B2vBOO0kiVo0pM6dxRhgtcORbJ1pm1o2aREs+tDMRqKsH71aM3OuKxbU7mfBFkfLKVg==,iv:mVOONxoo+KLZzgPV7DVARdvPXFRZqiEznq6ryTx+ixk=,tag:z3eCYD7tYwWyXtQLD25TCQ==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:g0bR8ciSJEd5zI18LrBnMJNf5NzY13L86Gge6gIKpH40HqxNu33o3ThqiiwBVEZ8,iv:BmftAQDEcGqcYEigN+HGzdbISlz2yEDfscbEDesVvTA=,tag:udgi5SO9F6kgBmeZ1NR4mw==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:9XAG6uT2dQ6bPTMu5M4I4VFCsXrZpZ4U7JkbGtL4mnfCTppKUBmy7hCaFhY=,iv:5TVPFu0aCWiD8LnWgvp/WyW4rwnbXUw/wIPQIuK73hg=,tag:YKnANLHi/5QBPcQ2FpdAPA==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:CwS1J7QtHlZJXzDMuTH0q9iI2br2qVf+EXk3PHqJjqygaZBwF+a+6IgSw4LsJ0c=,iv:m0UVJCeLJ5PnxfKvbCmUTwYwi8tkJ8UWz3GeIPfGqWw=,tag:K1CMfVPTDUT6LoN1Xio/ig==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:7Er3vEdJGEHJzKZ2z42p/8iNMlUm1g==,iv:h3nTth17/eNXa1TfdNOL4u1YYhsIUjnZb9EVgxhGiLk=,tag:FsasnwuTiLTYvG0JrN+JjQ==,type:str]
  PGADMIN_CONFIG_OAUTH2_CONFIG: ENC[AES256_GCM,data:RwWNfjNmVhCgz/9PJOeuFy8KzfsqIGW2dBopMsuYgDLWNCzY2zSTSBs0nNZymSQ8bJgRFRbJbiBYpuQPp5XuoAWxfxPd4mFizOvzRU+eH6/1GKv+ab4nE4JVuFHsbPd2CIR/mKaVPmYlnKpYP8ON5TfCBYToCzblYkLkhOritxkwK34JSIvAcudbUpryDstShoVhpFkSpdOkTqdFMwF+XtfV4ws/Kw4hzX/MgoeNcSgav/GByAS5jvRz9Op7NPaiJXmrURkQlKXUWrjEfVlU8WRPe5liBalYc9hQmSMJIIbpHGEmS0Pm8PWvKKY2kctI1JjIuJqxuxpO105dzIseDwf7BJGo4noEWKaEzhKy5OPq3zAnvRYY19Q1lFHuaTmKH2juC0adGm0gK+ygcM9hf3nEHvCULwLibqoD5oqq7k1zglE+dSSJodOmYuhqswmn6wFsu6k0bwRqQsubQ4s9LxxCwCG0/7WUuPyeyMCFf18TPLkqj9SswKaw7YSU1nBDbGN0UJEfGXl/wZFhvp/TZbwyaI6hkieCSJWifiu31MOGpDV8MVW94x0SNiwOfRU5UXIWuNHQrm/z2048Hgu0K6HZ7moZP79UUmSaW0V9kzP9Tg1wSdxNOfpDHg4ZwNvy/Mf1Koh9KiFtYNhB6rJPc3H1HgGCcgX1l5wo+7iSIKeDqXrf/fyZVB4DsmutnwpFUpEnCQgyXHPvA5huMBvqeC2i7NQhxHMLHeixMS/wGQW62Qy47LMuxSqsicTZIVCZMVnXBB1tXxY9kzsQXgPQ7J4/HFQIY7Exwp9JpzIJJXdaRs3U2a1125RHEjweR9cRYyWSgZhcRYpKnF1OoSOK7aCQUkDnOTna7hEqYp/AcG9TJdxFRsHCdCL2OwQBVymMyJcvDBJePM693glQzKjP5M9QZgiQIF4jMh7+hbSd3SKghMh5BPC9YW1JOkKVTJ2f,iv:ohaPaSmh/vLWLOHTWQaxZ5OssR3JeRM8FyK1wpC8iw0=,tag:5GhFsKHrII/asJKORvtrfw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ29KN0lTcWgyQVN3cG1Y
        eDR5UTJDVERES2M0SXIxcURUWHFtTHYyMURVCktVQldZTE1PMm9Fd1ZUTHpmcUF4
        bFFpTkVrUXNJYm56QzloQUgrTEh6MGMKLS0tIGtFa1NWTE95OG9wdUZqd0xOclY3
        b3pqSCthSHROUk5JT2EzUmNndmhVSlEKorcEzg/uAZSCVWARbDf+U6H8a8KHlTYu
        EsFjghrMEy8nvK0OYPONoWG/0qwDG8jJ6JoCv/Wq+bIpGH7nc4hnNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T12:16:08Z"
  mac: ENC[AES256_GCM,data:peuHoRqQS1nA5MtJOHbH5swo4Tn/Lj/efkqOzHfkAXq0h2GHXjgavD+zeBA0Xab6pIE8myfLNadmWnwohJw1VouLUTKEOzrbWl5uE5k29Aik0Ua4RX2177bmJlWBEaA1LanX28GPBErlc+5UR5RFJerw3Dhbmyd9Lk4KxYesOmo=,iv:YfQN/jVQthz7N36adlT98dedWwttFqVDkGMzKeQqt2Q=,tag:cTdYsD8LVvHoK9E2bopsmw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
