apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:nq5wIKUOSRNilGVbhKDej2M=,iv:nvK8MsO+1QblPxPaBgm8zxS5kY9AiuKCi2NcLJriL24=,tag:tv1j8lEmAVtdEUbtYsadlA==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:gkSYi2dMPHJISaQx+K3s0Ojq7GdR+bwpqw==,iv:p62sawitGzbmh0WbuhTtAbCqsIhkbcTxTMZQkL+WDQw=,tag:xeNVecb5cB4Qmncnzy8hRw==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:JlqPzQ==,iv:o0VbF83qL6QgZZeHRH1SEH8DdeANF1jVKV/ua6Gp3lw=,tag:vWkELU6EN3ZBg8uCa3uIKQ==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:d4xABqU=,iv:+vwVGTRHCuplR8zYMiCmf7FO39FzKqem6Ht0hwAMPq8=,tag:hLibWGBL206/QzqBW2nMpw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbUZQNS9zTlhYeDhyOWJX
        YkNvWklRSDgvZExIRlB2NWtyV3RLSjd3dm5BCkFmS3Y0NnpYWktjS1BtMExlaDVG
        aVhGQll3N0dGanFWWStnYVMyWW9sVG8KLS0tIDBmaTdVQXhEYWJnSmVvKzM5WWtT
        RHgzZXJHbHFKYXdIeERvUVhBZHNtYXMKxpu6HT7v84XMSD/6NnHsu+fys1PV3og7
        WahykGxXgsZipEiwW4sqdYV0KdmTucJ7UEV0JV/tK+ug8GpyTX4PnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T10:36:49Z"
  mac: ENC[AES256_GCM,data:jk61t2eSt4JISUST43KkOGWb7SUPmsCguMdlexugTqWkmfADCBhSfCK2SkeFL5D2ktovM2Nec9ctn6EoM/eL/EJJTbHjAfeu4XecK191U7TLoFkE+cSRLfz7fAUVhTm2+zC8ugHAGQFyMX9RUY8tdkjxO3EYqwabhvxYcrbJY9M=,iv:k1M3xHLzRTiNlghi7mapx5nWqbhIrUTgcPrCDNnTWoI=,tag:wNZgeERrVZnzrxbnuGJnmQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
