apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:2ylFLvIjiqrlMLzSi+WfLrY=,iv:vAWPVrX6rGsCncSV3DV1e3uJCSMcPrbi4wtfBBMd+zQ=,tag:eFDRppfcJ34wcScgX/RCPQ==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:jl9Jvpzcir/1eLGdRklQRRyusHfvOLLGUg==,iv:TyVoyhwP+3uPBLtCiY8VlX0uN45+2awvf5WN12J0b10=,tag:WuKYbMchwo4+ftCklEMOkg==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:FGxcVQ==,iv:tESVTCqf5HlNKrldX4FPT/D/AIor+aMcALa55RskZZw=,tag:vkLR1hQI+lSzi96IBSTe4A==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:3u9viw==,iv:MBbrAMN/qDCGP57B1WLcpjyBigivDqWaEZYLMe4AqSk=,tag:8jUnwOyD3ZOdc2FiRSiF1A==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD: ENC[AES256_GCM,data:HILoN1xks5bp8LRv+/hZoX5R,iv:hi/hxJmsVq0LBHn/38qUZDpYosjhhURFnDZx7wD6Ni4=,tag:mApD/8Kgh2cTwuVu1SEz9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtLzlEb28xeW1pM1djdWg4
        RHpvVElHVUkwQk1PYk8zZ0kzVEhKR0loZUFVCjM4aVMwcU1wcit6TUR0WmI0TENI
        MzBwcGcrSG9lVmU1K05RaTJsbTVaQmMKLS0tIGZEeEJiajdPMzlDSmpwTHlLNzl0
        dFZtNHZZaDhhNGg5YUwzRjBoNGM2NkUKKY5Yje49wfZPT0ZZq69BJXAFBI8xOkBr
        mkN6scITU8C8G4jwML/nJmIlofw45EG3XLQ5IGnasBn5wZtMXTMQnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T09:11:33Z"
  mac: ENC[AES256_GCM,data:eh2LRV6kaDv/QefYiIds3R7wgsT98katjSeVKzJPYRbxv/w7kcZbKe96ucRMQUU4JeB7rxAmBrUT5Pn55QtyrqInv6RA1PTfnoHdesNrdDo+QTzpVGriwfD5W+hmAGvdl8PSyygDOKD7cZDFBf+G46pcniSjrnVFvMN59/ip6UM=,iv:g4uoBt17lkTWv5LZR3VLxFNN+BaVx3pcKEPPLb+dnhg=,tag:aCkewUhN/+xuPNfJzKj5Jg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
