apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: databases
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:S3bxtHzFXRtqiKwGma/wvbY=,iv:9IEO+o1z1trLrJc2ghBTiWVkyqKv9yYjNAjZW4idrNY=,tag:oFFrQxl9nDQ5wS3FmhjL5Q==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:RS/SVE/t+KACvS/CZga2Rbioa7+s6Wx4zQ==,iv:2fx8ll8UPUVqB4ldoS8z9ky+OQ/NK4myALhzlv9Da6o=,tag:4kX7Csa4rtlWykJ/9m035w==,type:str]
  PGADMIN_CONFIG_SERVER_MODE: ENC[AES256_GCM,data:+ml+YQ==,iv:RtJB8/lPMGxwYLlw324XjAtCLwplGTMRrBLwz7P07kM=,tag:qo+79j6Fxs1ByZbQMOL2hg==,type:str]
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ENC[AES256_GCM,data:SQTzb5c=,iv:Ul+nOMNoYUgEpJ/Tzw4x9bnzS0PQJYkM8kmUSXhKomo=,tag:7OxfHL9N8Ck3zFZjNk81yQ==,type:str]
  #ENC[AES256_GCM,data:vgIJV+dUg0vTjgYr7P06f3w+3gyBuEJoSLV8GKHZzIpQmaUs6/PO,iv:JEQ6pPGwic56cpXV9TEDzEl8/igaxnS7AHPKyVm5IHs=,tag:tZi4/SLH1wehgmieYtdoBw==,type:comment]
  PGADMIN_CONFIG_AUTHENTICATION_SOURCES: ENC[AES256_GCM,data:oS2BbBl0rISQ,iv:wyaLc8yWmLDOhycSIwkFOeK5ueSnTPKKVsBXrWxqn4M=,tag:Ls7zxSfWTOx0c1fFvq1KBg==,type:str]
  PGADMIN_CONFIG_OAUTH_REDIRECT_URI: ENC[AES256_GCM,data:OtJPENzEfJSqYuZzo3Xx7Rk/BOuKYzoAvmrmsvmTLm8cEAzpRQO8QG/+,iv:X3OU//b+xT/yCvsw6KU0/Gb3NGlUUSV8S9kYPlztQIg=,tag:Rt3p9i1joLGME2XGSjXJww==,type:str]
  #ENC[AES256_GCM,data:z5lpsFRZ4aqZZpEMnJXt1d9O3sHpJU/otxRkNFsarPkXKneEY41xRKv4BSahkMRMxHRHCl9q9RQmZVMmPhkPgag=,iv:zx822RQ657fbAAYJwgCBQliuVapIosb/sOzWC7e9PYg=,tag:T+2OPCgf/WK3pMImpNNrog==,type:comment]
  PGADMIN_CONFIG_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:t6o8I1rI6ZZWEjfvUU9wSUGubbWnjQjUxDxuUK02r0wfEuYJC+ll2KMf,iv:0GfyfdbPdsljBsfYPrwsuB8YfogUWKv9enEsUHwNB+A=,tag:6aWwGpJmqzGhdGZMIqNqWQ==,type:str]
  PGADMIN_CONFIG_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:tW0G2rUfaJ+DyZ9SziH/OvHMlgfsS/4RBhvsqIWgXnhHluir7L1orzbub8mNBINdB3BCWs3U2LFgGJG12/eIQQBk5mMzL6zCEcgEV8iG6TqUtCgeAf6zKE6n6D9HTcfb2Z4H60bPEBD35NyeaYPuI3Au0KyDt6iDpM4k0GCEOI6kMw==,iv:81XBainPL7TUMvz0VAEW410SoNN4huLWA3QtGpC8rto=,tag:lZ+S8w9xMJVsas4TiTyKww==,type:str]
  PGADMIN_CONFIG_OAUTH_AUTHORIZATION_URL: ENC[AES256_GCM,data:Td5SOqsDIRO5OKx7jDUMZFxfIQUHPFvfcgWZfzeicz0KiSWaHl8lBlwfqPOKvR3C,iv:bU8uKMz9/26kpr/8FK/MjH3zso0QSCQ4zSTmRKp95yg=,tag:LqpS9aVR0XZz3H3GvsVTOw==,type:str]
  PGADMIN_CONFIG_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:FiCKwvxmGZzICuR9CHmcIvk1DHLtjEL4G0rVFTmhsYaxwbCbmdZuAua93Hw=,iv:e6hb2Xp6L6L+Gf99D8ajrvbWSo0wmSSFR600PnDob9U=,tag:65Y+hj/JuM4+bcm304wwqg==,type:str]
  PGADMIN_CONFIG_OAUTH_USERINFO_URL: ENC[AES256_GCM,data:gMgIhSap7sHay0gYqs166cyf3+gLkrJJ5zYkos6s7poqpwE4bjWV6G4kBaZGUyI=,iv:Yr5EixtOkh9zws1oOheMZ47a6zSqzjoDNAPy6sEblzg=,tag:oWox4TrfiKBmMqEInnZ4YA==,type:str]
  PGADMIN_CONFIG_OAUTH_SCOPE: ENC[AES256_GCM,data:qQcaxFNteGMdRZgrGtT7vPs8VAQIOw==,iv:oDy4qjrsVKzEAwBcI9AAUrrEMPWhO02LFs2rDYdaB0M=,tag:2HO+2V+dccCYiIUj96Bvvw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNXVlb1hnbDZzVnFXWDVa
        ZmJRaXd2cSt3RGJ5clErN24rMnNXQUFPUGxJCm94cnNjcWRXVUlTZjlzZ1dkOVVL
        K0lPZ0ZvREZJTndTR3IzWE9KRjJYUTQKLS0tIE04L3U3ekNKMUpmZUxFYWgwQzRy
        TWNpQ1VQNlBjWlFnbHZBNjJmYzNUeHMKVv1v32wvc+SelGRWmh6JoZU4KA+GoA+w
        kgWotgXxrkIStYIbKlnTlvdq+2+ERcy5GdAuASdaRJZiydl9c1n4oQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T12:02:13Z"
  mac: ENC[AES256_GCM,data:fBoEsBJONgu/Cxx8W9oqO+9A2xVWJG6IJsG05FwvVcgu7KAqjgdEyeajH2yAO0aTa7HoFE/qIhZyiyljnJK2w0WSgV+L5s4+ORszeYUqVPaOXlcn4V1ncr9OZ+2NEUa1QcCVhmwk+XYwYTqGa+SUXJQd7lMjCm2asA82iAWfvGg=,iv:rwoGy4C034dPFF5yGeVUcBEYqc8tAXx0FuA2qv6NPUs=,tag:9nU9BLuKgSsHDmoEoSqhfQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
