---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: office
components:
  - ../../flux/components/common
resources:
 - ./actual-budget/ks.yaml
 - ./nextcloud/ks.yaml
 - ./omni-tools/ks.yaml
 - ./paperless-ngx/ks.yaml
 - ./paperless-gpt/ks.yaml
 - ./penpot/ks.yaml
 - ./vaultwarden/ks.yaml