apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  #ENC[AES256_GCM,data:fuUixow+msZ0tj5pNv3exYstfXG2TZZH5H8adLA7VMVaR3yZkTtADSDYkDw2CbYQ9TJAS3YoeKFp,iv:IHzHRS9m0ozfXOT1GfPI/2gTdArFlQomhvX2NcU2au0=,tag:KBCWRn9da3pmKZ6J0pCIdw==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:OZeU4YyFZAky5gKxxPDeBhHyu55chrjjyqdL04YrM+iJZeHR1Awoun9DAMz7CRnF27ELaFMxSsBVqp6U4uMKcXPzVSnC9S/2Di4g/Vn1akwwR8d7pPVSPlHyeL5BxDLsHT0RN/sAB3J8xB8rZJzO84hR+kywiTYFnBkFE/0mac3HLIDSf96KOaoi54gcpcxzjEMtSzIR6WRCbmz3xSe7MdwFDG8=,iv:tkaQlH17UVjqrwMhhdxoGCpMV2JaxKij5sZGZw6vm90=,tag:i0gMiqryQG83u2joQ3uerw==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:kGq0QEKGcJQaWc2a3yg74rDwLtioAhjGg9QoSOG5,iv:Z5zrtrFLzffKWrt1tPmZpSf742YrzG1jZZ/PCnHXbhU=,tag:uQw19lvAFC5sdjbYD1b3ng==,type:str]
  #ENC[AES256_GCM,data:+EmtzRyhtHTkwVuxgtZiC9+yTAXoQGt2YqUqin3AIwk1zl4FyDNmQhg=,iv:0mW4lM+Yl1z681xR1tLUHV0Yjho6JD0hQOuOFeyTix8=,tag:N0r74tUNK2xKJtsS2t89fA==,type:comment]
  OPENAI_MODEL: ENC[AES256_GCM,data:mFw=,iv:ELnNvYOrV7GRNyRI3541nmX7rRd1Ak1PBU7OfZ1/uqw=,tag:sfPvlin98orvN4eXUQQ38Q==,type:str]
  #ENC[AES256_GCM,data:Bs3BxC5aUbp6UyE7fksy5P+CSdD6PCCJfCQB4xREVuE94A==,iv:XPTEUZ6zdXLTCGdW6HBF52eROnnbv1AUx0kTkBe5MYM=,tag:IsZiruWU5ieRuhDITdMxLA==,type:comment]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:aq8FlZEqJkxpUA5rwIaxOFScaWGKmMI=,iv:5YEFDYLfDqdlUIKaG7qMtDFqXOpzPhKvOXcDQoi9Xx0=,tag:lWZmOw14hl9CX7c3nPyD9w==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:xoyA2ONrZyW7Q/bICk723i+wG7BTYHznOrPFtZj1KGiv53wgX/ghBjiFZASfOAR86A7eSQBniwHkWftm77UXjfgNbIv9BlfADyt6uVg=,iv:CCKh9XxLEPm2MIh3miezaOf8agEUC1bIkT4MyYntRpo=,tag:exMDyzZ8KvzM2sT9qFPrEw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z2VsMEtjQ2syMEZYYUpu
        YWdmZjFVTFpNY2xReGFCR08xb2tRZXFud2pnClY0VW0xcWZRa2M0QUJVQW51Y2k5
        NFpwK0pLR0ROZ1p6aEtpVlpyNnVKdkUKLS0tIEVCRW9yd3RmNXZocHpXOVVLS0w0
        WE5kNm1yOTFlVTlBMC9NWU9FVm9ySWsKYONohSI1yhSY9bWc8Rqp5XWvTuKu6emL
        a9PMP+lLBYiQDEXfmO5TiY61UdAP73olu1GI0lwt6SXNIDczYRaGag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:08:46Z"
  mac: ENC[AES256_GCM,data:10X4sQIOdHnc1Y9GXHiQbOQtMCWmfMlH5pEV+eyh+zmkuiesM+H5YVbDb6O3z9aB3JID6TQvWcMoiv1EUoKfPxtDSjQ+V4s0obsPczPsQvQe9c0cOS1eDwOSJkFSapPdgWNyFLeYZ0UNoaM18//uqUxzkTho+hI9xiicLuNXYDI=,iv:xR8xSYwsWwrjoz41FfRWfF14Qo875MzFxGbhRIiA6mQ=,tag:EXVGyZ0o1xALAmKa70fJDA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
