apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:MUxDg9GJAXctKRh6UCKi0pUGdvEyk9qinzHERo4XGG4DB8ZfTEU5d/l0Ao3Oh67yynbIdrt1hX59tz3MAf2xLVX0jWbtPMlkrdjQvmbrfliVmaiLopIuANSD0W9wowoni9Q9lb5dNEH/Kwxd3H1E/rzPQAofs1Ma2zrAPrzEuIPKgPuZhgerX4urvKnRQTifHJuAcaVzbhBqUdzcIb9ciyISQa4=,iv:dfc+a+xQA2O1tOT5x1t+9wC0F4kUxNtoLcgiyZOtHfE=,tag:5Hx+jVyWkObmoXQGDBboPQ==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:BL3kFHZTPoG14EMlmsMl0Ez/O57a4Q==,iv:LAU4s4S4RfqCuvHnmuZ+9LqBprrsh7chm0oz/oBgRmQ=,tag:1nBBYJCfZg+XoROnC5nChQ==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:64+vchLceJ7tQddPyQ==,iv:g/w/yABMQfG116ZB3WqdFJ1L89zxXVdaDTMWlfzjGG4=,tag:8n3FdCKACZ+re48Mp3h/Cg==,type:str]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:w4da08GNsZM3Su7lLiHbeu/UIsu2kCk=,iv:QaaQcSd7e2HzMXWNH3d0ze2Yep8FmReBjct8F555F7E=,tag:BRlPoWaSIH/Ub/Q7c2G8lw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:hvJvOjfiidxj77/3t7i+qKlDVCSWJjwWEQObSqhRtooa+2lC00NZRVom/PblgbnQdn1FpxxcJNJ/YlUUGUBRHXNetBQytBWJLAIviV0=,iv:z6AAGidy7Rp4HHJnId7d35Q17JbgzerCmwBZGK81q9U=,tag:dzUjOI/GL2aCw8fe6vWQZg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QUFqVW1JWHZsY3ZUSXZy
        K2NvTUM4K2xvd2dXOFp4WXdDeGErZnJ4ZXdnCnNtT2Y3Q1E4T2RDUWpuVnJaTVAw
        amZQM2M0RElkbHZKQy9WSWZiZ0JDbG8KLS0tIFJucE1EM2dXS2p2eFJrQlM2bEJz
        dG85N1o0VEtNRWZiSG1KMWh6QWFLaTQK9+j3m/2JBbk377arvukiBnidpcSBK4/L
        urbGZqr9Cj4yaiuIOS26xmLIMGLJqoeHLHv0s2wplOLNYPMaZOz7fA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:34:31Z"
  mac: ENC[AES256_GCM,data:6ot7qgi1mqHZaQH+V577hbbD6EjTBDfsocOP6RkwV0+iqDliiSR6SuZoj5qeofg7sKkHH4fUr+EHdHMbKOfyfS/QbRXXq7oXPvnaXwTNZyG1DyyYVGj6mHm4Pmxznzt09y6LZkg+JURIuPy1VC5jh1MwAiZa3n4xYLq8OBvtSWo=,iv:Hui+kGbQcYdKtW8tgO6O82N2gOk6qPErltQAuJfPT6A=,tag:91SHFMk8VdmJt8Y8G95hig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
