apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  #ENC[AES256_GCM,data:KOxRHFKCwC/rloxuBK7doAawOJ88NBi1Nsow9CnmjHOGTs5v4WutEHFcxpzGZnZij8IG7xTbUrhl,iv:VnWxkAIbUqxyfnnnnozQtUq2REu+qKTLTTRqmyaD/7Y=,tag:zYC0AzCEpRDjpMbmYPdeew==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:lNEcKlbG1XESEkHH0nvpuvJFoLAg7y5+ewZ6eps7pIcBBGjX9NSG76FPaNScNmJsvVt+BLJNME0bloU++ZUWaz1bX0XObwQzwC92DqNx5L///AG92LCzl1nVwwF+SL6S9B8oke0/07K7Hs/wwsJcF+jTyRXUZ2bIdWqegzVFwR8ShzNV7/RP1xKryKg2bgbsr0MAS7qwt/Y0Dil5lZjlxr4LzdY=,iv:Qz2+bacHX6t19CD0iy/IuBRmzwu2PIrCzfvayWGW6U8=,tag:5lic2LAzKpP4R7hsMvXzjA==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:BEuezupbu5gkqBoTQbA78VGF3Q1ZrkB1i8jY4C/L,iv:kNIVYdxE92Fxh9bV0OvGLjecBtA3RUw/K625/oM8vzg=,tag:I1WEx83qqPxdslcETCIJxg==,type:str]
  #ENC[AES256_GCM,data:aeb4R/KiPtLl+O2LNq7mkwQo/+IU4P+/Mfpc2b6RYg8Zb8dpTVqd/7w=,iv:ZHDN9U1ug8KrKGswu5YA7arMD2S944ql+OqmMnYKlks=,tag:xhkBSAjMvtwieRf2OhQ1Vw==,type:comment]
  OPENAI_MODEL: ENC[AES256_GCM,data:cmSXWQTv8RjL3t1HKA==,iv:CeX10gXTjHaMZuS0K22izfpCbBPgQ2xQ12Pnywj8kfI=,tag:9S8I/0hDoFwL3V7iAhY9Iw==,type:str]
  #ENC[AES256_GCM,data:ojau+HtmSE6J3A1Uh6o/XIEuMnpQmpu/r9pD2mOSTzYV+w==,iv:HTH+s8XSlRKh63CwitQ/NYC4P/xhdgzzlAH+hOkMnqs=,tag:MhTw/jcLMTP5+G/6Ntz75g==,type:comment]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:u5U0BOXz3Yv/QZGvRZcE8QYb8IDFIBY=,iv:gJ1mMsI6CPM35lHMtCZDbp8w68B60tmTGy8C1unAfB0=,tag:/ONulPjIYPyPPpu9lEk4TA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:Psd1pqdecGZ8I0KhQBKzSh0BcKCchMWB74cq9/669Kb+jFjTskrhfakuc4Tv2Od82RN44WEr0zM2jaDMrr/NU4K2tJtU2o/PspKblU4=,iv:iWxkmZYGMat33rz1ptmlKFuGtnvFRuER2DZPGBI0QxM=,tag:2K+3BzARVdjA1zhH/TXfiA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZjkyaC9mQ2Vaa21QMnZu
        L04wa0I2OTRyZGlSVmJwRjZRdjBZUzRha0MwCnQrQzRReEk5WnhBZDkwaDdTdS9y
        RGxzOS9VUDRma3huVDlKaFhFRFNEd1EKLS0tIFFSa09WbEU4SWl0eFI3bjlvOVRs
        RlZqem9rbGFWTHVhUUIyOHp6QUZsTWcKbHNcR8CpNqUIZnZxFvbVRD794rNKPqHV
        Cm0B5cs4W1EgHXYNdVmB9JGR7VNzaCnwIxEmq++iyOQv9po/QopLFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:09:50Z"
  mac: ENC[AES256_GCM,data:N9yQEoV74Yfo/X8c4/jRj11RMkEca1dVcElMObqF03g65ovsyKLojGLLdtneadGRIMlqqPz1GO6A19oE+eJXgSWwM2+KofCDK2RhUykIiGYGMYru+QiiNShFw5zBSAFAZN5ptCeJiu567lsyql7ZE7bPGphD386be7Wt8xQxRK8=,iv:y2uWL/zQuCJ46rhDWPC/v8irDX6RFnOVGMorPGRpmeA=,tag:iHR01AA30BoM/jyqA7R1zQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
