apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  #ENC[AES256_GCM,data:TjS4K0P/nhQHvt5Crw5LZgHgu0It8dtKi6AbHRhDemh8iB5ILFinCKp1Vj/F8pjP9HnV/TuQ4tMm,iv:uIy5hpaqXJ2xCvvR8RXaeUJHiFaMxjKwI93Bx3+/81Q=,tag:jFU0IlrwAsqY5TFgNGEevg==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:cG6knW8H4vogUDWnMEWiXdn2bRbaVIxcPLBbJoSSFgVyW4Sd839PBLeF1YhnBqpknzT134YL5kvJxLgSp0pNlLsPq7zgjoRr7ZkA7o1rGTee8xi/K01I17G180uPEv+K6cYneDKNyozKUAM9Xz16ZckewLYesmJIcYWMDJhkzHV1TtF2w9PRZab9oDpe8XoHe0vg8MBm/JnO9GEfiS1Y6oeIqNo=,iv:7jmBXebELBB7fmXqJW6AM6gvrm6x2WzK/mrL5BX1i7g=,tag:X7h1WRRMkEhlKEgt1yCQuw==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:V16wiz3Wl3NEIiA0Tba1H4V8OGT96kUCmA==,iv:P0AQPFIxlpXaputr1GgfVU5dDDzE5IeYQs/K5Kb8BGI=,tag:lYaIuMqATeyV3rcpMeCScQ==,type:str]
  #ENC[AES256_GCM,data:bvbqehbbXJDAJbUfBHoIb+zNrRsO0lbibU3XRODhxUBLAgwYGCKzUUg=,iv:3I207DNBCkk9jnj5H9LvzmCsohQRApNJ95g5TWskyrU=,tag:5GD0l672GAn4mI6dEae07g==,type:comment]
  OPENAI_MODEL: ENC[AES256_GCM,data:gB+1+OHq,iv:DdLZCZeMQ8AOJ/+fafzadSB0ux2fioKcl3M8T8l1sAE=,tag:+8abhPTQoK6dShqOk8iUQA==,type:str]
  #ENC[AES256_GCM,data:ne56cwvFGqibtk4aL9+FCBwsRNOQDL2RV8HNu7g7Hjb7TA==,iv:DaCNL3bXiQlPVCpkzMbKDY3560Dnzuv/rmR2ms5egjE=,tag:vn7CSksuudMzZnBlhFRppg==,type:comment]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:gmBv6aqT2oUc1VlD8OM0Pu6vFY/B6Jo=,iv:aikLWjZydS6glz5qbj+yLzn2ADhfL5cHhVFJxBtF9ys=,tag:dgTjmClnfpdac0kOwxnkzg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:Gihuudv9FhzMI3oATc+dNFt6LZAjCBP1HRwb4abpPnztdZSw+V8SP9b2L3xMp2lnS2IZlxwNK9ek4DmhTa6wMeN5NBu98e+E2UTJxWU=,iv:HjqGoSkwbRK+UY0BqTp+ePt+SEwJY63XjJgEaWiw9P4=,tag:Z6DL9j7OMfSVr7Pn3AFLUw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYUVIejRMelZPRWxyUGZz
        SGVzVWdDeTlBNng4eVRXeDVKU2g5ZStVbzFBClM3a0dnYnZSL0NiajIvV1FZeGtI
        MWZ0R2F6Um00bmxWbDU4ako2WGQxVDAKLS0tIHNNU0VTUHJnT2wzK0oxaWowUFdm
        T3RlZWt4c0NYMkszRHIva2R6ZmFjUzQKpQxAh3dzh86vNnM1Xld8cclXd45QPKT8
        izm+GeMQNCcJ9j7Py/o35Wse9TCT9WfkwhDkRM4SwZgabFUd1cI7nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T16:42:48Z"
  mac: ENC[AES256_GCM,data:2MJ0HMMd7xF+pH+x0vJ2ImlYq56bAWb+tMYPwNGBioqwGwiUphXtcItvMqt3IuFOmvy6/VzzHyv7uRpR9iNWsnURhx3QNfuiCGwqnJ+aUQJQBhbbk6AWqcymK0zhSq42YCH/xyh7qmFLRDr6qNWdVF0SdN02DikyNZ3+6wDX6ZE=,iv:3PpGD/vnuTHJX5zsGiBbhzQoKbXBInzuY7/T279oA2I=,tag:N8qTp+bIQm7aiuQCrDR/bA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
