apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  #ENC[AES256_GCM,data:oJrwcJZbq3Ell+cxBnh00p0os7U87BcUTBNwY/elpj+x9tzCcd/8fHdoZ0Wc2c4A9lTR3pjnxK8P,iv:H7m9CyFIwkgT7kGa3tUDDPIf+IGunJdcc6+s26v/kuM=,tag:XAbnDMEYXSJgWKzgvozuUg==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:VCjZQImDBkb4fBaVhUPILPSNKFSzA8IyaVm3L/INM7aHz94gtYKtsJO3hLqCLJMwhCbo8K152Jigxd2pJTgJ4+FLS8K+hnwfESrBQ/B8iWehaR45qkuCbeyxTHuoDtNW4EPlxsFyBzgEXDy7OBElaVdZndCJkFCQTxlHSV0zK1SXOrfvN55P8yMk5qkm46kvu1RC0pOcev0unEUczeVKnUq8FF0=,iv:yIIJWFm2R/R6ga7n0jMrcIvs0dlDM/kh5LR3FZnaXY4=,tag:kCHuToSZksJmqJlULR8ftw==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:MC9rPxdaNjmqzosoFMuwufW4qukIq8hkcSxvhRv+,iv:D1JniDcLq0L5bpMA3VvCYQQ166JcbvOvg4rrsHIOLuY=,tag:oBKRWgsmS0bnu4va5W/+OQ==,type:str]
  #ENC[AES256_GCM,data:k6VgPWHamBudcVPtQwXv5hRD1YKidWb9Avs1cNUaBptxlBnJPwLJ+KY=,iv:MotirIIewiReALonNaTGLyiIRkTGXwuB0mBAeu+iOQs=,tag:I11fvvRwOkM3sAE2cE6kjg==,type:comment]
  OPENAI_MODEL: ENC[AES256_GCM,data:mcxgbYmQjkwNMpLoZjgEmzAepn0=,iv:d0Z0pOQ3ceOADR1txJkAqbABwak8P/0+2DX86d5T+Dw=,tag:O3mznM1JVHEQyuWBmlnXpQ==,type:str]
  #ENC[AES256_GCM,data:G1GAxsCUILWAC6anPvTSBpisKcTRcXqCu7VhQ7Ui9CM4Dw==,iv:hluu14nyBbFFbM6/+YcUpyLlTtBmFSVBvmvndPdGGU8=,tag:hGIWmmc0l3RNyQoGEC+lng==,type:comment]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:oAGvbPWOIViN3nb53g2DD5Z6GFQ7zA4=,iv:Fj613n3uh/02o2RikVBbYX6Qlh7MH6SndupmJWrNjb8=,tag:OEckuVu25USz/B7yCNt9ng==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:nn0ulfwrJQ1+f2j1R4oRDY12xJTxMHZ77ks8Fhhsw7+zWa3gbLPO+jfWMeWZx6FlGnAI6l838u8cQWJqYe0TBGhwF17FyBD0YaTz9KA=,iv:iibAzawI5gBvUkGms1jw2dXnlX/taS7sfqcP306n/k0=,tag:KUS5VSe2p257dG27jGOApw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUUtYcnI4SWk5R3o4K2dH
        UmNjd3pGa1pIQ1h0OEpSZHdnN2lLOVBRcVNZCnA3eFRsUFJsS2FrYlhKUU5zVFpJ
        YzhlNzUwVmlLKzFiRlVvS0NxNjZwS3MKLS0tIEtObkpKWVp6WmFrbk01cTlvaklG
        NjUwTTEyZGxlREgwV2ZpRitESUNHbUUKHghZjGWxYB2uaYft/v3MexCXhKDtUi2e
        fM9gWGoe1X2J6Uub71sj0nJ/5UAXKx/61wtYOuShPZhZKgIXQvG+KQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T14:56:09Z"
  mac: ENC[AES256_GCM,data:/hGceZwi1BsNaRoDvEeHJ3LWipzarZAgECX8IhQXQhRGj091oUISPZH4eB0ukv27AAhZwvG6X1uIJ70iC7xLXTbYvGSyNN3a17NPCsIm24jNGXiLSNa3YKfBnchAM47MF53jMMkLQIbyBB5fRTO0mGf6RGCfAPXNa4GEQRkVK98=,iv:GYGip+H5AZEQZjx1enrzZIgg1Ajj/2fSFlKNWp72WKU=,tag:u9VTmjbfvNfyeZBfYdQ9Yw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
