apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:DyBVSaDFwOygsUxTZEELlhE7Gz5PvIZEZMypOQ0wWEHboq2Lvx5RIMo0ZuiowIsvDGBR7G+MbeCweRqwtUlmFNHsrjaTuBIGWNKuobmgfCEbcydCQroTGXh9vrKz2LHUWqHzgQxGithzLgJO2aXtUpgpnJ+H10kza7IaZKGjjEBT12h15o5dw4hwAHGFY7tjh7N8AlLpwUEVLS9LGLUICU14HMQ=,iv:YC3tSYUT/T2kq6UujMHzPxQYXfbHFkazI6s8uA2jhFI=,tag:li7wv8nslY7JAe545KWNSw==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:4aqO57vUrBatnl5CZA2y6hHhwzymZg==,iv:z5e8qRZd9sZy3+oBYSFTXP3p3yYNbq67M+YewUqo5Gc=,tag:Yjvq1JZVGRWGbbSnjSnlGA==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:j+1nKkUQmAI=,iv:2Mt0lB8zLtjvA4rXZksaNZbJ5M6OZ8gfyO7e/BdivRc=,tag:x/io9NhyF9fZisIfKNFXkg==,type:str]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:05EHuR9Ar4T8Qar0oNludONk7f7dyMs=,iv:02r2EG2w3OGSn6Y/1CZVhGUzlJPVjqv5TUXCXEfd6mA=,tag:D9UJIcyDydGRH3vTAGMmkQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:36GRMMWCvUa59juUwborBTUOQ3Pj6h33yqzukv8gmtCOGBuk+xuKZd3MSZ2rqcWsoLeIOvNW1TjNeCUwDea8Rawmp716XCEEyKqm6J8=,iv:KCMVGdFWV2bAjyHuOtw8JfAGZEUYIIZFbsmnSK0MoQ4=,tag:gFGE7NML/xuwHOa2w9XcDg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVmFoVks5RjRNNEo4NUlP
        Nld4SGxja3RWeG9nMmdzSWZWTU1PQVhrTmpvCnhBWTFLNmlwanU5R3N3WnlaQlYz
        bzBTb0sxdVEzMWwxd25FT3Z1MHBoeHcKLS0tIFMyVEdBendrYk9QTi9lRGZJb1R3
        Q0JQMGVsc0dBOC9JWk85VThxMkdVb0EKpKx3gKrjLLPbINpebUW42D9WrcfGTh6r
        tQ6tLuZz6VgXdGOPmv+R1jOrI7NgohZ5LSoGqiHvYm+uTEuHtWqSVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:18:33Z"
  mac: ENC[AES256_GCM,data:6OCq7dYdC92uEYTJGurCIlPznGaOVPISjQ0KKWax0inRaXxrlLl70SJ/Z60IcPUyE97eYayHBZA3HWeSGkaI0GCoyJx7HvdUOA+b8qMRI47/8jxubQfUaVXUU12UTu3X4ZhaPQI3hYJ7bXi0E8X7bBqP5EMNCzOAEUzoRsSdgKc=,iv:nGf28WVz4Es9qL5E1hlGUAqJIjTRjgkYGQHsYvrHOOU=,tag:ql0Iqd3xO0lsq42WMYjCuw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
