apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  #ENC[AES256_GCM,data:3inJ86kbGSEsTYtxD2sRmSeEyyF48c67vg+yynZFCB6yZUdv11njaj9ZmjafSA1Qhf8gCWDWXung,iv:w5/OKftOqXsRvzQ06UfRlB7WafUOJsVOuU6sM+qo/90=,tag:T4bCjbvp04b4HOqwrM8F9A==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:LMObHtSxexhKWp+iV/6xHKPNjgHDw/nwmmRyHGxTijGhcfzYvQVaCD60n0PE/bHAhhUBHpe4grFp93lzpAWDE/O0IVue/SiUk0tZ97btIm7SWyzUozUZv5/bbZSgw6CFwViTAg0TGq7R4rYH58rzQlP1yROqszNrQSW0mKWq7GqZHlzol7mML6kmzb7u+j8bEgtA8bKfQvhW9IHvzLxaCDhwd94=,iv:34NakjhNkFx4Jsuwp02O2Wwrt7HQ2ijtL8IZYrBiNX8=,tag:/2sychPi4ZdlBnNsdjjP1Q==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:JU7N6TPPPRBqUnUqcH0bYYjY8rgrl9fkb7hnNQux,iv:Bz3cRQXX6hKUAgnLAa49VaOoXdaSIpinWenyYQVksNQ=,tag:XghDhNLTewe7r+OLP6/p3w==,type:str]
  #ENC[AES256_GCM,data:lk/7SFk4PqROfxTxafowFLVny5h+1DAr6QlH50pyCCfzGkLpFJQd5SI=,iv:DEAYw3Gkz6TvA0J9OE6DP2vLnLpZk0uuQw0GteH+QsA=,tag:hKqzHSj/LTKMpbNeRiNJRw==,type:comment]
  OPENAI_MODEL: ENC[AES256_GCM,data:6u454d7K05+wvoWu2FZtFLmATL4=,iv:sfa5cReOqIwN9owOBE7lv5a5aFb6bKIXgr+jQgMfcPU=,tag:uKIHD2OCpPBg+rxmv1se8A==,type:str]
  #ENC[AES256_GCM,data:4a/wsULYTvVPz9zaSnfqYcxAL6V/kIkVGNTJxooniyaPhw==,iv:e9Up0HpCIEKVS7itXgUY0DZLj/cBFuDn9JFpVc2VXnE=,tag:j7KKrS2a2auCw9t8xUpU5Q==,type:comment]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:IPnBS/bUsA+zsOv4qGQU05bEuRdabDc=,iv:0JFKaLKO473V5zzU6O3i8MhuGwA/oHdH4i0Zoboubww=,tag:kWrp3hknJlcRQGctyY4ivg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:gkp4JsnflDSmSSs1sCB0gQ466ed1DCp1JBC53CWTVXgO4b/XTJuElggamTejVeHU/C2AVr0jg9Ke5IQrPH4h4LeKC+RfiXyuA1QLzhs=,iv:9eTmpLKTRYk8yzSKrxS7LT5ypdF7rtcYznqi1KB6K1A=,tag:9MXQD+K2ECJaHLXFEmFJxw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWk5nUkQrQU5iMFFlSm9p
        QUc3ZUVsQXM2dEdTOERna244TlBiRi8yRGxFClVmT1pmdDhDZHduNFJ4dWpIVlpa
        WGxkSUl1dmQ2MytRUjF1cDRTL3FGYW8KLS0tIFJMa20yRHFzTk92R1VNWXh1NXI2
        TnV4Z0R6Y2lmSUpoVmErMzk4Qlh2QTQKZxjFXzU+Irmv3RY+CdqVlMUAN+mFdpnU
        +7bA70OGbo3XJrQCVPjsWixyRs+WEofelPMKGHQH1MLeSKepY3lh9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:02:07Z"
  mac: ENC[AES256_GCM,data:tXpNlnBR/yES/LH5UTTU/+LcPfUGl3hXqLCHuyA9ezf+jaehfLWzt1KDCFhRxj4B9h6Uen4paLBGy4kypE2tFeBqP1Weja8eXy9r5f9D43MQ3IZaX/Wxp2wzh8Bu3E0X71Nf6W4M2WAjqLUrfTfBjzoN0eP+WlMgqITzZPio1NA=,iv:Qkkd/Je0XtCvzM+1y4UH2H/XjgNgJtW1Xx+tqChS4dQ=,tag:G0+7hufzp6LxOWZYwDkp3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
