apiVersion: v1
kind: Secret
metadata:
  name: bytebot-secrets
  namespace: ai
type: Opaque
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:SbeEixXOwbBKbO+hnz6nCGd9VePVJSF+,iv:Zx6i6vDrNRBVOgFNomCcWLW/dX81HB8gF5ulAdI2HWM=,tag:vHnLx74BOjM2C+d/S8hlJw==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:uJPP1zXdYYB6Pu/QrJA9dXc9Sr9Nrg==,iv:qhy89vmcb4t/tbvGu1jcgdGXHPTAJjlAEC+XPG1f5y0=,tag:ZL7Owcwg2XCQ9h6clz+I/Q==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:3GmJBSEmH4KLitqgtQ==,iv:h44q2EpocydBqeh81X7j7d0ZA7cWCTWNmyGbhDUSzl0=,tag:B3LzYze8yKtLhANbJcSKSQ==,type:str]
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:E4TTcFpKYJF/8MjkRgtbfRHq5pHqO/0=,iv:YucMngvNvRkO9Cplm/cSQDRdBtaNHpzwBAlOAk5TlDM=,tag:I5PN7fsl6h1eXhMLoTTXmQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:d1n49HWblrK+0wNZ1LP6P/v/gS6rWzdDAfs2FwqfMWOgpWktRTsWGCj7rpdq21LukATzHHMLk5ZlCS0AtSyxeCZHp+wTLkI+orwBlDA=,iv:iVAgeyBrylaPOZzFn5OapgCoKOTLBanGQFrLJ+G2qZI=,tag:w/U2CHPrw70kP+Tt6balqw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT2w3S2RlNldHYWxMamZK
        ajNwRkJQWXlaZVFxTVl5Sjdtb2UvUk9ZbFZjCjVocDEwWHVmUFUzMTB4THZHbmZx
        SkNEQWpTUkhKVnVWYXJ6K0dMYWlueUkKLS0tIEFkTWNxS09wclQ2OXI4NkoxSnRE
        WTFndk0yeEhkMyt0bjdXZHliYkRVN0EKEmFENHFCG81zd0+HlVjaJAJMRohYJcmT
        RUvD0AOYtd4qsr+4GHFYylJKcFq7IFUtvVt4oUgIS6jPxVG5n7n2Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T15:40:53Z"
  mac: ENC[AES256_GCM,data:nKuqpw56xtDhig5cZuuq00xRgPlxbI8RwPkDSUCU3AlHM5z+PAFFtHYdvwsOkDN9c32deiV3oe+bj8ZCLT3jBoAh8wGzvfNVavDY0T9bWMU4I5b+GB32hINIEZWdYCcvHM2bOcouLPCv/5lgMoE5riGgezT9+ixth77lwYH5Hms=,iv:R44ugRCsbTVV+Poloki45LHMkwu6LK7Lf/UK6V9kGrE=,tag:Ms4occ/CMhxy83ONKIFkMA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
