---
# Longhorn volume already exists from backup restore
# Removed Volume CRD to avoid conflicts
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tube-archivist-cache-2g
spec:
  capacity:
    storage: 24Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    volumeHandle: tube-archivist-cache-2g
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-cache-2g
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
  storageClassName: longhorn-static
  volumeName: tube-archivist-cache-2g
