---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./redis-helmrelease.yaml
  - ./elasticsearch-helmrelease.yaml
  - ./storageclass.yaml
  - ./pvc.yaml
  - ./secret.sops.yaml
  - ./metadata-sync-configmap.yaml
  - ./metadata-sync-cronjob.yaml
