---
# YouTube media volume on CIFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-youtube
  namespace: download
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: smb.csi.k8s.io
    volume.kubernetes.io/storage-provisioner: smb.csi.k8s.io
  labels:
    csi-driver-smb: "cifs-share"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: cifs-tube-archivist-media
---
# Cache volume on Longhorn
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-cache-new
  namespace: download
  labels:
    app.kubernetes.io/name: tube-archivist
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-static
  volumeName: tube-archivist-cache
---
# Elasticsearch data volume on Longhorn
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tube-archivist-elasticsearch-data-new
  namespace: download
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-static
  volumeName: tube-archivist-elasticsearch-data
