{
	"data": "ENC[AES256_GCM,data:GiCc1shMdY6PwrpapO5doVNRHp7d9ZXQcHbq6d3gbGL+w1mtX9eyH4zijk/a5ew+WG+9OGA/rqroDuNaIy3dCqE5wMjKnQdICJuWP9aHWjF51YoNLK6Y+2nEtxxX9RkKtVrn0jA28E0VtHU9c4gcifS63Q8eLSMY7MepJKAdzzunRBQ1LKCFpJKIa6URtAwZudmpR2XmyRDr5PeNFKTAzLiDanxjNExy4HH9n8hWrfVQ2jt/m6oZPOCjg+khpFVKUi5wcmRrO/YKVddNKufUIK8KcKW75w1wHzhGRsFKtv47mvq03G352KPGybdEuz2tHCPE4NLyuz7sLHZWiR1BMjmfY4Tb7Q/QDX/da6iaiNP5Q0YsfhXxULzgG0uc7JT5vRLyP1ocU5t7zqSnaybDx+oLUKe3w+1ke6V9yL1/DKhrh5TxWFV3q1AKsCgn13PiZlgVndPWFcRKj2db83uNlFt7UCG3M+yzqKDN4dRUvLreLoUYRv6VhO0VqgxX0mYS7YUkK5Cyr7thbp7gvvWlad68i/MOdS/eEPvp75xMu/qQouHZVrbM68DQEwtGHnfDF38HXwmTjX6NeLs/DiXwS58Zxop5itYuzvbGK7AWw3oRbz0hGpOYrKbbTxngQ9q9mL56RNMPcAb2pMx41g5M23Gd1ppRroYcBh7GCbSqWAIpHol0S/097mcFvy8PT9rP9apd48EQpWGVOJ6Qqb47in5+JHlNVegji6cI3pFdYo8ufzCnb8LVXz2u/cPtvuUeteRK3FjsLDWK/AhnFGCJdDMbeDR4y+Vx89IqvuvEt9QL4FSh44LcLih2LwQ+m8zuOi2WWQv4WauqAPHb75j9c/WFfArw40EfilpExz0NAd0/ys2dcCpHIgZdxPgvxYMujC0+1Halm0hOixid3oIDNdIcyfNfMSmLDwmqMaC0S5vY8j63IntnFnCz3PDNDdPjWUE144DAOKonS9KZ7g7eytZLmQeMcnGo,iv:nEIBvVJ5iXiPKVBE3GxStA6TRz1uWL1L626kwXRTxpU=,tag:VkEQIC5dJKDccCWIUIQ+HA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbG41cExjMlloSFRxQ0VM\nUllWYnZJNlhESkt5MEFxV1ZxTE82MXprNWg4ClV6Vnc1YUhmazdtbzlDUlNuTWdY\nY21HVmVXQ3dEUWtPamRPc0J1MkNyaGMKLS0tIHE2dGZXRDdXY1FoZDVjS0M0ZFVV\nczRPcCtRc3FKUEVxM1o1bzFNWVVkUGcKrbAJCwttdsxFBZGKUTlp5zriDoUoMRdx\nHpl+aQ4pzI7D0qhPBmzS/WnpwYi+V5ICVm1pV/8jSEvhCmSR6V6WMg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-11-15T16:38:38Z",
		"mac": "ENC[AES256_GCM,data:pKh/sExzwRgo+Yguj7Q4RXVpLrfMBhRY1Qaq2gKZEOdXCB94U+bD4A3ZDBNCQ5PbTfQxAMuGuFsBDkJClkrRsd8ASw5ikWZm3JeLgCbhvz9KSoyarkl/BzWu/vxsBbzbiHTUodkCOGgOa4oYmRBfCvg1NG4v8bdRYnETMNzDPSY=,iv:n0LptclFSv6LhqUkVpZQBgu+fd9p6DUP+7VF8EM7h8U=,tag:ogtM/qEpP8+BBglFgbp7Sw==,type:str]",
		"pgp": null,
		"encrypted_regex": "^(data)$",
		"mac_only_encrypted": true,
		"version": "3.9.4"
	}
}