apiVersion: v1
kind: ConfigMap
metadata:
  name: icloud-docker-mu-config
  namespace: backup
data:
  config.yaml: ENC[AES256_GCM,data:mhyMENrKC9YfBDEeN3eVknEz4fKdklqnut85OgNdVbrxa9BCFtPzXRVcD3OdWAxvPOUAWCwztpk4yNUMm+rLxks/4BB0s+SrZRb0G545+v/lBsa1r8TQ7Fh42KITH7V2eQJR9MS//kpl6W97mGOmSKUhTY/LIiZjK6FJVhG2fjP8KauaBgSqPgXX/zgMvzY0xOc503jbzRkeeEIIyAO/I4Ssu80S4rPq9jedorHyVgTsk14nlYbwXrdggagV1i3sHDPUCkJ8LrUHbPd/pdikEF8B9E8qs9E4hHQzCtD6n7B3WgUEQYS5xk/xv82xRGp6mT1CPxdDWYGCQ7YeOqjmwawPtTxGQxk5wr639mo3ZpQdnLTv1M15hJh1EJEQuEFivpAFnkybpJsB/IbSCs/XuXquKAhhg0PSBgCyJ6Zprje59UfQzsQIZFZ5d97rhJ2A+v//9WjI/mGUhP9G8YqRlrjr9M3WeNAESwznmOfS2QgERVeaP/2nolt4rTwISzyub1AsJOLxIxGMGWO28W/jTvtz4lqtGF5KDLsluqAeoQx1LMRgO3CBhVLtCQ==,iv:PjIwmjIG0mpq4VBS9f1XcnmePsnosplmWvOgrtmX9s8=,tag:0R8xwqRZI8R3QQ59CWylCw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYmQ0a0E0a2FsSWpCNDNy
        VURyTnRkU3NadnNvVmFkT0ZyNGIyWm1pYUZnCnZWd0VPOWloMWlDTWNGV2VoVGhk
        SzhZNHo1TWp1TzlCMjZlOUlraTBLYmMKLS0tIER3T1Mrd3NPaTEvN3NDbzczdjBi
        QjA2anlpYVgyQ09CbUF3M2Ivc0JIeVEKV1ikuLDvp2YvsEL/iHJNH54QL58XQNpx
        SElIe6cXuFq7F3Dpbel2No9iU1OfeQgppdUBbJBH2MmHNP5Z8VlkEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T15:57:01Z"
  mac: ENC[AES256_GCM,data:kHSrnI2Q8YSX0Z7gZ9MkurY7iwciAdAwpVktFOWMCSH9MefvE1T66YfwQH00y5u30KzX96nPG7W0eKvaLUK5Y4FJDVKaskonv9fWcmbaE4aHwynqmZGjd4uqF8Z01SAf9l68JtNUry4UP/nJNC21tnBXZOz3azR2NZDw5JMjt6Y=,iv:ZK+A5P0xVPjmDblOh8HSG6Rj3BFeWIKos3FqRkS8u0Q=,tag:YgE796WvLGTiNjkVYMJ3vA==,type:str]
  pgp: []
  encrypted_regex: ^(data)$
  mac_only_encrypted: true
  version: 3.9.4
