apiVersion: v1
kind: ConfigMap
metadata:
  name: icloud-docker-mu-config
  namespace: backup
data:
  config.yaml: ENC[AES256_GCM,data:oMD/Uhqtcx34MY0ACOCo0E5NmGxjH7GlBCXFY9ooUCLoaqrXRqXk6jZ8z8+LHn+Pkd7MDzj593u/UaylxvcwhrzA0SBxja2xA3rmKbaAtGk04Wk0Ato9U6wSVzx6DNgoHzRBs1nkXdf3KMZxNOoQS2BKVrDgCof+JZbFfucHC/hS+VpC/cj0A8DLpo0ufObotTB7RSLqsBpusm9UBX++otL8IT8tHKoNCIInQ6T8NL+GBSZt9UOQaZR+mXOm2caLttMsbaxuBXctHsuuPBUVLbslzRrqLB4wr7lOO51KiKzWggbqKY2fzuFGSgECkQShmWWez/nJJd6dBLBILFpJkhONsXmqvKGQ4MSiQebiWQJrJks5gc5aAQRzZt8cuozketggqOC4ufPVWIKnCK3RCdQd0w9ZA2K0UhanUpQnNeIWT7TYbL04m5X8o8nhZGA5Oq4vCEkABpEg2QyiFAk8Q3BFrKwBGVT2awr7HZpe3570km5Q4sjE5Ag0gZmAOyk+xO4aB5I7zxCD3IptQ+UfFzvLR3j9GioX5kDvVTiZM/cyXokYfq8BU3Brqna9UnfbpOvOLyKll8uJ/YuOF69BFAvi3sxCmidAVgGPMIMoc0LVYH79oZlwXV/n8BgFmo4UBG7GY7Z4/9AriMb9WdHZh9cwvEN7O2lWbeJ7rZXTDE6YfYxLQ1M3p61pDxXEAP/7,iv:934xrUqF1asZCKG9fhA9a4pGUQAJPzEtM+AHu7IkD3U=,tag:qkOPQH1bTMl/1UyIM+To+A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ0xrNzlGSlBLbHArVWVa
        d3JzV1RJQTl6QktJVjUxTXphV3g0UTBWUG1vCmE2Zmp2aG53akcrdyt0VHFVakdS
        bmhnZ0FIblJUUTRtRldRZVVEakh5aDgKLS0tIHU1TGYrNjdlMEhJcCtzYTZ2cURP
        cnY5Y1J2SGxCalNORFJZR1k5MTFxNG8KBGobb1m0QtBZFqG+eGq3w71I/gztT6rt
        3+vZLDI7yo++WMGoPtaktvWzFQs9MbXcK7nAN9VmlaWui2BPKLoxJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T16:49:54Z"
  mac: ENC[AES256_GCM,data:14tHirAiHvR+zr4mXIp378fa6pbhWseBJgNUfNlWpwWmmEG1pdlfYQQxg7OFE3I+E+VpUPIeoJ45ZIDr4zcXDawxoO7jXpTuUyd8F57sYcoJyc3C+LJwjOysZvOzb6MToL/hvUqIaNXAl02YCQs2QEn7ViNODu1U6e8WgHG3KeM=,iv:8yyKzSW35lpZF4SQqhOVx1kUfj4SXQxI5KYZ0fx2tCY=,tag:VOXCdBGNr0teym5d2f4c6g==,type:str]
  pgp: []
  encrypted_regex: ^(data)$
  mac_only_encrypted: true
  version: 3.9.4
