apiVersion: v1
kind: Secret
metadata:
  name: icloud-docker-mu-secrets
  namespace: backup
type: Opaque
stringData:
  SECRET_ICLOUD_USERNAME: ENC[AES256_GCM,data:bQolByeyDeIUSNz8H1kgYGE=,iv:pv+rIXVq3GTE7YxGIuHd1ii4aF2PFhljr6pWaTr2z0A=,tag:dGoqtso6BfeLkHqhuzgp+w==,type:str]
  SECRET_ICLOUD_PASSWORD: ENC[AES256_GCM,data:eUvTw512aqd/8tjdtUY1ldI5NILh9Zs4Ho6Shw==,iv:I/3nExXgp9I/8/IO4wwHty2MXEjKT/7lem6rtMsRwns=,tag:+Y3fbJF3edAQ+CCps/VJ7A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOFlvc1htQmNNSVhRWk4v
        TlBnblhZM25ZN3QwQm1jZDh3cUIvd2Z4dXpJClQ3Q2Q3YjNHOVM2VnpORGRzbTR2
        ODFpRmpVUUJmbVBjTjUwYVNKR1NiNlEKLS0tIExJbi9yaWduaUp2aHkvbjNVWWcz
        U2dHckgxYlhvcXdkV09vN3JteXRoQzQKjN1rdoRuKXO6bf46lpyEjoL5W6SNs8y/
        VFQe2cCzukKEdRQDhXAavUd0iUuaz+NwNgsxeq3OXqKDTY6Rvyw/Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T15:37:41Z"
  mac: ENC[AES256_GCM,data:UmHFgZA36s1GeBSJA2V/hSB5JfkvO0ZR52M54LCbKlwuObNYzxVkWlQwFBtbVROiQ1qfEHWUucdMqN5dZpIs0J6hk6hAT7b31nfKReJSAOYi84RRPbHSzsDw/2EJG79aDWyntZM5mRk3hPo5Y2xTjSu/yrqEqcL4W99o98TJKAg=,iv:n/Q4eHF1EMFPLR+XQljeABlSDRwuyoOeqqdS+FdS7jY=,tag:evj2u/IbKykhUbyYfRj8ew==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
