apiVersion: v1
kind: Secret
metadata:
  name: icloud-docker-mu-secrets
  namespace: backup
type: Opaque
stringData:
  SECRET_ICLOUD_USERNAME: ENC[AES256_GCM,data:MLOcKjyOPHAIaaGqcVfUukU=,iv:++CrStA4waW7xmUhQQBOcjgiRe6SdShk1H+blssE2zE=,tag:V04DADcZAoFOgcchCIDHOw==,type:str]
  SECRET_ICLOUD_PASSWORD: ENC[AES256_GCM,data:D6BV4NGzbGE=,iv:Pj1PDAMqMaRg8xVaBOYyhNeRuyo5wM9brTUR8wMMT4I=,tag:5EZJodat9qqR70ubrvCnNw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VXdtYVNpRjcra1ZFZFNr
        Q3ptRGhPcCtBTnFnWEFzQ0hZcEVWQ0VZR3dzClltSXdGcU9ZZXZyQk9kTXZVak1r
        ajFaL2RhU25MWUE3RVQ2YkNESzV0ak0KLS0tIEx5VitaOHp5aFFhcExuNmdvdUE2
        RDgvdEhVLzNJdnM4bC9jMWwyVTMvVmcKFastzfBu3hMFJQX3qy9SKDHSR6F2xcvi
        iBABUVXTou+hAtrXyNhpkXaftQvIe+e8bZUlllrgEzOAv2HKoYQSiw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T16:29:24Z"
  mac: ENC[AES256_GCM,data:dY1RQiaVLya8R4DM277G+WfoNHYhEhqBholhY5BJ2oGmE9TbeRCGZtSra6YgSFCc49vJJQrNsh5BrdP316akRIOTgHvG7UZYt5fU2lDbsUMtWta5Ss/jzPcDcoj8O6Pggo51kP9XztCbXPVmzSiDjvGznE+o6N5o3VnMjUMdyZg=,iv:7sQB/GrelXGXRkfnTXdsaz4GP3EKzHTQ4/YJZi7XJNo=,tag:02pgKp4GZycJ5moccynkNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
