{
	"data": "ENC[AES256_GCM,data:8GDPVOGVO9tlVyl0uBqOnZ8EVei1GcoYkV1SKDBcUc/wvbJOu5gLfsL5ohYm5W9KzxYG0MW5pmZbgcLv1Kp6A9LHly31n6NHpTQ4zwIXWmU4+0B2pkx4gBo/T88y8A5tlR/A4rE4U9RgFjqBGduFTBrVMxnsLstMDub+POUA356Hn5pdbhl64SunCCYP8KVdZn41SgevMPNX5GyR3N/KPqCww9L0Y9xiRlyuBCEIWBJKPFpihNrZyxznBWJe6cpOYnys,iv:0whvB6HA3D4F3Q5YGsStY3zCMn04j/YdPUpez5aeDpI=,tag:zX2Obl3hzM3ExGlbGH9wMA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeE5jek55dlg3TkZyRUJq\nQzhKVDRYdkl5WDJ4dHNqYkFoSDE3S2ZORWhFCllDZ1JMVmZBL1BsTmNJemE3VHly\nWFlDcktrSEd6cWFXdSs5Q2VmV3hXdVUKLS0tIGUwQUdoMnNKSVZHa1JJT3hqenBK\nTVA1K0xKQnZ2eWo2NEVqKzFraHNqV2MKffOU7q+a3KkuU0ZySo26EtgdHlJ909ZP\nFSq0mPzrg5MyaGexqiqCzRDsOIJ++JoZhfIsuu28wcd8WXOUk2S5Mg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-11-15T16:20:33Z",
		"mac": "ENC[AES256_GCM,data:uqk708zvVxcm8QEuQ3kDWbPj52RlEHOKa6U7hG5/T25IijzQBXftXrcfJZ66X/pIiDY2EPt+WVKi7R2n0vLaV+MnTGARjUmawsbsrL8CrMNgrjO3zNSL5sEL3En+LDjHdU9+TXxhudpBQ8UOM5wISflH6PqdlB8/q40/Uig17Q8=,iv:l2s1K5swBGGi/0N+JD1wIU8xv8+g/8h1jLdj+scyhmc=,tag:RGuWSSriqwaaPTmx890Cfw==,type:str]",
		"pgp": null,
		"encrypted_regex": "^(data|stringData)$",
		"mac_only_encrypted": true,
		"version": "3.9.4"
	}
}