---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  # - ./pvc.yaml  # Temporarily removed for RWXâ†’RWO migration
  - ./helmrelease.yaml
  - ./ingress.yaml
  - ./authentik-outpost-ingress.yaml
  - ./secret.sops.yaml

