apiVersion: v1
kind: Secret
metadata:
  name: apm-secrets
  namespace: monitoring
type: Opaque
stringData:
  apm_secret_token: ENC[AES256_GCM,data:7Db4Gys17SqXAad+Kf9kq/LR7H9xtTjLllDcve3saxKq87kN0X/JJkg14K0=,iv:XPVf8njcVpX9yXJctoGIz6SPdk8tUvvdVgxqLQQ9aOA=,tag:MQa7b3Ev/zPDHIh4AAS5EA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMFh6VDAxTFUvUmRLM0NN
        aVh6YXlFMU9laTdnZ2dndWZnS29LZS9zRXpzCkM2OWQ5b3JpM2F5dzFodDFkam9m
        K3ZuK2VMNjVyeStmSUNXZnl6NUMzOEkKLS0tIDV6SU9hbW9HSzJzNnRncDQ5cFA0
        Z2wyY1RDY1VKVDFFcHFXdEhieGxiWDAKMEL6qX3saNYbh6UaKVcnfM+iypMzOWG7
        aZ7iMH3hZCYL0r058i8Hvue7e8qPqt9xvpjXUyToxk7W6gGZ21osRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T22:35:48Z"
  mac: ENC[AES256_GCM,data:uRUuWiMHpvPeH5Xt3Fd2goF3hK98HI7SrmdXZL3AAqnnPie+IsHtUHcgGNeBHOP0A/i2qREucP3Jjn8vL4plXEKQmlpsogKSuTfnrZqo/Rua8JMC7Ypd2LGWmifV1ch6mRlcQJ0Ffv1cAieEDJ2VnvjU/eA/RRBHFGl6SXPA2qs=,iv:0wuvP18MDHikIG/qI2x63K7ATzxTVQ27iBrNvGEX5Xg=,tag:fkzWq71igI+CH+DSUursDw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
