apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: office
stringData:
  admin-token: ENC[AES256_GCM,data:37/4WVg3K7JCr2dHJjVarZPHA05k+hJTAdK/OEVZDX6jS651gaXvUj1hQEk2SlUJxIJBdX2/WazYSWWB1GB2IPXMgaZEcQvxeL2i23N62RsecvE/ZcJX,iv:4p2z+NUua019jedBzFr6i44TgCyvA1yWmsxHxGWclZI=,tag:tOw5UVn+otFbzgUBNLdd+g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4clVOZEswQm41cTluRTRv
        WHVrSlRGUEtYcXh5MGdYSVJGd29JanA0SFVjCld5NEJZdlNiOU9DZ01IVEloUlhW
        c1J5WXp1TitRcjZKbWVZSVFyN1gyT1kKLS0tIFJ1M2xQZDI4UkRQaTQvbTl3Ynk3
        TFcxMW9TcFQ1eWo3T0N5bVBXMkRlc1EKYMNnCTSgvbdkSlcT3xN1MJz5OLEoaASS
        heOosmQxUHyFTTwdCQPYl5yJUn2cPle4qUA41SQG8o4L+h7VUBl3lQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T21:39:16Z"
  mac: ENC[AES256_GCM,data:KBKv6fuGDBsOhEji8eP1M1XeuGpKufawvuZh0KfqJbXFlp6Wv4DUELYtU05t7D5xgkojIJdtnSn+tOaQY1d/nxVjvp125Q9hRgcvlTAG8mdkUdnOtTF/FvLJSEMiXheTuJRS6SLj0AfOn0vfS6WUYexrM/FschiMibOL/V+SwFw=,iv:aBHxG59//Bq6SU7UvFtcj8MHo0tt2npI993JkibAtK4=,tag:Xa4Zje5sRALSPHFNd190ZA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
