apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: office
stringData:
  admin-token: ENC[AES256_GCM,data:MKHgmSIIQV8Vc+/tEa23QuG/m9zapOQKUCt50LA/jbFScSfd8r6aCZcO6HrLPFPXJrwZmqrcfIn8nOseSA19hQ==,iv:YuL+zUgM+YbQkWwBzTR5gqc8Py/uOAZV24pCYcczuAQ=,tag:EJeT+5N8TVs8Tqh5zK1jJQ==,type:str]
  smtp-username: ENC[AES256_GCM,data:NDzUCr8mnLfc6vIyXzjBSAkCbHtT,iv:sVaF7+SWCN8yTGoEVIWdn6zUMR3ieqLUJd2msr2II3s=,tag:/k3MEQxL1oIiZrhkc6CPUg==,type:str]
  smtp-password: ENC[AES256_GCM,data:xxrjQhqOjPmpCkGtcnPEsjNm1tfIfUAHroeCsA==,iv:lL5yg+t/auEFvuOeT3NruyV1fWPVnfjR6+cikKfnywo=,tag:my4DojjScRuphMo59pW1KA==,type:str]
  smtp-from: ENC[AES256_GCM,data:CmI2E2rgSw9YO9BxAc+8GdjziFGa,iv:dyJXG5HlZz2A760eO8eTxKhkCtN/frKet8bgcnDWqrc=,tag:ou1XHFXme63ylab/FUnw9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUmZKdGpDYW9RVHRiMm45
        V3NqTDVwVWNvNnVLbStqa3pkV0Z5bEV2bUhzCmNIR0tBZHNIREU3c3AxUldmMHVh
        UUl1UTZZWkZLeFpyOE5xdzkxSjRaWWMKLS0tIDJyamVZVVgzOGxxajBmWE1oK1Vr
        WUNuSlRkKzNSOHVJbnR4ZVBxdk1JT00KXO0mH9enewj+Mh1eDX2UZEMkXlAjea6L
        DG5InBW1CZBJYikLmDZWUfTBiVhPlGnSdJuaWtyqBpimKWah3Fo3Hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T21:45:18Z"
  mac: ENC[AES256_GCM,data:/JO719/6sKdnczNbGunzIkZy+jLYB0kbeMg4s+J/BSROeceMuZIlMJqMuEETxqJF+EyaE3dvAjAWhUAxILcK8tBgcX+5FrWgWuFKe0jO6877AlvAXisX6x6mufh7n9Mth3tAxV0zx0KRZ+KPyVyVf0JLr1m5tOlL3V/Dlp5PB3c=,iv:Vh/ngUlOePcVQ6BseuMj+8s5uthXaep2S1YqW6L2fVA=,tag:2IG1HBlTzYtUdbSON0DxXA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
