apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: office
stringData:
  admin-token: ENC[AES256_GCM,data:1oZuLxFbaKnIAxZREE3XahcCrSY3aXKIJ8V5TJkSZNoMcVc5+6eAXOVHqOi84Lyv1qD9csK/11PS8+V5wavBuH9u6K2PkMbxchrkof3q1dcuqk3BJQZ5,iv:cY+fM4PvPnkx4Kn+xoH3A5HoJ67x/vYlBPvhlIAttlA=,tag:sl/TjuAbFEhziwD9WtUFqg==,type:str]
  smtp-username: ENC[AES256_GCM,data:WDnFtlSW+UqD/uSr1RsrPl/UusV6,iv:K7fYa8yX9S4J6/8TM/NKBG+l68KQC7OLMDSVGh41WcQ=,tag:W5XiMwK60uCy6FgZC8zv0g==,type:str]
  smtp-password: ENC[AES256_GCM,data:q9cVG5DnG5QMj5JC7bL1IQUjDd0mHiIRfdY2pQ==,iv:I0MSi82imdCMwK1kgG1gxK9QWnyxAd6C3Jo2+nrRgAU=,tag:oomJUwcnCL+KdKXcCoVstg==,type:str]
  smtp-from: ENC[AES256_GCM,data:4PRofl2dHQvSB+pUIq47N238dFVq,iv:gc7quIO0X9rCy6DyZtRI4gWDTqlY9ArEvpzjhi+mhwI=,tag:GU5ITzQV3bmWwGs8UH8SHw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NFp1dzJ2aGhqdnhLR1lY
        VFAxZTZYb3ZiamVQeW1Odm5ob1crL1lEQkQ4CkRLWWpzU3NEWXp5SVpVNG1TY0hY
        dGdyMlNzOVVWNEFwZkY4V05HU0tBVkEKLS0tIGFYWTlkbmJnK2luYlhUbUxDS3hS
        ellPbU1iOWRpUlpTQXA4cEQ0dS9IUDQKe/l+IkoPif3Ii0klLyw7OuWPzRnQ5D89
        XjG6lfNDkVtjqQkAOYGQDuZuJm6TQfftuJhWhaUY0txD0Va5QZLqVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T21:43:00Z"
  mac: ENC[AES256_GCM,data:dumvCSaySlaQEoOJt467MTmprtBIk49IuAbjv8mqNRBVTwFLn+7AtqCbCyj/s/dXCIf1PHQyqr9T0SK4hNzAm9nvf7rjj/p+p6Ikri2ya8YiDW1bY9gMv7ZfTCQycMlPzXDUrnQsbScLRf8+/9JiHfdFMqdFWS7MpZsUOALFByg=,iv:zJDwrfa48Ua9OOMm84a9BVn1/CeQBb04IEhNOrvWUUg=,tag:6KWlREp/gszWW5HXzQaIAg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
