apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: office
stringData:
  admin-token: ENC[AES256_GCM,data:+PiGKiqydAa8BkWBS2elXZXa6JAMnrYY7zpfbbByx99mmvrDhxyhtsbML9qptUux88k4hJUmXKsJ0w6cBJkKPg==,iv:+BS4QaV5bpn5wBITUjdsjsgtM42T9gJQzb3aSCgOC+E=,tag:py61pKDUbXALRid0iuwb/A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDKzZJSlNldU9VS0dhbWF4
        RkZSQ0R4TjhOaURaZWRabFhHN2I2dEJ4dGd3Clh4Y2xmUjM1R2Y5Y1pCSXYxN2Vq
        OGZhMG9WZVdhRDNSb05BNll5Wjd3bUUKLS0tIEEzL0xIcFdVcTgwazVWSkFuMXlV
        Qzk1R0VNT0F1WHBEUkZZWjRXaWxNZG8KdHx6BxfLa6SrYDeb6jXcajOtBEkN2Jic
        PRO6oEkbeRTrMQz4X6nezOBmhmoiNrflznZbsAmQtbVa3MlMvNbL8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T20:57:56Z"
  mac: ENC[AES256_GCM,data:Gxm/cASShbpm7diyBE6eesGAZS+BUoyOa7FKIZxDzZIUTEIm2tgAwKGUa2ZAsIjYH8ArPIx7HU4Hds6+lZ/5S2DKPVZsOuS0OQ1t++3/379bVs6E7ZCV+NQxWVYVE4PihUerZc0zXaH/sVNbZNFxQGYvY4A6yzdAC3370IU5+YI=,iv:S3sLlbqGgxYc2/yZOB1EEw4a1Ohb0hgP4jvw2e0EhWc=,tag:e56rw5NxFjR1aSpNrJz2kw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
