apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: office
stringData:
  admin-token: ENC[AES256_GCM,data:/4RijI3hVFy+NE8jhUNknuin2qHkSsSWXHHm52WHxV4wxvE/+vPSsOw0ZWbg2nh5gBRSQfXrdUx0Va8sEjHeY8EiUa4bqdZCjNpWAEpZDuA1a3YbzSab,iv:MGNdlezFqABh8y9aPcoNtb097OidD6lybjBb34A/4No=,tag:n68eEyO9lnbIrGX6mE8nUg==,type:str]
  smtp-username: ENC[AES256_GCM,data:rlDMv8NuTC2a2wSoZvKjTpmHWhOH,iv:nFHG7FOGgr1M84zJI/aWcczvG3MjuLQCW/IemHBeABY=,tag:tS6Pas6XEqeeWHJ/X/NOPg==,type:str]
  smtp-password: ENC[AES256_GCM,data:PlYMbhrHa6BtN90IRmIHA048NI5JWvig3Jluow==,iv:AevOwddBh9H2yOHjXhimml51NnvfvynVSSIg+x5y/eI=,tag:Aetmi78L5XfUrMlylgb+bA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaWtEOGdjNW0xZHF6eU13
        VW1NMDQzcmxRUm1EK21PYlJyRlpkeW1sQ3lRCndLekIyRkdMUnIxVDV0MGtMcDZX
        ejNYQlpmNHhTU2NiZDZVa1VHcGpLelkKLS0tIHoza1dTMTZsSm81bHJ1YmpQVzZQ
        Wkc3RVBKRXZsb0pRTHJsdnFMNS9jeWcKCy4edmP2CC6x0Barn/00ghAXiqX7q1vW
        k0UavLuvUix2lSQs7caOfZDI4mScfohzgeGCNP3zJzdfAKA7vdoElA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T21:41:46Z"
  mac: ENC[AES256_GCM,data:G4LLBLMqI8AVrys2JTAz8pfSm7y807greaF5lREzzfPIClZUjRC6iX8RhXIewdgMCTegYeOSp5SaZ3JPFDEGG9212ZZvMc9phwjyfwkhiol7BUHtPMD68zRwlDi+zltB1KyJPsWEBdXKGJApLIpBcTn8KtSW8s80+g5cxyjuzZ8=,iv:9H0olPDshNkicgsodoqVKAaEsCDMYfITPHce7Lp73ls=,tag:gDBsJZMORqFNwqmco6VhVQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
