---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./storageclass.yaml
  - ./helmrelease.yaml
  - ./service-auth.yaml
  - ./ingress.yaml
  - ./authentik-outpost-ingress.yaml
  - ./configmap.sops.yaml
  - ./secret.sops.yaml