apiVersion: v1
kind: Secret
metadata:
  name: frigate-rtsp-credentials
  namespace: home-automation
stringData:
  FRIGATE_RTSP_USER: ENC[AES256_GCM,data:iR7JbD8=,iv:/H8AFPcVSoYIArGfVdPjrLlBl3lPraWaW9ywZN8fZfc=,tag:+FmhfAj9jgScmUhqlI+liw==,type:str]
  FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:ixTa0Uw=,iv:DcNFksEijFTMdUpXLmP+CK+KQT7jvLmIjvy7YRyaxmE=,tag:d6v5W2noSYnmwSj73OQDHQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQmJlakRYS2xvNUlUQzJW
        Z0lMbGYwY2VGYkEzNjZSRzc4dzdYM2JVVUdVCkNvd2FTK2NMci9ydmRCRG5KOEFt
        YUQ4cU9iN0FPZzFlZEtSNHlCRWdFMncKLS0tIEZZZWRGd205MWJ0TS9LV2VoaXc1
        OTFHcHdlYzdGYnEveFFTZXQ3OXdJNzQKlAtlP4S6QAk6QdmPI46b0n90sEjX02Xq
        FLGewUc9s7kLxCTofl2sau94HDlFL1rYe7bMuo9w7kZmcPRXYR0bdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-15T19:41:49Z"
  mac: ENC[AES256_GCM,data:D7RJ1Ji+HmEiWyFYNQfjRpuSZwn9fVsml0PF/Rw7A5H4V+tyKzT/VwbZj470zJxdhC4prs5/nyDgwXocfSPPVt5r2r1gefA0NvVVS2H6tKisFCPIZfYUS546HPi7IRzA6ciuAAV2aEmI2pZkwOHvGPAG5587Iii/cW+Ij/73RIA=,iv:dm8Upi44YYEzcgv4EumHYV0iNH4TSDE/4c6hikTb2fk=,tag:loydgsr8payLaqKdn8Zpsg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
