apiVersion: v1
kind: Secret
metadata:
  name: frigate-rtsp-credentials
  namespace: home-automation
stringData:
  FRIGATE_RTSP_USER: ENC[AES256_GCM,data:BABFZVU=,iv:khdgnIlmIzHkuLkScfGWSGtD+gOVnyqnJMs/j0yj1mA=,tag:UIKIkjEzNDvPhLh7GFboqA==,type:str]
  FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:rQ/vR0I=,iv:wPr4L7jJzGf+R3W38TjEqZcSzgRBi3C8u4U3UsWWWCQ=,tag:i1cUo9zeVPWPg2Rodx0QrA==,type:str]
  FRIGATE_AUTH_SECRET: ENC[AES256_GCM,data:3kK1eRhl7muGQSN308bWfvEqqVW21eY+Sc1w+rzpOKRyCn5LDmWaZCK/pUa3S1eXX979BB3cK7xmrCWTFuJTGU8I06Ec0wzfQBifik1vaDaOLfPr1G1ShZEXMcdcbrDomPztk0k7lmtFe8LbC4XrliFxwC83RtSDqFU3C+pRO5w=,iv:5eeC+qV7Wf997S2iM9icZV0a0tUB8x//jwg0CHrbRBc=,tag:IC/IxeccnyyUyTQz9NmW9w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDLzRmYkt1N1FkblZGWUNO
        VUg2LzJud2pNTHY5aGdncnlzMmNkbG9xMTNBClJtaGRVaUI3QTNPYVhTdmcwanJV
        Und5TmYxbjVINml5b2dkY3YyUHdSN00KLS0tIFdSVDBqamxXRjJ4dDZNdmRKRWRx
        N2JmYjRPZ29LUHdJZjZNUG5XeGttOVUKj9TFXAN6ZlN0KtjV7EOqPLpt2Kd1vpDD
        viD1uHhZbXFlWqJDhs9vnE4cIR/R6751zet0FM5WJ9W4hIUjURH1Mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T08:39:32Z"
  mac: ENC[AES256_GCM,data:fgJ8JKjb8CmuVfkd1cOrPr6HLPkpXpZaFeQHXeso0IXRiCheCsSoQnssAMIJICjDD8h0eT8iM5Na3AI1kuLOn3YshG1n8w9XGbKTxAUD+B6h6t2GwkINsBzyxhYbpkH/0EfAIYSUauGQpAn1Z+zoEJm/LlzWESkPsFptf+8Tw44=,iv:JX/q+ok4B/6/GmOZI3dDUcdTH4MWovI5qzE05JzbfdE=,tag:NFC1dECX+1FwqQXMEODDOQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
