---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn-volume.yaml
  - pv.yaml
  - data-pvc.yaml
  - init-configmap.yaml
  - secret.sops.yaml
  - deployment.yaml
  - ingress.yaml
