apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: databases
type: Opaque
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:zj8Cmf8rmXJt5IWNZCtCIS9+wh9wdlVRJg==,iv:8X3TvQRcIYSXXpaGyuTmZSJM63f9arohb6BaDHyZ47w=,tag:l+znYdN2XMQiWkcCRzdkzQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:1eVDGBXvfJA=,iv:12SwG1BJMIseTV92RxURSZtd5oIiWuVMF/g2/aH6azw=,tag:kXFVSQg1hZJRyqXEfKJrng==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:uB7g+4bAQt0=,iv:pe/zGLt3ctMNm03UW9ZJZZejP6u0CXZBrkHMrqyun10=,tag:9HZUMkxCxJwN8NjsTQEMKg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbVoyMXVDdm1zWEhEZmxT
        bWFCMzgzdXlUNjY4cGhPT3Y5dk15UjFOVTFzCnZobUNTd0tNOE5kT3h5RmpERFlH
        RHgrVVU5bTJzNkNBcloyMUYzd2F1d0EKLS0tICtXeHhHcXZsbGJLWTJqckZEZWt2
        YU9DUTRrb0pQamtQQzZnUG5OQy9ZVjgKDaNCH5wqCVjdDtOXej4AMG8RHMrGZwmx
        mZ9sNp6oCVV2PHithT3xNKUcIQeXS6K20zFTAYPPfU4JUVPLDqat9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T08:21:51Z"
  mac: ENC[AES256_GCM,data:MIg1GObKuFKb8B/jIK3g0RZU/LN2BhuHWlg3QWPAAdKey8ga1IwzphDjTp+yR97XirhiQEdI9CnlRwCDzlHdivXW7PlwL8hl7/yzzNoEf8RpVDseRNBH/6g8yTR0P8irp3WhgE6+ufg7BCqgPA6DlGmJbdLR9swVTJS1OwE8Zps=,iv:/fzLQj8UTKQCNslRXKSDpbKrxXhgZhBkDUvSbxMYEUQ=,tag:nfa5fpRmWFrhsGD/f1DMFA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
