---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-code-production
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - ghcr-secret.sops.yaml
  - image-automation.yaml
  - pvc.yaml
