apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:9Nj1dNiz6EXgW2irWDxajlIlDA7VAqUC1QOBSQiYVQ2HrH+a0kDR4zeosUTDcpNrtrSqDKun55JxBDqsrQh8ggG6JovMVSirDwuY0eJFKX30ACNaE0DGU57ZkmUt8OxKdNtgjXCcyRV6FqvVz7sgVsotqH3SLUWPYkwzsa3aaqyoS1tzrHwSKGCsMII=,iv:4blL6wELF7cKWhNzRfQ0z6NF0Ox/yX51/SNjv/98c/s=,tag:V0F1gjOaUejm6QZocopDrw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Ry9FMGJyaDNMR3YxUkV6
        S3pTWHEydkxjQzQxV3lrdUYvZE1MYXFDd0hBCkc1TUtFQXhuZ1JQV1ZHbkxYcWpH
        SGtPQS9VZDFUa3Azb3JJRXBTbUozWVkKLS0tIDMweWNqQlB5d1VhV1lLZVFDcmpY
        YU42NUFmWnZDd2lZV1EvMWdaQlA4c3MK7C1p+PK6o4kuDQlgm0EU+UkNxEFyU3Me
        6Hrb+47htN3lQ4cQhSCbuozmPbxCeNVXpY7dbkox27kkbBRaWYVVnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T11:55:02Z"
  mac: ENC[AES256_GCM,data:v7JOn32Hxb0bhnV17vxwZ7qxQSRUqzZSGiZzqxmylQpnrtwpyiQH8tVpyg1t3TdpAxMz6WLDtN37ItFbKxBTSlxtNe90mjo6jKYzVBaCjfvRdXQbVaZmuL1eL5DDzIljefC6VFJYb2U3vms0MtC9JFOjrWEr2eeKNUgzxsJtciA=,iv:HJZZLFftZ1pAe7cj1ddxZUZ/WmmNXLoCbRhhTv0cGZE=,tag:Jjqe/XjsBWECCMYvmAnPzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
