apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:IawquwRiy7IQ5myKfOUkBjO4Oyg8ka1n3iPq8FB+1V8F21potepDDpz98G0ZLOL8NaXWbDjJg729rTwldO5dt6Fnlk0oSYA/kogEbydCHX6iy8Grb19bWTnc0Cb5YD+QRFGQaMN3aSojHPRTNW4QAnHzrlKSNKuRBvp4ehPkA9XXk4q77fQ9Eo3wi5E=,iv:UW+trxOscVtZJd8NMTQcKQ/dP6UzInolFU5Y8HpjvqM=,tag:qG1gpM28ChGrUt4D/k0MZg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUDBoRkdiS1ZSUUZ6aGYv
        ZjhFSDRiMGZSQVRYb2U0VTl6ZFlOeEtOWEd3CmtkbTZVUVJNRllrZTIzSWZORy9L
        dWQzNW1NcjRjRVVpRis1VmF2ajJIUVEKLS0tIFo3TytIbEJKRFN4VTJHZEhPOXla
        MlYwU2JuajhHazZvTy9ZUjVTa2hQZWsK6uSjqxChG6KW1PexkqRrrcpqfhv5anw3
        Mcn5FipbGkDrUNXUgV676UFVgxS1yJxoukewtYbpgsURyCjpkRVpxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T22:48:33Z"
  mac: ENC[AES256_GCM,data:Fhf2nm/l1q0w43ubKixG8d6DmAJjj/h14sYYxHzwuyejFDI8bRK9IZ08F5zEh/aTFn1DL/w/4/sb0xV8dNweS7iyNaDGPwT13Lf2pvz9RkUt51cevBwxc2r7vwSZe2+TR49L056fVmQiuXx4eTDKjnXZ18IMkXVTO2Q1/FAXDrw=,iv:OhQVPEFEz75D9TWN2Mbn6c5AGk1ESgVIBXK31FZ0BWc=,tag:N+NDxjQUy4REhACPOOUg5g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
