apiVersion: v1
kind: Secret
metadata:
  name: opencode-andreamosteller-secrets
stringData:
  GH_TOKEN: ENC[AES256_GCM,data:kb4XZvVTErZDLBcYRN59cEX3sIBMzK6iOELDZ3L3Rs4oHIvXFQ7N1A==,iv:SXfRraDGo65FAqLACiWIhtnpPFE98Fj0rRAeifT9Vlg=,tag:4crRTVg5s0duMNXNGEUQtQ==,type:str]
  REPO_NAME: ENC[AES256_GCM,data:ybxZeDxkRsOIVcXdGJglufAjJDX7ciCRahZcGbLMyGD/,iv:9Yt7AkfHh32GOsILzqGLqjd1ijDPFEr3DHa4opBL5b8=,tag:KFRFJ+Jzk7TV+Tzx7YbfaA==,type:str]
  OPENCODE_SERVER_PASSWORD: ENC[AES256_GCM,data:9Axa9knEstgOgBCBTCCqmlC2osfF/nGJVtc7sZDO,iv:eaF+E+IYRgKeUZQ0th6SG8at9YdY9V8AqMfNiGJx2cg=,tag:ThSBJl6ThiKjr1vHXHjaBA==,type:str]
  OPENCODE_SERVER_USERNAME: ENC[AES256_GCM,data:WuexYpVulrE=,iv:J566P6zogXRs4O/PBJg0Gj7tsdK1Vv1Rtw//VVpzA3Y=,tag:lyFS0LjNo0q8Is155bUn4g==,type:str]
  ANTHROPIC_API_KEY: ""
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  DEV_SERVER_CMD: ENC[AES256_GCM,data:Oq26OnaFtpXAirjVFAJMoi+qBvGPu1IqLUw8,iv:NTqUW5Uz/ebuNklA3JS98sdkPuiHNX1mZsvDt4WvxlI=,tag:FrTR/YwJThMaci/msNHkrA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMFVvQU1xK3g5RXV6ZTlv
        WG9Pb3J3ODRoMzdlanZIOHpseUliNHdLQmpzCllTMm5HTjI3SEE2azlZWlRrMWg1
        aGRKYXRzUm9GTDRTUFNBWFFoWkZSNjAKLS0tIHhyTjdYYTc1QUVWbG40WHpNcExr
        V2o3YjcvM1oyRnFCTitqa3I0dXVmZXcKeVcWmgNYXvrX/0QG9H3KMXWI8VLRZDFQ
        Y8n9Qzg4LpxBQcSBKITtf2dQRzAft+B3Ns0oUxzqvteEp/uBD+fZJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T22:52:22Z"
  mac: ENC[AES256_GCM,data:or7RZEHpTSka/5uhEQJB6sgX+wfT9ItLMlg7/MZnsDRDD3ahGgWJBYFr5O+mmOpc0Qocp02m5BRECHff2E4nZK6XL81saHLZ8TIn00t17doAW3DrxwduVezRNl8X1LB4H8jSJmprNorJqSwCUC7GFZG8faCWBrDMsijUgnY4iDM=,iv:SyjnaAbYHjvaOC9Iw6aamcTTQ2kLcGhs2f1qH1leb5Q=,tag:CWdPQTEXMrNtBX8N3f7wWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
