---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-recurringjobs
  namespace: storage
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: longhorn-recurringjobs
  dependsOn:
    - name: longhorn
  interval: 30m
  path: ./kubernetes/apps/storage/longhorn/recurringjobs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage
  wait: true
