---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - pvc.yaml
  - secret.sops.yaml
  - helmrelease.yaml
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: penpot
