apiVersion: v1
kind: Secret
metadata:
  name: penpot-secret
  namespace: office
stringData:
  PENPOT_SECRET_KEY: ENC[AES256_GCM,data:Td/jmMksl9WMFaonbSk8QmaK2AvfxnI2/E/kqH3ABJw10ngE8XHmULI368NF9OKZMs1mKfnjIewXLUOSgEz5y4fHBXTJsqKR2Pd7KSKsk3W6LapEh50=,iv:4o+wxYEDtiyOchadBHDEnXk1FAvZTB5YSr9RtKe2Y0M=,tag:UWo4leUCZXDTH19KiuCPFA==,type:str]
  PENPOT_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:VhaTVV0BaFFT04xjuXlVECSXvrZJhZGVBvKUG6BjVUPxWoX54V0MD33Fmw==,iv:DE45PO+xopQ/po4+XLnADu1BnJs0pCr81iDFs0oyv7g=,tag:8wCt9DNAwHuGSOB56zU4Yg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMDZNck0zYkJ6NHNQME5C
        eDhvVHhKTXZMeTZlVnZMQ0ViclpKcURNQVNzClp5OUJjVkdSL2ZDbzRXSjNXdmtz
        OEMvY0gvcWpxM0tPb2FGekgyMTg5RkkKLS0tIEo0Z0F1Y3pPTkJGOE5FOEMvek1i
        VUxoMGlxRm9hUGRrWVRtRWdGL0lxc0UK1m9CQfAiMZ8I3XCe+XAdwZKbMqApOB4n
        g1j88CbTDdq+MONwPharrpfoWVusJIr6046MfT2UCal/rOUUqRK7OA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T19:22:52Z"
  mac: ENC[AES256_GCM,data:AmY/cOgd4aoEn+w/uvTc2pJm1ZVjRWEiXlfFzVGag40YMrUIAVzEAPp5qwdFpBeI89IHNGsNVa2yFdDE4c/dO0RYJQtq7/6K+xGCw1PrYd5TZdxcw86gX+SA+SAs+63z05vT0AX+ZgGz3ttTZK3hFHTuNIBM7/F4pCaYjwZ1NHo=,iv:0UuShO6S44dTL04MXBjjbD7NifieuTBfMvIN40EJ6/k=,tag:OVQmgGO2w+phEHF61w88bg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
