apiVersion: v1
kind: Secret
metadata:
  name: penpot-secret
  namespace: office
stringData:
  PENPOT_SECRET_KEY: ENC[AES256_GCM,data:PwA3wyPY4bbFk2PSkXv16D1GDT0wa41aVu2D0JlBLHqzrV6baNPnhL3A9Ll2JbpA3lmFUfKDueQMO+likv2wb4mEP5gsuI9JAMh5UD0sLdrxZNYlo9w=,iv:tC78eTWMkkRey3NY6XpnCNYvvmax/wkyqWP1zsrlQ94=,tag:olLqgVXYtjUTqv9XVF6UhA==,type:str]
  PENPOT_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:lXgRjxybdVkfeom/9VKGDGOti20vvfZ6foOZb1FBJQ3U/yxHzbIwL67LvA==,iv:bN3v69kSTdilSGzQt2LDWSEZ8vrYzzRQsCYyR1pzonE=,tag:sBCGGc5WvgWZ9qetIz2Ejg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSmdUVmZTSlppbThERVRn
        VWpOK05PT29HNzhRL1hrbGU2MktYYTB0NjJvCjFCVjVNOGVCWnRnYjRvTFFNeGJ3
        WG45TnRRMzM0Z0hGT016bUdRbjdndUkKLS0tIHFRZE8yVWpqSlV4RjlVM3BLUU10
        N2VIZjhDeFRpUXpPakVPbGRETk1rd00KSjz7hcIlYs2pns2SnKLWXtuUHNJVTmk0
        8pqliHr35kBJmrUyA7UUVEzfjj1Irqi6coCpHU9ek2XUSOzgcJsn2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T14:32:25Z"
  mac: ENC[AES256_GCM,data:3uWkLQ/zHmjHz9ZuoXjr/WI/S8rBIjvEX7aJ37cF1iL2Lcxa1LSSQBmlFmZggtD9XFT3He2gLAARvZrdM2428T/jqad2c4lPNempHJnbGJXk1TaNIsEDZQAP59oDy9ewccsVez+lhbuenhn1KOjFH2gFWxPthIgFoPwOGH+MUSg=,iv:buyxpnnOagnEH7HnNM3FEHFUgD4ZqrpigT2gNUL7LyA=,tag:PZe6D5oCYEaRrtraddiLBA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
