---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./grafana-pvc.yaml  # Temporarily removed for RWXâ†’RWO migration
  - ./secret.sops.yaml
  - ./helmvalues.yaml
  - ./helmrelease.yaml
  - ./alertmanager-telegram-config.yaml
  - ./longhorn-alerts.yaml
  - ./authentik-alerts.yaml
  - ./prometheus-ingress.yaml
  - ./prometheus-outpost-ingress.yaml
  - ./alertmanager-ingress.yaml
  - ./alertmanager-outpost-ingress.yaml
