---
# ExternalName service to reference the outpost service in kube-system
apiVersion: v1
kind: Service
metadata:
  name: prometheus-authentik-outpost
  namespace: monitoring
spec:
  type: ExternalName
  externalName: ak-outpost-prometheus-forward-auth.kube-system.svc.cluster.local
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-authentik-outpost
  namespace: monitoring
spec:
  ingressClassName: internal
  rules:
    - host: "prometheus.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: prometheus-authentik-outpost
                port:
                  number: 9000
  tls:
    - hosts:
        - "prometheus.${SECRET_DOMAIN}"

