apiVersion: v1
kind: Secret
metadata:
  name: langfuse-clickhouse
  namespace: ai
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:OyM7rEAhj3UxsA8uWQ==,iv:hJBOwKw8mnki44r9deNzQmw0Vh0x5FN1JSKAkPe/PEs=,tag:9U+OVezduYdldsV4pTqMUg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc0dQU2w3S285akwyaE15
        M3BYT3FXM2tOa2xhLzgyek1uSnkxUmFWZUFnCjdhcElEa1FBdkgvVUhWY3BPNm1P
        WXZ5NU90RXpVaGdvdDVJdTY0L3dPUVUKLS0tIEVaeGRHb0kyaW9nRlpVSGtvNGVs
        bkVscGt5cFFRQmxGT1ZQQ1A4aWdDWjgKZwnoNcPzQrR+icc0Xswx2D5ZAdJwKBem
        1zrlevLyYTaUeCw62kvIIX8PLLb9hoVeB+aZLRa2K873VoOnElw7uQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T19:57:12Z"
  mac: ENC[AES256_GCM,data:ZY2h5Rf1ny9HC+a74E/vN3mOK1PueAM9of81LzCZV4ObH3JgQtvQskjC9c+lvi07Ir1Xy0HrSU/V0MGvVZ8TJRoxK9rsNvIaSbK36tzWMPihR7W1M3sPID5cykYdMw9QWUck8ywkWF3+/QHN+E4y9o6y/YnQj/8Ek3lyzMZdc9E=,iv:TrYnGxcf7ekTkXtQQLSrIa1Q38GJKoluVpKxpP46dHk=,tag:T+FykxlSBhTbPstAX1yKyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
