apiVersion: v1
kind: Secret
metadata:
  name: langfuse-clickhouse
  namespace: ai
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:tjhAcwvzfPG05CUzDvveIwmjTBv5t3ru2SW3HRYqvmo=,iv:1rsXTz21LAztW2zf/0LrIXYhp+B/7OSZGUrBYu2FvFY=,tag:/GgJGycAMKrXulmwt5zFaA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS2FQbjczTEU4bGYvc1Az
        MnRRRXZmL3pMSXdYVHhOdWtEMEUyWVU0K0dzCmQxdXA5MWFIWGhKVjRVeTR2VHRi
        enRrMzFZdDliVk56ek1PUFJ2cU1WMFEKLS0tIFVtaUdBcWh3MnRGbG5mV2Y2NnBF
        RVRyRXRHNTlxMUV2SVpFWU84RkY5b2sKP5rBtyZUWYnE6o/vfPQmZbP/ww2yO0KW
        rrZA9MjPYxJ8rtFILxbD1kOk4LgtTKm+O7Q6xeT54CxRpGTOZ1CClA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T22:30:20Z"
  mac: ENC[AES256_GCM,data:v8i6R0Uo00ik3k1p/LegauNW6WLlI5OzCIBM+X6GxHMmvuXnufMZoDSFnyyRXdsZV+82NyAlP5SaQIHuMgNqk691fHLSca/GvpAI45t194kerWEh//9cJv/Kzgd5QGu2uGUQBQjJRiGmiEDvwn3XhB/nDvOj6IqSyS8H81MGkf0=,iv:cgx+P2Sw7n/MGaR+OuR95qB9N8IXA/msg+t0UaEFzYw=,tag:xvnqQbk0upN/8PLtgDNcAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
