---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - ./postgresql.yaml
  - ./clickhouse.yaml
  - ./redis.yaml
  - ./langfuse.yaml
  - ./ingress.yaml
  - ./secret.sops.yaml
  - ./clickhouse-secret.sops.yaml
  - ./postgresql-secret.sops.yaml
  - ./s3-credentials.sops.yaml
