apiVersion: v1
kind: Secret
metadata:
  name: langfuse-postgresql
  namespace: ai
type: Opaque
stringData:
  POSTGRES_DB: ENC[AES256_GCM,data:6q+r1LoU/fI=,iv:jFr1tpNL7hLQsCetNEjAtWnyswpvHkKxvQQ/nQZ9Iwk=,tag:XOpPaVDrHnAc+5rJOWDBcQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:WpIa/7BbIhk=,iv:oKHPJ/hL1ZHdWdM4dhm0G3JSbCpKYgvLgptHHmFbryk=,tag:HPfBLj6tiBUWzsg3m8bwDA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:z1a7OI//+nKeNh4ra9J7SsPEyJgCRgjaIGkZA9g9gpc=,iv:e9FcX5qzSPGUyNyZ+Sv3rsmIt2Axs9sQJhvpKpmF5UI=,tag:yGygQI35XwTAmk6N8saNXw==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:aKuWz60pwUqdkL1ATrbVsaINlIG9IKaRC8+ggXUbOF/Vo6FRFoFdIDtnB+75nnpvjFFJ0eWd8N/FLxWUc1twQZyu3O0c86C7hhZgbcJF9AIfB44kD9DioQ==,iv:kNCcW2rxC7doY4musHzHrwpLe4XvEkEAcoLYDuUMJPU=,tag:99N/X5d9lphtoekAKUKVMA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NWZQcnZLVTJDd2x6dTlH
        U1dFVm9QQldMTXZpQmlTOWhTNk4rNGIvTDFZCm1CVkZGTUVXc1VVdXVnOWRtNFgr
        NG5SQU9xbEVWNXZzZTRYeXJxaGY1dkUKLS0tIFhSeUpuOVRUdThrU296aEx0WW8w
        bXRXQ0lhbVpUVDErVHNnTjc3dmdGWjgKYPVGEFYimQnxZX7FMHa+6BqvjKkvl0sw
        e+OQDIW1GVMqSXOX1Fih6P9GkFV6f0sxnjusxzIYdI1u9HRNsgLQWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T22:30:20Z"
  mac: ENC[AES256_GCM,data:26Bgeo7ZPGS4oNVHnAyihbtoxRU2ocSx37S3pbu8BZqprueM9MrAH44C7p/oXjcLphJeEr+SNw9HeVV24JpWLA1lJsuhlEI7KZPGcEdcTH4u8LPOlxehJbeqq/fhFBGi4bnwCH/3126t2vCavAEgyEe22oUTayjY/qBKUzmJpZc=,iv:WHDBhbTz0uGHzfeDtvLU0+ueR8el3r52S5DnYvLKd+Q=,tag:P/Hv+RmmqTgwMZ0qaIX6hQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
