apiVersion: v1
kind: Secret
metadata:
  name: langfuse-postgresql
  namespace: ai
type: Opaque
stringData:
  POSTGRES_DB: ENC[AES256_GCM,data:ZzmnPWrQ1As=,iv:6pHqgxDY1AFonMS+YCxa3h1gRXKRU9d82NuVUfYGZZM=,tag:kz6t+dmyxjjgzJbALslOAA==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:fD17df1IPNY=,iv:FWqoAt/jQAYycW+Wb8ixfYFboMv9/xqOCucGwWGcySc=,tag:EFXdA5TRIFknjj6BzbqnJw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ea8D2FSNdp0t4AQ=,iv:5l+SohM6TdSLX5C6Ufyxg3ItPexubk+ipUIqZE3kB3w=,tag:UGHpHgeoYVJfe6rHra6RqA==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:lOa2iOqN5mphYhthLhAdymRT/ABboOWjKy4rBx0EjSnsewT83pdckux21NiaanJA520dGBMd5JoChciJ13BCjbeH/g==,iv:eRIvsgzp4g7lunNDB23JECfKo3kdUb1h07ixtiuzWBM=,tag:4lEgRpWv/+HCryiZr/i9Mg==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeHZPUU0xT3FSTEdsVW5G
        Z1pCSS82Y3I1OFIwSGZ3enVLeGgwSTI2Y1dRCitzZGZ1QStORXA0ZGcyU2cvTlMz
        LzV1bDRkdEVqWWNUcHNGZVJjTG4wU3MKLS0tIGZaMlFPUGl4Z3FsaCttM29ZZVd1
        TnB6M2lSTVRsTlpWalRScXRIS1pqQnMKeZJ7cpqBNyVWB/nFtDvlXc/ii1/w20Ck
        29MGtuE9dqqis+OQtvsw1iz0k3HNraN1lDS1yRqQirVxMIG1BTkpWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-28T19:57:27Z"
  mac: ENC[AES256_GCM,data:eB3yGkQsTB/mfN+aun5n75z+a7Vd0iwnieCj7bLptpK0a+AaVCwUCI6hd6b1tQYLc0OkWAA/51SBZ3tWz63di8hBr1ZnxmeTbNKlDcEfusI0ZsMISOOk6W9xHgU78zsDLcsSfUCsQhIT+pYKhOIxFQBKqfcVkJDlBp8BXUkKqr0=,iv:rH2mYqjPpjVQyLlhuGmd/UN3bWbXH6/nM8wghFfSCag=,tag:YRxVnXiPRLX2gOb5pEFd0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
