apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secret
  namespace: ai
type: Opaque
stringData:
  nextauthSecret: ENC[AES256_GCM,data:mW1DrXzzVjknE5qlmr1AP7tYLmpTZgxBBeJyKLzQNEhWf3fztud34Tpbnz8=,iv:lxnP1hWeh7WjrB/RgD+cDvQ1Ln24DocFV4ZfPZgK8ts=,tag:p61/2/szurvp7XQi7rCAfQ==,type:str]
  salt: ENC[AES256_GCM,data:/n3GI12SJe197ojueZGfkiVH/gEXqese0P8UJ0Nh2XrTpZxiUPfxN31dy/c=,iv:0fv8Au3S5kFeNdigzdj61XH4p4+Chf4g3rOywbAZMBU=,tag:GNzLWbxASGzR2alh2KFzpA==,type:str]
  encryptionKey: ENC[AES256_GCM,data:7LrgNPhd4dCW5WcoJnwjQeNQCof7y/PCDM4hGv8gvxB9FzqK9tMMcY3T16NvGQrsgMJEbeQJsbf1ficTG+Vfew==,iv:/kp2dSx7mfTlLu776QISogb4XUFyjjJRmyeYdiC4EwQ=,tag:o5oWv1JCJyCRs9IVj089xQ==,type:str]
  adminPassword: ENC[AES256_GCM,data:vts5BuTqc88TPxE8l3PLUZLedKPSmnMU/gjnOD7aBbPAvOPleVMrvU5k4q0=,iv:2y1CcDW58JVUf2hGOSHu5+F3jcOtOqRWo5FRjP2YeiE=,tag:ciX9cqw+KEYKJemSAlBxIA==,type:str]
  oidcClientId: ENC[AES256_GCM,data:YHSXXypzIwY7vlNPhrNZrmwoNRdr7VDYfuFTooYwkjsc7HPy1u2ywA==,iv:5BwZqOmwdr0qNzkLh0GFfWC0tLANSoVYl7tl6VHmAII=,tag:Aw434YR7dz0wxpmLsy/7yg==,type:str]
  oidcClientSecret: ENC[AES256_GCM,data:Tb3ICxkmz6eXkUVDZXcsXEaObq/NlUyDWYlb/lphyPJT5HQAofKxe6G8QsdYf4BwAtaFofym8c90ROsGdBh9KiXqc2rLle9wPexv/+/QmeW0Z7J0PJroaIjRvDF71isLN4nmWMvtOtLVl98J1NzZAx25WRAawZ72cb6iz4xHJT4=,iv:xE51jpS+B4mY/2rYojc8Frq/pEuQ9X85KN7uY78T1Q0=,tag:RAhfcTjG0HFzleC7uGLPlQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eTVHejc1UENscFo4MlVF
        cFU2dVJZa2RyWGlFd2hVRG5FMnRlZjFjVEhNCi9hVHd4MHdMdHJEQ3Z5MnJTdUhW
        VVBhR2tRNnJDbW5tY0ZvMHpxMHNvSWsKLS0tIGU4QTVwWWFPZHc0aEVKeXk2SmNw
        ZW9GNXoyMkVpdjZGSk1rUCswbGQ2UU0KwBb3wy/jhnC1a9KmFPh4XEpRqjgg8MZO
        rF49gwaCZFFpoF27Ek6cd+pFK2M+hZF8tLGkGKbqG23Nh2O/3C3w3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T13:37:28Z"
  mac: ENC[AES256_GCM,data:H9OmG4fn+aMx8+k14FjBeMYblQx7oFEooG2yjMAOVdH2pbHeBCI4rfY3dzIthQWmvZUvSiAaFx6IftroYttt3ckxsx34BP7QFpDmoowsPK3dsw92wDqPK/nwCOcsqIf4YP2TQZf4/NvskZkP7KLi/F1PmdSSardMEg2soOl9Dvk=,iv:t5r0VJ1Ctloo4uaqizBKiCkoiBYj/4k/PPSEhYDqdq8=,tag:7vj1dHgWgYnq+NZDHHbp1Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
