# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-production
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:oUyerUP/RNhyWaCToWJl2DBV6K/4IX9bnQKaPmpln8AK5vS5eHSDITzikoHwFRvssShjm1fy/xMORerSaILN4dObkoaRJU5RWo58A3xWsg4SEBeNOaQSDxW9k6Kpzmj/XWr1SDNrmYcuq27FQMfmniKC2NV59QR54tbhqmjT/SnJiiqAVDNP2B5GL/bDcah+zoT9ZOvaskRQe44CUxbFfN7O8NlS9M4WhlQAJ+IOPSqml/ceFdyuO69x1/4LNB1QgQQL4FJUuskZF3k+cl/mnGm4oZyUFrSRYiGksXC+oDw4kmz7U4M=,iv:ddLUufKrHXHcoBTHw82riFpJ6pJXm62ZP+t4ttjuA+A=,tag:tu7hoFWwLWMFzQlOkSrArw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bXRiUjhzK2RTbmVybkhu
        VmRseTlzZWk4andhR2oyeDJBUURxdDFSRFE0CldBL1VYaDBrWktveHdCU0JHbS9z
        KzNHMFc1aGRnSnJtcVJBYXNzaDlZb00KLS0tIEM4WDYzR2FaMXZ0d3pmNEw4aHZp
        U3R3R1NNSFNTMG5qVG5hY2xubjgwcUEKnIAAOan7NfvqLYdJXLC8z7JZ7iJcDhBt
        NoNqDh6700RBd4Am3AiJaIo7NOZhL9QKqBZ8Cu6ncKp9M/Csfx4hQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T11:55:02Z"
  mac: ENC[AES256_GCM,data:gTj8c30J96tnr/UxDzbLPQtwi/ERVhITY1j6TvuBLZTsA8uR7yL0sA72dhh4OHkhIQrHsnrzXxX5w+cr4CZj9RabA+v8d9uvXWYu+N83y4RJDuvx8gHdno7A48B3pl/8bvr//1KWLZMWeWzCERUGhUfxBcRNzr7BklzCMpcEmHk=,iv:MIr+RSzoFAOk0NMVITnZ4kYJ3UVXJKknpQBgfL8Z+FI=,tag:NSe3DkRc5F1kKsBYGPdzOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
