apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
  namespace: ai
type: Opaque
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:4GLoAMvacL+wby0RmyYgkFTdGhT329pONUgtqHuEO1SUgmwUxiqE8A==,iv:+IWN8a7VD22ejtgO69Pji4HNrNSuNpwt6MMe93cQfFo=,tag:9ANPDZ+vaxOR+XIZJmc0Mw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M3F4RGJhL0xIUXA0eU5K
        MFVoYWkyM2hUTXMrZ2w5SDVyandLYStVWTJnClZoQnFMemZaMzd1c2tmSFJOdmRu
        bklnRlplSlZsVmltY0J2aFNwRkNuRm8KLS0tIGhxampNMVUyTTFNQVFZSEhrT2Z4
        NmxDT3g2bi9kWWFlZFFUdkVtcWYzUGcKEKHutoRyhA6GpitAPmBWQfLV692OOu4i
        5I2Cbs8p1XEL6hle6NtIBBA3wF82CLVXbZXNUQPYLFdHnmMcbaY3uA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T15:47:26Z"
  mac: ENC[AES256_GCM,data:t73vBSvRxap35nz/4dCshJ/i65d5khh3rRAtZ85ZXn6+9Hme/EOEzTa+NzxVBPDhKaRQC42Lj8sPCvTPPitFtMU9sURdIVuDl5EYnnQ9ZQlHVX4a7RmrumgDoObe/I65koqNHrBYsVtihYpbIIdea0uHCF7L/4plFchZqDib5lE=,iv:Q7aZk746LASQlKC3PI/3N3wrDZ426SLB75YIRjqSp8o=,tag:qqzfnii7otJy115bRLgZxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
