apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
  namespace: ai
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:O/S6IHlxZnHUBHxk5iYBbg62H7GmW1QYxusM+8DVzIFUu/34kQilfJ5uQGxDryHqXMOd0NsXTwK7NVCT3C5Mmw==,iv:g5jZTF0wB0RORQ9Fn9jNCVE6tA5tP2DkV716ahudMCo=,tag:hhg4/C3bvUGhrgIqnX9Tmg==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:eDk+fi0dIqJLMVl3eObnPHNs5QMc1qL6lAalVgvxF66wudv3s99qxg==,iv:6VkY80L448nCTmJmZnBbp9J+SPfyzwOQwPmZ8c8oDk8=,tag:YVDhMtCWNl+xupMTK9dyfQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYnB6Z3NGdGpDOGxEWTRP
        a2hqbXlQWHZZRXdYZGIxYyt0blNwVDRZNVFFCkVYWnNtM1VEYk1KZHc0ZlFFV2Fi
        SEIxQmRGWW8zTE9ZdXFEQW9sbFlRZ28KLS0tIFBzeDhTcmFXMms0Z21VdUlBOHFW
        VmVORDlRQ0U2SStZM1plc1VYcVVNU0EKczifj/2zj7r1PlKNBafGewMjkrWu8FR4
        X0ikQq70eMNrBhYYl9bMamwu/usYq2kHVFid83nECmyK3O96upBTDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T20:27:31Z"
  mac: ENC[AES256_GCM,data:Vm+IkLfyD3G3sbFzpVFxzqRpZtQ6FxKAln881PHgbi8Fdkt8ZpMu+ZQ0fggHyJlO9XrFzszCCMLMBFBA7wLob7SLVLPVL4U+++0ujfoQAeJ1NEEk1lvCYV42/7j3QQw1Bj7cVlnuFSt+xJ1AHCRC+OwU+ABAaSrKIv7NTgLQPZk=,iv:U42wK16ajS4dtnPEGDUhnT6sJHebdrg/mgrlURNzAro=,tag:keuMAUWs8qGeFrAhkQ0s2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
