apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secret
  namespace: ai
type: Opaque
stringData:
  OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:us2OO3vMzfTA2sWRqfDdmUzCdF+2nMpuYZZBSx3TJ2sF43rKkoZC4UF7HqqJ6ADj,iv:cS9aCVBqwzN7ZPqPwUiWmSDGRrnmRBJ+EUG4zEaVhto=,tag:/mFZeupOYjK/KWTWcXb2Fg==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:SEiWtPQA0kZFlOULIVqWIHjTcgSzp+JmUAMazYZiytPoENtA3/o6MQ==,iv:YEfAdcevjF0AV1bAXZcgNDhXAEYwkt/lIDcMDkqo+D8=,tag:/iml4cN5mkyxZtiVbkpROQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSzN3TlhOSzlmeVluUHlW
        azMrckNobnNrL2hQcjJzNDRRVWIwdndWRlJRCjMwN0Rvc3VPUG9sZVV5NC83KzRD
        cEgrYjhQZUU4VTNjRnNDNjdoalJwaHcKLS0tIDlTbEtlVEdIREYwTU90RDFPdS9J
        TU1hQXdiN1h0VndlVm5CeCsydkF2REEKvX0bOd/n/+E86zwUKuKtvIkz8kx1cgNA
        XnOnuLCMZh1pLxEK8FZttAvlgEtbJtoyjxQulaqq9wZsFMiMT70M7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T13:01:39Z"
  mac: ENC[AES256_GCM,data:kHgBa412USbsuZGF2JP99V0HPQEEiS89nVL3BeN22x4W7FXAOUxcKpugH+i+TWBvXH6cVZrIKcelwKxbNKbISU1RQZQDa18m3c6iWfG3F09lgLrLz39IjfWSfNInvXgeg1OLF1qdDEA2HkDnSjmiNjbir+VDNu+o2AD2DurJ78k=,iv:jf+3igMyZ6YJwug7A7lhS1s/E4W2zLmZTSZoH5Zai8c=,tag:r90BlMc0z6V63Bui1EjKNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
