---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui
  namespace: storage
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Longhorn"
    gethomepage.dev/description: "Kubernetes storage management UI"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "longhorn.png"
    # Authentik forward auth annotations
    nginx.ingress.kubernetes.io/auth-url: "http://ak-outpost-longhorn-forward-auth.kube-system.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://longhorn.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Proxy-Secret 56915e032a849697664f1ee8567e8ffe134c7e2dd19b3d2ce16b42c7a487799cb232e4c69878081ea6e265d22693c1283e20c2fe2c06fff5ef986080e78d0263;
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - "longhorn.${SECRET_DOMAIN}"
      secretName: longhorn-tls
  rules:
    - host: "longhorn.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
