---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - ingress.yaml
  - authentik-outpost-ingress.yaml
  - limitrange.yaml
  - secret.sops.yaml
  - alertmanager-telegram-config.yaml
  - backup-credentials.sops.yaml
  - recurring-backup-job.yaml
