---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
resources:
  - ./helmrelease.yaml
  - ./certificate.yaml
  - ./secret.sops.yaml
  # PV and PVC managed via Longhorn API
  # - ./pv.yaml
  # - ./pvc.yaml