---
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: adguard-home-config
  namespace: storage
spec:
  size: "16106127360"  # 15Gi
  numberOfReplicas: 2
  dataEngine: v1
  accessMode: rwx  # ReadWriteMany for web UI access
  frontend: blockdev
  migratable: false
  encrypted: false
