---
# Longhorn Volume for Import
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: teslamate-import
  namespace: storage
spec:
  size: "5368709120"  # 5Gi in bytes
  numberOfReplicas: 2
  dataEngine: v1
  accessMode: rwo
  frontend: blockdev
  migratable: false
  encrypted: false
---
# PersistentVolume for Import
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teslamate-import
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "20"
    volumeHandle: teslamate-import
---
# PersistentVolumeClaim for Import
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-import
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-static
  volumeName: teslamate-import