apiVersion: v1
kind: Secret
metadata:
  name: teslamate-secret
  namespace: home-automation
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:TnZIx7RTgKkbsyya25lYSrI42tMcCTmYw219D0Bb2kw9jyxgpYNMUNzT2d4=,iv:Z4qcbNll+x5jws4ycir9Gsp40Z5o3W34jJoQYjFE7A0=,tag:X1/6QB7m+6fE25EkBY22zg==,type:str]
  DATABASE_USER: ENC[AES256_GCM,data:3vrxq3Ox6CPX,iv:V6TJt5ydz+BD4Ot0u+RgABFPjaax0NOeCTYteKTcoj8=,tag:Ydm13mvRn77wCPIxDN84QA==,type:str]
  DATABASE_PASS: ENC[AES256_GCM,data:xx3c9Nx7i3INofK+t+S6vQBt4xfP/FlXRjZbx2J3UPQ=,iv:rQw8ctHrlRNh4p80O+krhXoGwIBTAFzx1/YBWnzN5qg=,tag:RuCt2KFr9hH0wINOet3PAQ==,type:str]
  DATABASE_NAME: ENC[AES256_GCM,data:aXp6EMSZ3aGe,iv:Ks/qISRtuSW+vf4nbWy/nj3yKpL7+xivp8ZfFFVC4QU=,tag:UTTM81tJ7BH6bk97H/4RyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSDBYczVqemRTNWd2MjFt
        WTJsTlNhN3FmUUR5LzU0dzl4RDU5Vi9YSnlrCmlseHM4RzFueFcrQzFWS0RyN1Bi
        ZXFaa3hJSHZMSnFRYlFjc3NwUnlQa3MKLS0tIEd1ZWRDSW0rWWExTUxFRTh3NUFo
        cjdodjk3U2lKcTYrNnVTR2FlRU42cjAKS6OhKsNRURLP9SM30rfqA4xXicRq740l
        jJJKtPuoWkIEVWYjFoWy0YfMb+x/jcA3a1Nta9XsoK8F1TuEw6MKrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-13T14:26:04Z"
  mac: ENC[AES256_GCM,data:sT93a4h36OSZdr89yodvgjkn9UeysZasmiD6M0w5gctwW2tGIdR7esfiBtY07PNi+VAsbyuujt27FyIRTyxZgXyXndvkOA+m38S5CYmFb4qdDsSgJdYU4U7zWdo8mdZOWd57RX06XBtdRreEG7ppPZbcxzY0LdasQCbGeZY/6BM=,iv:o6jZaZQvpSC5L/4F53NS360WoWrkhN22YPtJ8HQdvUo=,tag:0mcqTnoIf6MjNisL9Arf0A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
