apiVersion: v1
kind: Secret
metadata:
  name: paperless-gpt-secret
  namespace: office
stringData:
  #ENC[AES256_GCM,data:94OIICx0AP/TTW1rqErxYCJtvoHB9+xxewzVfkHN7mpXvyymUSbzpgzf3Q==,iv:sl1XQF1qHGVrrLV7qwj7wQEtFhj5maYVyHBRCfgxiPU=,tag:XyCdFlWQO7L4Q8d1r4gNwQ==,type:comment]
  PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:6LynXsk84L2m+e/85y/GbxvKmJT/B+PBKE/oLyati4Hm6WYzxsxsNg==,iv:8QU5CVXPTKgRx9o/FX+CRun0b2d+pX396eVstWyJfhc=,tag:W10+RJS6FwIuuOIbreA/ww==,type:str]
  #ENC[AES256_GCM,data:TXeHLdJd8H0qmeaT2xXCt9GcPhFH5Nlc/CIKC7JjFKfSvAUm1A==,iv:aJYJLXA66Jm9pDBaRAxBFFqWYThVq6fwszEW6Jwh8f0=,tag:9+JE5OlxnCIDJh+sD1p3aw==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:9IC8xsnt0VrTbQ==,iv:scXthHIu37qZpvY1O76sclMHWmhD7PeiLhs8DaJONPI=,tag:rgwaOxOrPxGEK8KyFgfSCA==,type:int]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK2k1MFZ4VnYyUENSVEVG
        S2FCZU9ydExQMXdzTDczUXdpTEFVVDMwNDJjCmt1d0FJa2ROZktuakFCU3kwbWsz
        UWtGL28vQ3RKOXQvbXpyYlhVN2RQUUkKLS0tIDdtWlhraGtGU25NMk1CMGI3TlJK
        TUU4Z3BXS2ZpaENPMGlmVE9nbWxZN1UKIBpUvpu1A9IdlEnGc0g/JzddKDSbJ1r3
        Agnq5C4IxyUsMWKJMss8Nqm0t+YySMqC1kEEuHhrVXqebLZZcxbzDw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T18:48:44Z"
  mac: ENC[AES256_GCM,data:/fbGhqjsyktlW566nS4HZBtTOA9AeFx+jjZBqagX+elPBFedX5lnZNKUCCJJOlFUl6/zAo8rOimvf3MUuu9eyM6gaHhTT8ecsrZwK0UEWtT/HDBcUg/nehFS3olL27EUb0p8AcuDj0EVnupFDjhHapJOSclJ5ndrttTq5P3meQE=,iv:PuvA7HjxPBiWag8YtDB/PF6KY9BHjsHTOPS+gY5qp9Q=,tag:mvSlTEJZAYgoGY3kWTccBg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4