# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: my-software-production
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:2eVu4rchRkgD0vBM495mO894hO1pLSI7u7YliyB0a8Myh2c11ZT9M3CeVHXnpy2ydR2w3f1+EMDlKRAujYHwr3HRwblvbCpFp6bjGjRMLybfVVjSIuyjp6Ms2kF+hQQgF2TzBgpo7ArHKLnAeQAXNGMdma9ew8AibF6mIVIxQI2OFddU0sYX1ZWo93OET6L+zTIFRpKTBD+vH2XMaOyAEsBIdO1pX0Olz0EHQ+0Ug0EPo43DZ3Hr7udcb+n9DdxnUBcm2A1yK8YgYpfn2FEc4g5N2S9qU8cHEJKJvxyp7mkbNvzhMYc=,iv:KRCvAz+1jaQsER/Se8uMeIDV3o541lqKrvpvUTowAxI=,tag:r7QyNijdhUElY12XGLrJ5Q==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVE43a2ltbTBsT2VHZHN0
        RFVkVGlsZDdNb25IdE9IQzBWemhMTUhCV3h3CmU1QWgwUHFyOEdhWHlYeXRGaU1T
        MVNpWmZYM0hmM3hhRTh1RjZIbis3TVUKLS0tIGxRV3Y5Z252OHZIajEycDRwR3p0
        V00vUFRibUhmN3BrYTd6S3NMbzBhTWcKWY28zb8/531eFBl+WBMaJfv4ll3BAWDZ
        4mz5i0kzPSal7kK+u3kRmA1QrA8VgFO6q5lN53TyVl9cdOVDqL2TOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T11:55:02Z"
  mac: ENC[AES256_GCM,data:pClAmqs882zKIhUuNYimPr+mkvsa3J9p6Bb7Gizcn1uEmnwIqXg0GZkhU/iklhv6mXMd15UMULq8ddhKzkvcRfdDZY02zGRtbaR5jXN9xNH5qOLOBywU37IAZ7ruI/Q01ZWoq1fyUXRwXNJRXJqAdnDwQEk6Z5h9Tgv2SyU/DLY=,iv:fqpHge1XlLKR/SvoLzNl6O7cFljrMZIrr63NC94LZ30=,tag:3qo0whdTXoiQdmcMCSx79A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
