---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: absenty
  namespace: my-software-production
spec:
  image: ghcr.io/nachtschatt3n/absenty
  interval: 10m
  secretRef:
    name: ghcr-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: absenty
  namespace: my-software-production
spec:
  imageRepositoryRef:
    name: absenty
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^sha-[0-9a-f]+$'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: absenty-image-updates
  namespace: my-software-production
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(absenty-prod): update container images

        Automation name: {{ .AutomationObject }}

        Files updated:
        {{ range $filename, $_ := .Changed.FileChanges -}}
        - {{ $filename }}
        {{ end -}}

        Objects updated:
        {{ range $resource, $changes := .Changed.Objects -}}
        - {{ $resource.Kind }} {{ $resource.Name }}
        {{- range $_, $change := $changes }}
          {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
    push:
      branch: main
  update:
    strategy: Setters
    path: "./kubernetes/apps/my-software-production"
