# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: v1
kind: Secret
metadata:
  name: absenty-secrets
  namespace: my-software-production
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:H60PscBnwD5mat13lPTgO/065oXvqwW/fnaumOC/NoC7V83Hr1KXyEg/KF2xZhXJQSwgvOVkSg==,iv:yrTuvoBwZxKVrEn5N0RhAj8bf1VuE2VCmCpnxq6V2uw=,tag:98pRvKwsH8iYXl62mKy4rg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZzJPTnREMks5UEFSN3Jk
        Z1RrN2lpVHVXbGJ4SFRZUHY3bURMRS8wY1NZCkIwdk1nSm53Y252SXhkdTJiNkNi
        eHFZWXZRM1pST1IwREMzbXhlQ29EUGsKLS0tIHp4ejlHRldnSi9aaE1ZNytQci9R
        NGcyK2NjMkJoSithM0FiclppbkFuWW8KhWPq7RpVA0NM9YFpDTHl14soTZHU+6zJ
        dRZWV85t9EL81TGsPgX/OEE0iE04v33SO4jR0QQF19dMmKSrkfM1xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T19:56:27Z"
  mac: ENC[AES256_GCM,data:TdEOZL9NN4MchgMDo7oDNO7QxwFPlaYP+VAcPjQG6Qm7bJYwPXu600ZWZMsdj9eoYF3r8o2pekuffuQYdVy8kzcsT9MU7oJ/6wsSiS+eFpIfH3210oC5fRP9ybDJk+IFTbjonJCCWvhINnD+jIglBT2TyH+rt6HhZfKOv6UeCW4=,iv:+ytEVO4NxtryrN3p0OwEynxVdvBOdiXMPsTHZhmLq9I=,tag:B2SJ4s458c78cQU+/piLDw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
