apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-config
stringData:
  db-username: ENC[AES256_GCM,data:BjG5m5vGJhZ3,iv:b9kFxbNStDGWXYur+Kdot9R1bEhrEj/e3rMAZMWSrFo=,tag:gNECydC29NYlpLQDT7ImzA==,type:str]
  db-password: ENC[AES256_GCM,data:6SMlzJRvkHcOgKcaIzyFODz1QQ==,iv:f+O60LDDrEK5Q2Xk3AunppyV9nNPIl/a/SLDik/ApII=,tag:8IF9ECAJs67cb+RevlO2lg==,type:str]
  admin-username: ENC[AES256_GCM,data:GC8=,iv:YqtuxLgjlBkI+2JuXMj5zSjkfdGl27lmggb5EQ4yMBU=,tag:rXB4Ejsd2Omhq9DzgwSYzQ==,type:str]
  admin-password: ENC[AES256_GCM,data:899Gmd+3iDiR6g==,iv:GHStBC3DF8j5Qqj2Dm+D7ETn6VEERWbKIhEoLdu7wKc=,tag:rn4W4qny7xCBhSppsnP8mw==,type:str]
  nextcloud-username: ENC[AES256_GCM,data:Dws=,iv:UvKx5CAaiy4gdxhJVTneOgCZi/WoO2kv6Koime+mucU=,tag:NqvVTzuHv0L2QwnlMxFZjg==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:5inZTj3Mfp+U7w==,iv:2y5hkj/FUc2aIU0yQE9/F/n2v1/E5cxEqhkeyz0uv4s=,tag:NEKCrLYgs5V2kEs9gtVcfg==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:u23Hou5DMCbXG9uyWeQZPZ5Akg==,iv:Cquc/42IcnhKzeeXtxg2FesXX8OHM1FsF2+ruKLXaJY=,tag:zUPi8jwQSeuW0iQE4rdiBQ==,type:str]
  mariadb-replication-password: ENC[AES256_GCM,data:s4wtwhc4eF+v71VeyMouz9sJHg==,iv:JP+vHoZchduzqSkFHKm4L3v7BTV48ELWJHpafzao5uU=,tag:agLzcf8Y5/U2hD9BsbffgA==,type:str]
  mariadb-password: ENC[AES256_GCM,data:raNecdDLPGf+KU+Ec+dQW5xGPw==,iv:h33meyDKn3Xdx5YmzbqRcoCZTTqM5yGFIRfA7OWWxCA=,tag:pg0XRhJPr0q++owA6p0oRg==,type:str]
  metrics-token: ENC[AES256_GCM,data:kicu24Wr/uBY9qGd2fLzwGdOF3Mj/PiJxEld528nqGND+zM+50fXOqJgaJL6pZfA8vdcZPEVNBDY23NTeb5oCg==,iv:e/qZUakLZHgk5OfOEkpUcUAjbP9vD/P9CSgmNs7Xk44=,tag:jyfskfrfVsUmhq+YTbbd2w==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT0cwT1dERW9MU2RPWVVT
        RE9PNzV6UmJCZXd2K0JpYmptS3lMTUtBaGxrCjJlRVkwVjFmTldubkhyWk5xYWtT
        Sm8wZzBuM0VpYWU5L3hiYThBdE9oR2cKLS0tIDlBZGZmMzRTTmpVWnVOK1hGL2M4
        eHdZYWJka1daVGZTVm5BRHNOR0Q4UEUKlvoerCUGckexRXDAV7nGFfow4BERe240
        JeeX04p1EAaQ7OAl27FDzX5Ms9m/kITS/8phdJRI8xBNiH1DywYP+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T00:01:26Z"
  mac: ENC[AES256_GCM,data:ZXn8fFykUeqyI7xnWPkR7GHSaz9j9lNrN7CQTQqPouawzvaKV8fvOGzY+C8KbFWs/x2Nfy7OpkzoC5twD7mfhuqTJErcYmB7fa4KfnnfzAVwENtPvEIx/aUXw/fbGDFPyXpyVfoBhOuLIVcK7TmmRkT6y7kgGy1bljLQA3gI9Lw=,iv:L/I3AVHAwRBwG0o4RhYmOAOyYKJB/9Nl0kgXOMPiZdg=,tag:oAektzl1shcO4TDwwT6p4A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
