apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-config
stringData:
  db-username: ENC[AES256_GCM,data:edwKGFJfHVMP,iv:030XAwD5GRcKTEcgBok08bAoQnxtdBJnN2rbXVsWYmk=,tag:mm/Nl3frGOqedsUwJdwyKQ==,type:str]
  db-password: ENC[AES256_GCM,data:KLpeD+sSqMbaQaSp0QjOI4eD5Q==,iv:ITTmSOE9YKtrNM5bIxralQO8Tc/4Vj0SHVHHrud2Wvc=,tag:b1KkZgatqTKjxJ1tGBZL5g==,type:str]
  admin-username: ENC[AES256_GCM,data:TC8=,iv:kpjgdpte1bvRzwhGpwA6bECcKsC0ASqLRrE38uwHeXA=,tag:aRCItHRp/SsTivf28nDkBw==,type:str]
  admin-password: ENC[AES256_GCM,data:DSu34Ah/8bebuw==,iv:1NZLRtV+6DKnjVyrT57Odr+G2aZTMtrO+cXjGLh/8So=,tag:Uddx7fH6t6MJWBzTJ2lVfw==,type:str]
  nextcloud-username: ENC[AES256_GCM,data:q/8=,iv:c20lG0DdnmvphtHAqkwiwRVK7j+0okk7xLlMCY73NTQ=,tag:JBm4KlCpvC9zyZYYV791XA==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:zVe0m3udp0IOKw==,iv:ImGmfiTuzHy+OZYzCJDYcbPH7orrPPsWLZjyT93iYNY=,tag:MVwamINkX+FSfk7DGi+yZw==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:7tpRNgCuoyjelWfKGRE79oTsIg==,iv:okMXhYKCpMqZtq13TwpFvq3UIhigqb5pBkKiUDeDYRA=,tag:V+NO1Ht22iz+SRVOaoq1Sw==,type:str]
  mariadb-replication-password: ENC[AES256_GCM,data:q9attMA7ss8oGG9Nf8irdLvY3g==,iv:fOttRflc5SNZjKYxpDTUMaFR/+AaSJK4UjPOn5RvGWE=,tag:0oSWwrghFMY93B/K2d6qeA==,type:str]
  mariadb-password: ENC[AES256_GCM,data:2urAcBi40PqTuJSbmmYZJrPE5w==,iv:VZjXZMhfs9G1BeE+7i4TL9oBpdDHTkWDpZd5nECDSLU=,tag:AUVqOQdspXDRjm9Z2j/2tQ==,type:str]
  metrics-token: ENC[AES256_GCM,data:MkqW9DCG7QpWLVoXuXgRmAkbFXga+FDOdzGB7M0GPl6aIEop7v2PQdMsQ1jp4XaNKU6H5wsL4T7OqNaBg5b6Rg==,iv:paPsiBOYLwbROqDVdXq2+pP5tmjZsrG1l1V0hJGKM/4=,tag:M6E06xnmhMZUCkXqcYg1wg==,type:str]
  whiteboard-jwt-secret: ENC[AES256_GCM,data:qW9Mm8/eYs88RumFMzeW2/UJbcKxjnVO1F9dnFRKBqb/tju/twi7eFdmuei6zrH8G+3vOiy0nLSl5p9LEmu7mA==,iv:4fXr/8K2jCrV6NN2J+AeHS44lZsZxNTHBRkc2d4jzpw=,tag:H/bRdab4QE5mgcei37qeJw==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaUlleTNOQ1J1R3U5d3Fu
        SVFLallFQnhUVU1iTXErTVdJM29aVkhwL0RjCktxUzBLK1BqWmtNSTZBZGtRaGN5
        TEhRUkFMRWlYb0h1QldJVG1KdVRyOG8KLS0tIFNhRGQxMGRYV0JId2I2WTVTQWxG
        L3BBZWdkSkFRRzBSRmVYajgzTEJPTjQKlWg+iZzHiFSz0n4G8rBOC/pLTMV0hMJi
        l9vNHsxF4hnCrw86BCkx1UMPSMa1WwHPN1DjUVihDSaLWzIQGEmXSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-01T17:00:59Z"
  mac: ENC[AES256_GCM,data:duYxe0UI4kRTzuGpqHbZSGu+BGUxeBHPrVDUwkPohlMwJJxOxYpm0pyqP5kH4jH5ecG0KXf0GPMSqzix+9mZjMgkT2wg7Wzz3Y0LDx7DoZ5rl4wqPCi0iQYzQt+k5Ji5zK8gWkCXElu15cv05l6eHtj15l7Q1I8x8CXODAtqS+E=,iv:UpKW5w6h6EHgAVrI6WP9i+78uwckKCv/V3Zl0WCqxyg=,tag:9ipv8ofzrhQRuMU+8N1o8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
