apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-config
stringData:
  db-username: ENC[AES256_GCM,data:+4N/W5zwTe+l,iv:X44s1UjANF6PHoQFsgYfub3fgxfAqvKe/eEAvpBzNFk=,tag:HQh5UuEvHtovmjNAYBeQ6w==,type:str]
  db-password: ENC[AES256_GCM,data:8pz4TABdkSfTy0e5jkYRBHIBkQ==,iv:hxBvrlpG9FoPR4FkNWccVR3p4rNULKwYIqnpyQaWhfg=,tag:7N58hjL7uG9YChsbbVX0UQ==,type:str]
  admin-username: ENC[AES256_GCM,data:6K4=,iv:ahBVw7ELdnsFrxo3E4H/vCL2B11hJe6j75iYcPHkC2M=,tag:SnkKqU1fNtGgiV7koPcQVA==,type:str]
  admin-password: ENC[AES256_GCM,data:ewOLQkNrkKPfhg==,iv:TV/R8l52kyeK10HbpxukWkGNMC8j+9vfuZw4C49I78Y=,tag:ZNqEFio71mN/YHmviRQflw==,type:str]
  nextcloud-username: ENC[AES256_GCM,data:3fk=,iv:R0JbkLKTTRXbZhx8Cw1BlkIOVQKvIAPfpT7LUuEVyaM=,tag:wrlywI1unq27BxgMq7/ATw==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:MOp1EDlJtYLh3A==,iv:l1oqL08NoX7ez4ucJvv3h6QGc9To39z8oXzq/KRIIzU=,tag:08nUGnO99XT3o9RcAfKOkQ==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:1/i/rdH761t4ywT2wqq1rKDclQ==,iv:onUknFFtHaoP44z3qY71lEyD4LRMy9XQEnd9w4vV6mg=,tag:LuMtxq177ZEhCOY3ovni8g==,type:str]
  mariadb-replication-password: ENC[AES256_GCM,data:Srno+m+sZUJMbSJ0k3hxbEq2Qg==,iv:RdUJ2TaKSiJo1FctJc8s8YzBlMC6PrRFLDUY/fQnREg=,tag:3kegB+PKekEZFYZGH216LA==,type:str]
  mariadb-password: ENC[AES256_GCM,data:fHlSK4j9zjV3/67Swg+BKz1F3A==,iv:JGFWmzSC15fzyleHESuyeIFdyOU8RcXj5Vrj6ccQGLE=,tag:7ClkMeZTAABSCqRB/gEvQQ==,type:str]
  metrics-token: ENC[AES256_GCM,data:GlVNeF/8G68E3qnLb6JC0D9U02q6V9Zm9a+7aqk=,iv:Bto1wcpH1TQ9SIPhhl+GuT8KEGpE4tJi5sISpYJGDjM=,tag:1iqEZntRK8AOs2wS3sBUZA==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkc2hJTDlRWFY3ZDRkM3Fm
        Y1lteE1qcnVRNjg3K3NqU3Mxb1NnTWRhK25JCjFKYzFuUCtjUW1oT1BvS3gwTDh5
        OThZa0RFcC9IWFdoYWh1NEdDSUFNancKLS0tIENXZWZVMXJpUjJLRUdqSVVlT05I
        cGY3MWNPbjRuclcrRDM2TUxIY3NXK28KzpoBdksbsHWRNJMxVnLDF41fr5kg+Szd
        xQ7vn2boHO8jGKKuOuUAXgo0u5zvjNdvNt32/Jo4a2wIZ1lagzqz+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T19:58:50Z"
  mac: ENC[AES256_GCM,data:Xp/KaNa3XMkxICqvekhnk9RBKrmCyBIGSOnFwWO7ai9vRTlo8kVOhDNMJusJ+OMSHXMX+jjdoCnrFAuF3KW71EfPcS4plM9+190XJtnXdsoeY5T0+zzj39Mn2PmVtTy5g2IRYC47U2X2CH+1T7/Dk4xO1wjmk87zxUBYIEwL7ZY=,iv:xFAc5qBugLOMX640xKKTri8GKqfcLZbIGiOILDY1bbg=,tag:QndpP155udjhERitmggWjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
