apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-config
stringData:
  db-username: ENC[AES256_GCM,data:L7+jS9QVfIqH,iv:NpKrKWzxyTJSTtcKczto8/zLN5kEFnrT40EkvcHsrrg=,tag:xOM3FDnfB3FyG6UIslsJ6A==,type:str]
  db-password: ENC[AES256_GCM,data:HLuSeyburT6C2OsaO1z+SGb5Qw==,iv:KNzc1fCfAbGkTcjSd6ITTnZtJM7HJZqsJmFtFdtNwgI=,tag:QIpB9fr+gIhrBg4cku2dMA==,type:str]
  admin-username: ENC[AES256_GCM,data:wVI=,iv:Zmr1fAYSAgrZSURQ7NTfhIWE+BK/QEsOojUh/YuZHM4=,tag:H4GO34oAu9DBVNQXEDtWrA==,type:str]
  admin-password: ENC[AES256_GCM,data:kz3J/k8tWCFJZA==,iv:ueaW62ORtdDJrchh4P4EaEDMibpVqETuH8wQS4euiDM=,tag:e7m35ESJJ7YyuwexXvfDEg==,type:str]
  mariadb-root-password: ENC[AES256_GCM,data:CgTMxMd3K+JQFkHJbmAWWxcVNw==,iv:3cQkcKwzZScWlvlytN7/ndx/bb+brnG3GeTA2TQ6qBs=,tag:2t/4ZQzqIxsJDQlveCONpQ==,type:str]
  mariadb-replication-password: ENC[AES256_GCM,data:PS+kmI71jBwJR9pcvh7T20v+ZA==,iv:dIFNJFzhU4UDYqVzrXfjeGTcGrPtUXoG4kv7dm6NQW0=,tag:1mPFL6/SAO9DgNIl5xlGtw==,type:str]
  mariadb-password: ENC[AES256_GCM,data:hWPBeRd1FQj4Q2wScFOqyvAU4g==,iv:bvlwTnDVelPByT+HOaAoxSuNoqgLI/gae+iaoXptKPE=,tag:97LY3NXTKT3sEQdstkouaQ==,type:str]
  metrics-token: ENC[AES256_GCM,data:+950tq9Gr8R++iWFx3gjdbVuHUHSTPaLMW3Sh2E=,iv:SPPvlTuBLCHE4HobTjza27FY/LVE1GDgivEIDVamb6g=,tag:pR2drSPM9in1PykHDGkEcQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cW1HNE1MQ1J4Z0REbFdI
        MlRGZ2h1NFpnSGNDNDJVNHdVcEMyU1p0eWxJClBTMHZuRCs5ZW44T0VXS0Rmc0ll
        d1ZNYmM4UllONmVQK2piQlgyTEN0dXMKLS0tIENJRGNGKzhWdkkyV2dZanR4N20y
        c3N2ZFJwT1pvU0NBZy9XRndGZ2trdmsK6Am4mi1/yIGtoWfg7Qva8zjgl5AZWRe8
        eMBdAtl9dBqTKlCVkUjDCvR2NO1MoX9RraBPOngpSh5RT0neyqVqgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-24T19:38:50Z"
  mac: ENC[AES256_GCM,data:wzTC1p7Fq6WCjnpKsLBXCYfZGzlUzVwd+l0hP0Ldai+eFCxSSl56CTy94j/2tYp0+NarYtrDWxnHvIDyqeroov6E3q3l5FgMeVa+IaS/UbFigP2jiukyjqZMx0fgDqpttgbCxsExYc46Bk/e5iWeu/8fl0QfI1GjcB1RWOyvqTQ=,iv:u33k2NW6v5jCmITFpt0SAIu7RzoMf2kSc66iifQN2hk=,tag:NWhyC06FISwg1qpz+4N6Bw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
