---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clawd-bot-data
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "20"
    volumeHandle: clawd-bot-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clawd-bot-data
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: longhorn-static
  volumeName: clawd-bot-data
