apiVersion: v1
kind: Secret
metadata:
  name: clawd-bot-secret
  namespace: ai
type: Opaque
stringData:
  CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:8fYDUUUiFs1mdSvbtkvXLNFe2RBP+Vcufk9CraRztJz1dV3sgC6Mh/bTowWxZA1A,iv:oQrPiR/dwOu2aep6h3DedpZs20QoIkWRWwnL2jmLJdI=,tag:gLLbHTCMfHVm9ub6NbOHeA==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:mSiLYfaoT5X4jHDevVHW2BPalQQMYD9J07BF4W3e6roJso+ROtU5dA==,iv:R/NjIUUi0fyu62APZ4rCVJfF+dvNjoXhuTk6Iwu5TT8=,tag:IfBZjfhEY5am8FzZBU4jCQ==,type:str]
sops:
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NmFVb0h5Z2oweUNwWE9D
        QS9IS2Q0VHZqNzNMdUJUeHdDOUN3TDUydmdrClI3T3VRMXU5ZTNtT3Z4cnAzRHgz
        NVY5bjdGUjFYRHlKMElGa0JSVE1Rd2sKLS0tIFRtYk9lczB1WnByN2ErK2FxSE9j
        UkhZVm9OTnI1UFM3UDQ1MnZqczhPUlkKDDbd/NF2c1QVnEbMandVQlnY9emQzK/S
        kjPufWvWAK2ROYmOnv5GCAWwrelmDuoVRxqBGEAUMtj5mOXZoeBMQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T12:38:33Z"
  mac: ENC[AES256_GCM,data:iSeZelubzj3QFVIa0rOBa26RyckAijVnVvt56hdU858v9NbAA/J+xV/CivHh12FG+Xt/L0fPnUtFbnG8/SViSTdLGp0ppF95rb+ot2ahSA6gkAqhfMsmigBdj9MGDfMYQv3GBayEcYIGpxSlCtbIMaX4D4l8Ha3Uz4s44zmwVpM=,iv:DMvMLSb5zgyHYrFEYD3S/3ACrmDwrG4Fnbw6oievV4w=,tag:Cq/pEAg8WeeyuIXRCpLDVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
