apiVersion: v1
kind: Secret
metadata:
  name: clawd-bot-secret
  namespace: ai
type: Opaque
stringData:
  CLAWDBOT_GATEWAY_TOKEN: ENC[AES256_GCM,data:jPGtR2uf8jhjJUVwtbsRe4QuWuSexndwy8RhawyJzcVOH/LCoPwq5QtTLkt+PRPW,iv:quUnutrcKzo0pCraKDfmbyLUkcfqXXEqiW22pkB7aPs=,tag:m8Wb+GdPUsoByVikzKu5eQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsLzU0T05EM2lVZEtTRzVF
        Qld3eUs4N1FxeUhWRUQ1NG9QTGVKaEJKb1JrCjUzZkRMQ1p4eU5hOXFRWGRZUDVw
        QjJmWkZZOTRNaXJ5dUtheUloc29GV28KLS0tIHNBK3BnWmU0blBGRDB5VUh3dm1N
        d3pzdlhXMXVaYm1XZGpHL0JTcVJrd00KIVJuVTgZC32F5UGefxEcST2kuyaHCunK
        WVK/iVKn6ESxHnFE91xxg+oNLV9KJLG11IhSIoo8b0HxvUAmtm9htA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T15:54:54Z"
  mac: ENC[AES256_GCM,data:ZR96Q9fOVlPHvBClY1MBH9tfMSq0+msINBac7TyCDGjaECd1otpEhQP3fNs/Ur2WqssZLY17qH5M/k8PNSAvaxEDTA9P+/NL7d35CTbiBWohBAD2hXAqemoeqov2cHcHdAftOLyA/27SNdLxsG2FrG5y+PUENpHtuve6n0jx+bw=,iv:ad0RzpKHW5fP9L7e2u0eCUYtDTGcEJP5r5WPTFrsDh8=,tag:LnJdhu51OwwK35cB1IFDcA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
