apiVersion: v1
kind: Secret
metadata:
  name: elastic-integration-secrets
  namespace: monitoring
type: Opaque
stringData:
  prom_remote_write_api_key: ""
  apm_secret_token: ""
  elastic_ca_pem: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNG1OSkFEbHlNVFk2Zk40
        Z0FZVG5tUytnUVJhNnFsSG9QOWtOeXRmUlhZClM4R1d0UFUwd2xTWHRaZ1F4VzBs
        ZSt3VkdHNkRWUjlBK2orOWNQUWNjS1kKLS0tIExqaUw4bFRHVHJiOGxzVFdIeFBU
        eUNkdzJFR1FYOHg3OFJoZTIvWHdNRE0KG1h0hJFxwxtkZHvrKUfHbiFiU/G5uS4M
        1t0iBdW2NYq5HjEneFFzYeYRncOGeITn4mZUKwzG6TkP7o1Xuk20qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T22:34:58Z"
  mac: ENC[AES256_GCM,data:vcwwWMywEzIiVUNxtIt+mvzh12NnU4TBSaMdtbjpFVs9PaOf3ZdasT64E37NUB5zQcd24n+9xcf7TEJEeYlmhCsJcE5VdQz8djWVKG4tzpcECFUc+ApjfjbRZ+Mjs0FvXg6dxZuUPT0vid+dMup9bD+OzF0vLTxVrJLrwyajrgk=,iv:R5NATfvI9lhLWqCGB09f9LWgg+Ekgu7ApwiuY3LynnY=,tag:3+8RaGVe2egJq/8udbGSWA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
