apiVersion: v1
kind: Secret
metadata:
  name: metricbeat-es-credentials
stringData:
  username: ENC[AES256_GCM,data:AsUmTzFObQ==,iv:KqVz7eVPTUoA8q1aLRroKWKE5G3YFgVT/wGTGjmDsuc=,tag:wEw8vvd4hM5bFmAKVpijdA==,type:str]
  password: ENC[AES256_GCM,data:0C2wAG/FEdHzGPIkCHGQ24yKqeBtngzY,iv:Q6vCFC9cRY2hWifugPLysgT2fXsjdt8upUlNBV7Zl0I=,tag:cxOu5ri+IO56HnP4GxZLXw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudENQNzJ0THNiaHk4VGdU
        aDlTSWJTZTg3eG8wSGUyMHV3dWNHQUFzcmo0CmVTVkV2Y0JEYU16b0tLSGZiYW9X
        QzRVendDK05QOUJ6VkNrcmJnbm9nRGMKLS0tIERJWFN1cDNURlZyazdSVGpETUdj
        enhQVGVlcytMWjlwRERNaTcwNDRuclUKLuK8liZamstxnp+hpQUOIceeqtO6e/OQ
        +Tvr76RgOrmo9hK9JJhfj7oepL+eg3EOQWc74o4XEsSFyCaKkq4S0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T08:20:27Z"
  mac: ENC[AES256_GCM,data:HGtsNCMDMIkZcKvAZ/muI834wu0HuDLmdkc86ikHlY4xptdLlnV5/8+vRsu/I85937NeQRGdQSKOZRblyvrUJbfZ9+DMVApi80M1hzxnLOqahUNxuNTyI64+HsuN84RnGIGJ7kxkhPfehsYuMRn3n8vduOsB0gVghqVwbb5dIs0=,iv:sB97R6AlrrVBMYewtWL2fy4mndHylEKitdBRkJvxOPs=,tag:3o+bo1M2BpvfCL9u2mFsXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
