apiVersion: v1
kind: Secret
metadata:
  name: metricbeat-es-credentials
stringData:
  username: ENC[AES256_GCM,data:WuRVyNaj4A==,iv:gngJHia5EYjAeagIGtjNcRJsJEQJX7M43o1O9QH1mGY=,tag:eOJmEhNX3pqrx7wYpJB5aw==,type:str]
  password: ENC[AES256_GCM,data:uGfsfJVJFvUTl6E9FNS9RvJHNZnDCmPI,iv:S0I7QQC3sloKpKgLKfMdl65i8dyfzd/rWUnxwyOlLr0=,tag:5Nv4W1IAPYrlkHbA/V75Qg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU2dOOWNvY2tNMUhlaHBx
        YitodCtoM2I2bVI2OXRTMXlhOW14SjlseXlvCkpzeG9lWkErVkduZzZ5N0J2OGto
        S1BHUFhKbUxCUlR6WnFKZWNnL05BYjgKLS0tIElKNXJRZEE3Yk1NWUJhRE5sZThi
        d0ZWTStORzBoNVZJSDhTK0lkR3Q3TWsKdcEDgoTCZ090VgW176SZuSdiW1Q1VddE
        ud3lHZ5ocFYOYSajVfihxD8PO9h63pVM3F4et2kWwYG4W8aG4GuL5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T07:52:36Z"
  mac: ENC[AES256_GCM,data:cJPMyMfqrEpJMgyc6bBqr6nCnPGHvPj3EM4hCPFPP/8T5B5JmhONM+iIAsITu7qZgjqm+5gAQpIWuFYh9tpcrMWCTVI0Qnjn42Tdn4epuCdeux2SRdvW7ZbP1/1J1HYRsGNTPcSepKyRHRshKmvziSjHGgBm8pZ8YMTymi6Se0s=,iv:1VkNfF6TfolFj7WHvOaH/SR208DUCxCJVhpnf68Isb0=,tag:p5A2Ne6yzbK4uucYNJ5FsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
